### ISSUE TITLE
Infinite Jetpack Fuel glitch

### ISSUE THREAD

**Issue by Kirame1717** [mekanism/Mekanism#7354] opened 2021-12-04 01:00 UTC
### Issue description

If you unequip the Jetpack while in air, after flying, you get a duplicated ghost version in that slot, that vanishes if you click on it. It can be used like a normal jetpack and has infinite fuel, only exceptions are that you take fall damage now matter how much you slow down and you cant change flight modes.

### Steps to reproduce

Mentioned above.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.24 (Latest)

**Comment by pupnewfster** [comment] 2021-12-04 01:15
Duplicate of #7224, though thank you for the more accurate reproduction steps of needing to be actively using it in hover mode as I was unable to reproduce it with just the steps they listed, even though I can some of the time with your steps.

**Closed by pupnewfster** 2021-12-04 01:15 UTC

**Comment by Kirame1717** [comment] 2021-12-04 01:28
> Duplicate of #7224, though thank you for the more accurate reproduction steps of needing to be actively using it in hover mode as I was unable to reproduce it with just the steps they listed, even though I can some of the time with your steps.

https://user-images.githubusercontent.com/95510533/144691718-77277b04-b0b2-46cc-b834-75d24bf733bf.mp4

This video might help with reproduction ^^

**Comment by pupnewfster** [comment] 2021-12-04 01:37
I am guessing my previous message didn't convey it but as I said with your steps I *was* able to reproduce it so I hopefully will be able to fix it for 10.1.
