### ISSUE TITLE
Teleporter hud issue 

### ISSUE THREAD

**Issue by NotaDev2** [mekanism/Mekanism#5600] opened 2019-08-05 21:04 UTC
When i link 2 teleporters my hud glitches out and is only black or grey (playing on a server btw)

Steps to reproduce:
1.Link teleporters
2.Look at your hud
3.?

newest version of everything including forge as of this date

**Comment by NotaDev2** [comment] 2019-08-05 21:07
forgot to add it is minecraft 1.12.2

**Comment by thiakil** [comment] 2019-08-15 10:04
> newest version of everything including forge as of this date

nope, try again.

**Comment by pupnewfster** [comment] 2019-08-23 19:58
Closing this as you have not provided the information we have requested. Also I believe the cause of this is likely the same as what caused #5579 because iirc the teleporter draws it in the same way that we draw our fluids. If this still happens on mekanism 9.8.1 let us know and provide the other information we have requested.

**Closed by pupnewfster** 2019-08-23 19:58 UTC
Labels: Waiting Feedback
