### ISSUE TITLE
Personal teleporter getting nullified ownership

### ISSUE THREAD

**Issue by GrandMJ** [mekanism/Mekanism#6620] opened 2020-10-14 19:47 UTC
**Issue description**:
My wife and me playing a modpack on a dedicated server.
Her personal teleporter stay functional with all frequencies as long as she doesn't relog. As soon as she does, her pers. teleporter gets ownership null.
Sneaking right click doesn't change ownership. It stays null and no frequencies are visible and/or usable.
She can enter its gui and if she crafts a new one, she'll have a correct ownership with all frequencies.

Being op'ed had no influence as I just tested it.
We're of course using the same ISP and LAN, dunno if that might be the issue here.

I did some screenshots where you can see the owner state before and after crafting a new one.
Let me know if those are from interest.

**Steps to reproduce**:
1. Being at the same house with same external ip, joining dedicated server
2. Craft personal teleporter, use it to set initial ownership
3. After relogging the ownership turns null and therefore unusable

Version :
**Forge:** 32.0.108
**Mekanism:** 10.0.9.432
**Other relevant version:** Modpack: Valhelsia 3 on its version 3.0.17

**Server and client latest logs:**
https://gist.github.com/GrandMJ/417741585e8bf47720021dfc26e5ed58

**Comment by GrandMJ** [comment] 2020-10-14 20:27
As I did some testing, she built a security desk and threw all personal teleporters in to clear the ownership.
Then she re-owned one of them and that ownership now remains after relogging and is fully usable.

**Comment by pupnewfster** [comment] 2020-10-19 18:11
I believe this most likely will be fixed by the fixes I made in https://github.com/mekanism/Mekanism/commit/6fd2c9338785b45cbbdcfb6fdef78763f3203f42 given it seems frequencies just weren't fully working properly on servers to begin with.

**Comment by CapturedCherry** [comment] 2020-10-20 07:56
I'm unable to reproduce this issues following `6fd2c93` code changes.

**Closed** 2020-10-23 22:26 UTC
Labels: 1.16, Fixed in dev
