### ISSUE TITLE
Mekanism cable networks are breaking when leaving an area and re-entering it.

### ISSUE THREAD

**Issue by RileyGuy** [mekanism/Mekanism#4676] opened 2017-09-05 04:29 UTC
# Note from dev: Please do _not_ add a 'me too' to this issue. 
If you wish to subscribe for updates, use the button in the sidebar. It is a known issue that we have not figured out. Of course it's going to affect you.

------------------------------------------------------------------------

#### Issue description:
Mekanism cable networks cease to exist when leaving an area and coming back, chunk-loaded or not.
Breaking one of the cables doesn't work as it doesn't transmit power to the adjacent cables. I have to break all of them to have a complete network again.

#### Steps to reproduce:
1. Place mekanism cables to form a cable network.
2. Leave the area they are in (at least 32 chunks away).
3. Coming back, the cables will have ceased working and the network will no longer be existent. You will have to replace all cables for it to function again.

**Forge:** 2460
**Mekanism:** 9.4.1
**Other relevant version:** 

The crashlog here is ***NOT*** relevant in any way, I'm just posting it so you can see the modlist (the mods haven't changed but they have been updated recently to their latest versions with no impact on this bug whatsoever).
https://gist.github.com/Xerasin/3a52eae8f6d920eb97510f08eeb0bb05

**Comment by thommy101** [comment] 2017-09-05 04:54
Could you please provide a log file when this is happening? It is certainly relevant as that does provide versions you're using.. Giving an old one and saying, I only updated everything after it isn't so helpful.

I'm almost certain that this issue has been fixed in the latest release.

If this does happen, could you please provide some information on the transmitter networks of the misbehaving transmitters? You can get that with the network probe.

**Comment by RileyGuy** [comment] 2017-09-05 05:57
Ah. You see, I don't actually have a log file as I don't own the server, I'll contact the owner about it. However I did scan with the network probe and when the cables are functioning normally, it reports the correct amount of energy receivers and givers. When they break though, the network probe reports that no network is formed whatsoever. I also think that this is only happening when they are connected to entangloporters, because I have cables that are receiving power through different means which are fine when the others break.

**Comment by RileyGuy** [comment] 2017-09-05 18:16
Oh by the way, just as an update this seems to happen with item pipes as well, which leads me to believe there could be more pipes that have this issue.

**Comment by thommy101** [comment] 2017-09-05 18:19
All pipes use the same logic ;) It's very related to a long lasting bug, which we tought was fixed in one of the latest releases (certainly in 1.12), apparently it's not fixed completely...

Do you have a usecase that is always reproducable? That makes debugging a lot easier.

**Comment by RileyGuy** [comment] 2017-09-05 20:41
I don't know how easy this is, but try connected up an entangloporter outputting to a bunch of universal cables connected to a whole bunch of machines and stuff. Leave the area about ~16-32 chunks out and then come back, the cables will have no green in them and will not transmit power. Some mekanism machines seem to bork half the time as well.

Log as promised, but there's literally nothing when it happens: https://gist.github.com/7349c9f62bb945af3be6edc8d4981a78

**Comment by Lunetouche** [comment] 2017-09-10 00:40
Just had this happen a second time on my server, after i went to another dimension then came back. area is completely chunkloaded. Network from gas generators to a thermal expansion energy cell was from, but from that energy cell to everything else there was no network. replacing a cable with a new one results in just that one filling up. a server restart wakes all the cables up thankfully :P https://pastebin.com/raw/AEzgp4ue was in the logs.

Version is the 9.4.0 homebaked in AlltheMods3 2.8

**Comment by thiakil** [comment] 2017-09-12 05:04
> Version is the 9.4.0 homebaked in AlltheMods3 2.8

Your version is far too out of date and probably doesn't even include the initial half of the fix to this type of problem. The latest is `9.4.1.326` for 1.12

**Comment by JaSpr** [comment] 2017-09-17 00:06
This keeps happening with me in AllTheMods 3 v3.2b for all types of cables/pipes/transports

**Comment by thiakil** [comment] 2017-09-17 02:40
and what Mekanism version does that pack include?

**Comment by JaSpr** [comment] 2017-09-17 08:17
Mekanism 9.4.1
Forge 14.22.1.2478
MC 1.12.1

**Comment by hathfury** [comment] 2017-09-23 03:26
This is happening in Modern Skyblock 2.4.4
Mekanism 9.4.1.326
Forge 14.22.1.2484
MC 1.12.1

I can confirm replacing the cables and restarting the server wakes up the cables until it happens again.

**Comment by thiakil** [comment] 2017-09-23 04:21
We do have reproduction scenarios but have as yet not had time / been unable to find the cause.

**Comment by Lunetouche** [comment] 2017-09-23 06:40
I believe it may be forge and ftbutilities fighting over chunk loading tickets causing wierd unloading of the chunks the cables are in. I havent been able to reproduce it after increasing the limits for tickets in forgeChunkloading.cfg to well beyond the number i have loaded. the default was less than that allowed to be loaded with its map system. (now using 9.4.1.326 of mekanism but still had it happen before changing that config)

**Comment by thommy101** [comment] 2017-09-23 06:42
We've got a reproducible case with only Mekanism installed, however not had enough time to narrow it down to some misbehaving piece of code.

**Comment by kulflame** [comment] 2017-10-14 05:38
This is still a bug in version 1.12.1-9.4.1.326 on ATM3 Version 4.1 or 4.2.  Simply put...  The cables stop transferring power when you leave the area.  Tested Basic and Elite Universal cables.

Also...

The Basic Pressurized cable transferring Oxygen breaks whilst the Basic Pressurized transferring Hydrogen works perfectly.  

3 players on my server all experiencing same issue.

**Comment by EliogabalusPL** [comment] 2017-10-20 12:53
Minecraft 1.12.1 in the server version, on the client also after leaving the factory and return to her pipe stupid and to fix it you have to destroy the pipes and lay them again.

**Comment by EliogabalusPL** [comment] 2017-10-20 13:04
I would like to say that the problem with pipes is not present in all devices.
I have set up 6 Smelting Factory in a row and after moving away from the device, and then after returning only a part of Smelting Factory did not ship its product. This may help to find the cause.

**Comment by henkaa** [comment] 2018-01-10 20:54
Running Minecraft 1.12.2 EOD Synthesis (it has Mekanism 1.12.2-9.4.3.330) I was able to reproduce the following steps and hope this will contribute in finding this irritating peice of bug: (I have no access to the servers log files just for the record)

1. Be in the chunk with working Mekanism cables (I use Advanced Universal cable)
2. Leave the chunk (lets say 15-20 away)
3. Come back and realize the cables stopped working.
4. Without doing anything, leave the chunk (again. lets say 15-20 away)
5. Come back and see it all working properly again.

**Comment by ProsperCraft** [comment] 2018-02-05 16:38
Could this be related?
https://gist.github.com/ProsperCraft/92c7b09dc4d4ba649367a233ffd63ba6

[ic2-poolthread-20/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityEnergyCube@ebf03d8 (dim 0: 86/59/139) removal without registration

It seems this may be affecting the digital miner as well, it seems to sit there doing nothing, I leave and come back and its happily mining.

**Comment by Darkduck83** [comment] 2018-02-22 20:15
Good Day 
This issue is happening to me with the "Enigmatica 2" mod pack - Mekanism version 9.4.3.330

**Comment by marcin212** [comment] 2018-02-23 14:36
Mekanism-1.12.2-9.4.3.330

https://i.imgur.com/0fKgS6o.png

after replace 1 cable:
https://i.imgur.com/eBYQLqp.png
https://i.imgur.com/VNv47X9.png

**Comment by predakanga** [comment] 2018-04-29 13:37
Just upgraded to 9.4.6.341 and am still experiencing this issue.

In particular, upon returning to my Mekanism area all the cable segments had a full buffer of power, but none were passing that power on to adjacent machines or cables (newly placed ones remained unpowered).

**Comment by GordonHollow** [comment] 2018-05-04 10:39
Mekanism-1.12.2-9.4.8.343 also has this issue on server

**Comment by thiakil** [comment] 2018-05-04 11:03
Can we please see pictures of the setups, or even world downloads?

**Comment by predakanga** [comment] 2018-05-04 11:54
I'm away from home for a couple of weeks so I can't provide screenshots, but here's a world download.

World download: https://file.io/p8bsB2
Modpack: SevTech Ages 3.0.6 (w/ changes)
Modlist and versions: https://gist.github.com/predakanga/d763764395f2257df0e18147d42947f1

If need be I can provide a full world save, or a copy of the full instance

**Comment by thiakil** [comment] 2018-05-04 13:27
world download is 404ing

**Comment by predakanga** [comment] 2018-05-05 00:31
Sorry about that, forgot that service is read-one-then-delete.

This dropbox link should work: https://www.dropbox.com/s/k67t1sirlxnu4oc/nw.zip?dl=0
I hate using 'temporary' file storage for github issues though, so if you have a recommendation let me know

**Comment by Boolyman** [comment] 2018-05-15 13:45
Is there an ETA on a resolution for this?  Getting a lot of reports from users on my pack that they have had to stop using Mekanism pipes all together because of this.  Which means I have to try to find another mod with compatible gas transport.

**Comment by thiakil** [comment] 2018-05-16 00:27
We don't know what's causing it, so no.

**Comment by Krapht** [comment] 2018-05-18 22:04
I'm having the same problem in sevtech 1.0.7 (mekanism 1.12.2-9.4.10.345) so I'll add my setup in case it helps finding the issue

My setup (in a broken state)
![2018-05-18_23 22 42](https://user-images.githubusercontent.com/1724361/40258833-3cfcc082-5af3-11e8-9f6a-7df54eea918c.png)

In a max size compact machine I have a 25k rft/t liquid ethylene powered Advanced generator turbine with a forge power emitter. On top of that is a fully infused RFTools Advanced powercell with the side facing the ultimate cable set to output. On the other end of the ultimate cable is an additional advanced powercell used as a power buffer to ensure power to machines. From the buffer powercell and on I used elite universal cable.
The middle section is a liquid ethylene setup. Power on the back
To the right is a 3x ore setup. Power on the back.

As soon as I leave the machine the cabling seems to stop transmitting power as I no longer get any ingots out, but the machine is still loaded because the generator is still producing power. When returning both Mekanism power sections have stopped working (the generator -> buffer ultimate cable and the buffer -> machines elite cable).

Now here is the kicker.. If I leave again, not touching anything, everything comes back to life and working properly (as far as I could tell), I can now go back and forth and everything works as expected.

Untill.... I make a change in the cable network. In my case I tested breaking an elite cable in the buffer -> machine section, between the middle and right setup. Machines on the right ran out of power, as expected. When I put the cable back, they received power again, as expected. 

Now when I leave the whole thing stops working again. I go back inside to find all cables dark, even the ones in the generator -> buffer section (the ultimate ones). Those are not even Mekanismly connected to the one I broke. Nothing is transmitting power. So I leave again, touching nothing, and things start working again. And keep working when I return to the machine.

So from what I can tell. The workaround is: Whenever you make changes in the cable network and leave, come back an extra time, but don't try to fix it. Just leave again and it recovers.

**Comment by justinrusso** [comment] 2018-05-24 01:34
Hey @thiakil, Is there anything we (the devs of SevTech) can do to aid you in finding the root cause of this?

**Comment by thiakil** [comment] 2018-05-24 01:39
Not really, we have a couple of repro situations though I haven't had time to look.

It requires sticking a debugger onto the game and trying to find what's not updating properly - the transmitter code is rather complex. Rather time consuming tbh

**Comment by GordonHollow** [comment] 2018-05-24 03:26
Looks like exist limit of mekanism-pipes in one chunk. I replace mekanism powerpipes with ThermalExpansion powerpipes(water and gas pipes stay mekanism) and this issue appears rare. More mekanism pipes in one chunk - more chanses for this issue. Maybe it's FTBUtilities and Forge strange crossissue (but i try force the limit of updates in FTBU config - it's not work)

**Comment by sb555** [comment] 2018-05-24 21:46
We had this problem on our server. We were using extra utils chunk loaders, but switching to ftbutils for chunk loading fixed the problem completely.

**Comment by Iorce** [comment] 2018-06-11 21:08
I encountered the issue as well, multiple times, always starting at a chunk border.

**Comment by callous4567** [comment] 2018-06-12 12:40
I've got the issue too: FTB Revelations pack. We added some mods, i.e. TE4 and Torcherino, but the issue was prevalent before addition.

The method for reproduction is similar to how others have stated, so, pointless to restate. 

https://drive.google.com/open?id=1y6z6yQfuCK4ludNHenRX15wb2YMgzFCh

(Server files)

**Comment by thiakil** [comment] 2018-06-15 14:22
9.4.13.349 contains some Cable network changes

**Comment by Terminatr** [comment] 2018-07-02 01:22
My experience seems to be related to this. Ultimate Energy Cube is fully functional with EnderIO conduits used for a single input and a single output. After leaving area (dimension) and returning, Energy Cube will no longer accept input but continues to output. Breaking and replacing the Energy Cube restores full functionality.

**Comment by Timmypwn** [comment] 2018-09-09 13:09
i just got the problem and it happend by routing the universal wires from a chunkloaded 3x3 base outside for a short while, then cross a chunkborder outside. when breaken the pieces that where in the chunk that wasn't always loaded(outside 3x3), and only replacing them. everything works again.

**Comment by bluelightning32** [comment] 2019-01-05 04:33
One of the players on my server complained that Mekanism cables weren't powering their IC2 machines anymore. I found the following in the server log. The coordinates point to an IC2 machine they were complaining about:
```
[13:57:03] [ic2-poolthread-3/WARN] [ic2.EnergyNet]: Tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@401e9ab9 (dim 0: 519/68/742) removal without registration
[13:57:08] [ic2-poolthread-7/WARN] [ic2.EnergyNet]: Tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@4ec6e9f3 (dim 0: 519/68/742), sub tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@4ec6e9f3 (dim 0: 519/68/742) addition is conflicting with a previous registration at the same location: EnergyNetDelegateSink{tileType=null, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=519, y=68, z=742}, blockMetadata=-1}.
[13:57:12] [ic2-poolthread-10/WARN] [ic2.EnergyNet]: Tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@4ec6e9f3 (dim 0: 519/68/742) removal without registration
[13:57:45] [ic2-poolthread-1/WARN] [ic2.EnergyNet]: Tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@7262652c (dim 0: 519/68/742), sub tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@7262652c (dim 0: 519/68/742) addition is conflicting with a previous registration at the same location: EnergyNetDelegateSink{tileType=null, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=519, y=68, z=742}, blockMetadata=-1}.
[14:16:37] [ic2-poolthread-7/WARN] [ic2.EnergyNet]: Tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@7262652c (dim 0: 519/68/742) removal without registration
[14:17:00] [ic2-poolthread-6/WARN] [ic2.EnergyNet]: Tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@cfa740d (dim 0: 519/68/742), sub tile ic2.core.block.comp.Energy$EnergyNetDelegateSink@cfa740d (dim 0: 519/68/742) addition is conflicting with a previous registration at the same location: EnergyNetDelegateSink{tileType=null, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=519, y=68, z=742}, blockMetadata=-1}.
```

The server is running Enigmatica 2 Expert v1.49. It is also running SpongeForge 1.12.2-2768-7.1.5-RC3512.

**Comment by pupnewfster** [comment] 2019-04-20 15:07
I believe this issue is fixed as of [9.7.2.373](https://minecraft.curseforge.com/projects/mekanism/files/2701541), if anyone is still experiencing this version could they please let us know.

**Closed** 2019-07-08 01:43 UTC
Labels: Waiting Feedback, bug

**Comment by OGiMGO** [comment] 2020-08-23 22:33
1.12.2 --> 9.8.3.390 I have this same problem too. Transport cable push/pull, gas cable bug when I don't be in this same place

**Comment by pupnewfster** [comment] 2020-08-23 22:38
The issue for 1.16 is not this issue, it is #6356 as it also can happen vertically now it seems not just across chunks. Last we checked it worked fine in 1.12, but either way 1.12 is out of support so if it somehow broke again I am afraid you are out of luck.
