### ISSUE TITLE
Basic Logistic Transporter becomes disconnected

### ISSUE THREAD

**Issue by mexifelio** [mekanism/Mekanism#5583] opened 2019-07-26 04:07 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Basic Logistic Transporter becomes disconnected. Items stop going through. Fixed with reconfigurater and then items begin transporting. Pipe IS on the edge of a chunk border.

#### Steps to reproduce:
1. Happens randomly.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 1.12.2-9.7.9.380
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Cl00e9ment** [comment] 2019-07-30 22:07
This bug isn't totally fixed (I've built my own version that includes the fix).

What is really fixed:
- When two transporters are on a chunk border they will no longer disconnect randomly when leaving and re-entering the area.

What is still broken:
- When a basic mechanical pipe is connected to a basic fluid tank on a chunk border, the pipe sometimes disconnect when leaving and re-entering the area. When I placed a block near it to update it, it reconnected.
- Maybe this bug affects every kind of transporters (not just the basic mechanical pipe) and every kind of machines (not just the basic fluid tank). I haven't done advanced tests.

You can find the "home baked" version here: [MekanismAll-1.12.2-9.8.0.homebaked.zip](https://github.com/mekanism/Mekanism/files/3449033/MekanismAll-1.12.2-9.8.0.homebaked.zip)

**Comment by pupnewfster** [comment] 2019-07-30 22:17
I will try to look at it some more at some point, slightly busy at the moment. I probably just forgot to add a check for if it is connected to something else (not just if it is connected to another pipe).

**Comment by pupnewfster** [comment] 2019-07-31 23:19
@Cl00e9ment I am not able to reproduce the issue when connecting to other blocks. Are you able to reliably reproduce it, and if so could you upload a world file with a setup you can reproduce it on.

**Comment by Cl00e9ment** [comment] 2019-08-01 12:39
The issue is reproducible, but it will not occur every time. I tried to leave and re-enter the area during 15 min in order to see the bug and record it: [https://www.youtube.com/watch?v=RmN_XlXAVc8](https://www.youtube.com/watch?v=RmN_XlXAVc8)

You can find the world file here: [[map] Mod Pack Industriel.zip](https://mega.nz/#!aypkCIDL!qyPjwlIK6UZSxzHUjpzckFv4cEadmaHWcxsvcDqg6PM)

The mods that I used:
- ae2stuff-0.7.0.4-mc1.12.2
- AE2WTLib-1.12.2-1.0.30
- appliedenergistics2-rv6-stable-6
- bdlib-1.14.3.12-mc1.12.2
- BetterBuildersWands-1.12.2-0.13.2.271+5997513
- BetterFoliage-MC1.12-2.2.0
- BiomesOPlenty-1.12.2-7.0.1.2439-universal
- ChestTransporter-1.12.2-2.8.8
- ChickenChunks-1.12.2-2.4.1.73-universal
- Chisel-MC1.12.2-0.2.1.35
- CodeChickenLib-1.12.2-3.2.2.353-universal
- CoFHCore-1.12.2-4.6.3.27-universal
- CoFHWorld-1.12.2-1.3.1.7-universal
- CTM-MC1.12.2-0.3.3.22
-  DrZharks MoCreatures Mod-12.0.5
- DynamicTrees-1.12.2-0.9.5
-  ExtraCells-1.12.2-2.6.2a
- FastLeafDecay-v14
- Forgelin-1.8.3
- ForgeMultipart-1.12.2-2.6.1.81-universal
- GraveStone-1.12.2-Graves-1.3.1
- Hwyla-1.8.26-B41_1.12.2
- industrialforegoing-1.12.2-1.12.13-237
- InventoryTweaks-1.63
- ironchest-1.12.2-7.0.71.846
- jei_1.12.2-4.15.0.268
- journeymap-1.12.2-5.5.4
- JustEnoughResources-1.12.2-0.9.2.60
- MekanismAll-1.12.2-9.8.0.homebaked
- ModernLights-1.0.3_1.12
- modnametooltip_1.12.2-1.10.1
- MrTJPCore-1.12.2-2.1.4.43-universal
- NotEnoughIDs-1.5.4.4
- OptiFine_1.12.2_HD_U_E3
- p455w0rdslib-1.12.2-2.2.156
- ProjectRed-1.12.2-4.9.4.120-Base
- ProjectRed-1.12.2-4.9.4.120-integration
- RedstoneFlux-1.12-2.1.0.6-universal
- tesla-core-lib-1.12.2-1.0.15
- ThermalCultivation-1.12.2-0.3.3.12-universal
- ThermalDynamics-1.12.2-2.5.5.21-universal
- ThermalExpansion-1.12.2-5.5.4.43-universal
- ThermalFoundation-1.12.2-2.6.3.27-universal
- torchmaster_1.12.2-1.7.1.74
- WirelessCraftingTerminal-1.12.2-3.12.93

You can also download the complete setup here (a MultiMC instance that contains the map, the mods and their config) : [[MultiMC instance] Mod Pack Industriel.zip](https://mega.nz/#!D750RSrZ!_IAkZ_1nRo5BbrRRpn-vYI6UkG3KHpBbk-iIVdFkbmM)

**Comment by pupnewfster** [comment] 2019-08-01 15:28
Thank you that is useful, I will continue to look into it some more so far trying to reproduce it I ran into one random crash so made a hotfix for that at least, so at least some good came of this. Though my suspicion is it may be hard to track down it not reconnecting to tanks given it does not happen every time.

**Comment by Cl00e9ment** [comment] 2019-08-01 16:48
Yeah, I just got a crash caused by a NPE from Mekanism. Here is the logs: [https://pastebin.com/rSikNFrZ](https://pastebin.com/rSikNFrZ).

**Comment by pupnewfster** [comment] 2019-08-01 16:55
Yup that *should* be fixed by https://github.com/mekanism/Mekanism/commit/f887183f1a220458f5e7586ea135b520707f20aa

**Comment by ChlorineX** [comment] 2019-08-04 08:49
I can reproduce this, after opening the world, the Logistic Transporters that are adjacent to chunk boarders disconnects randomly, sometimes items can keep passing (Image 1), but in most times they can't (Image 2). I have to break and replace it, then it works again (Image 3). 
![2019-08-04_16 40 14](https://user-images.githubusercontent.com/34786330/62421643-b573cd80-b6d7-11e9-9d68-a5be5b7920f0.png)
![2019-08-04_16 43 07](https://user-images.githubusercontent.com/34786330/62421655-df2cf480-b6d7-11e9-8b9d-c986c73b96a5.png)
![2019-08-04_16 43 34](https://user-images.githubusercontent.com/34786330/62421656-e0f6b800-b6d7-11e9-90f9-cc69686b09f8.png)

**Comment by Cl00e9ment** [comment] 2019-08-04 09:13
As pupnewfster said previously, this bug is partially fixed in the development version.

You can download this version [here](https://mega.nz/#!uzgmGCxT!4LD_l6UcAUAz49-wEZXedMw7HW-69vJbubzJIIlm6tA) but it's not an official version so use it at your own peril.

**Comment by pupnewfster** [comment] 2019-08-05 00:57
Fix included in [9.8.1](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2755008). Note: This does not fix the low reproduction rate where sometimes the cables don't reconnect to tanks etc. I honestly think that may be a bug on the tank than the transmitter.

**Comment by pupnewfster** [comment] 2020-02-09 00:34
Closing this as it was fixed quite a while ago, and in terms of the rendering breaking I have yet to see this happen in 1.15 after having rewritten the rendering code.

**Closed by pupnewfster** 2020-02-09 00:34 UTC
Labels: Fixed in dev, Waiting Feedback, bug, moderateimportance
