### ISSUE TITLE
glitched out cables/pipes/transporters

### ISSUE THREAD

**Issue by soundtechscott** [mekanism/Mekanism#6903] opened 2021-01-21 22:57 UTC
Visually all my mekanism cables/fluid/item/power transports are broken....
I can break them and place them again and it all good for a while, but eventually returns to a broken looking cable...

seems to function fine...
but it makes me not want to use this mod

![2021-01-15_16 53 35](https://user-images.githubusercontent.com/51548286/105422636-ed870d00-5bf8-11eb-88c4-b514411764d4.png)
![2021-01-21_14 54 15](https://user-images.githubusercontent.com/51548286/105422638-ee1fa380-5bf8-11eb-8e5c-8b4ecf37e6d4.png)

I'm using the most recent file I could download for 1.16.4

**Comment by pupnewfster** [comment] 2021-01-21 23:12
duplicate of #5922 short answer is remove immersive portals, the mod is not fully compatible with forge and breaks various forge systems that mekanism relies on.

**Closed by pupnewfster** 2021-01-21 23:12 UTC
