### ISSUE TITLE
Smelting Factory do not allow changes to item slots except removing existing ones

### ISSUE THREAD

**Issue by minecraftsteve** [mekanism/Mekanism#5515] opened 2019-06-09 04:11 UTC
#### Issue description:
I was playing a 1.12.2 modpack called All The Mods 3. Before its latest update the Elite Smelting Factory I have been using had its buffer totally normal. When I updated it, as long as there are items in either input or output slots, it would not allow me to insert or swap items. I saw my favourite Minecraft YouTuber using the Basic Smelting Factory in the modpack Sky Factory 4 and I think he was experiencing the same thing. Though Auto-sort can partially compensate, this should be fixed.

#### Steps to reproduce:
1. Craft any Smelting Factory
2. Put some items in any of its slots
3. Try to put another kind of item in or swap the existing ones with other.

#### Version
**Forge:** 14.23.5.2825
**Mekanism:** Mekanism-1.12.2-9.6.9.367
**Other relevant version:** 
All The Mods 3's version: v5.12.1

**Comment by thiakil** [comment] 2019-06-09 04:16
It would help if you can find/make a video that demonstrates exactly what the problem is - we recently changed things so that the slots won't accept incompatible items (e.g. so automation can't insert into a slot where the output is a different type and thus would get stuck waiting for output to empty)

**Comment by pupnewfster** [comment] 2019-06-09 04:22
I am pretty sure that bug got fixed with 9.7.0 the latest version is 9.7.7, so if you could confirm it still happens with that then we can look into it more.

**Comment by minecraftsteve** [comment] 2019-06-09 09:38
This is indeed fixed in newer versions, so I guess I will wait for the modpack creators to update it. I'm not someone who updates mods in a modpack separately. :P

**Comment by pupnewfster** [comment] 2019-06-09 12:44
Going to go ahead and close this issue for now then.

**Closed by pupnewfster** 2019-06-09 12:44 UTC
Labels: Waiting Feedback
