### ISSUE TITLE
Bin duplications

### ISSUE THREAD

**Issue by OutcastZeroOne** [mekanism/Mekanism#4911] opened 2018-01-16 21:39 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Place empty bin into Tinkers Construct crafting station with item to store in bin
2. grabbing bin with stored item from crafting completion slot produces bin with stored items and leaves an empty bin in crafting grid. works with all tiers of bins.

#### Version (make sure you are on the latest version before reporting):
**Forge:** Forge 14.23.1.2555
**Mekanism:** Mekanism-1.12.2-9.4.3.330
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment] 2019-07-17 16:37
Closing as I can't reproduce it with the latest version (or the version specified.) Might have been a bug in an older version of tinkers, unable to confirm if that was the issue as no tinkers version was listed.

**Closed by pupnewfster** 2019-07-17 16:37 UTC
Labels: Not reproducible
