### ISSUE TITLE
[1.15.2] Server crashes.

### ISSUE THREAD

**Issue by Quu1337** [mekanism/Mekanism#6021] opened 2020-04-03 09:35 UTC
#### Issue description:
java.lang.ArithmeticException: Division by zero
Sometimes it crashes on load, usually i crashes when someone goes into base that has lots of machines.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.30
**Mekanism:** 9.9.17

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/XNGYyBPy
https://pastebin.com/ydHrR4FD
https://pastebin.com/uPuwPsXx
https://pastebin.com/x6d8s1Ux

**Comment by Yoosk** [comment] 2020-04-03 09:39
Duplicate of https://github.com/mekanism/Mekanism/issues/6010

**Closed** 2020-04-03 09:40 UTC
