### ISSUE TITLE
[1.15.2]Resistive Heater crash

### ISSUE THREAD

**Issue by EnterFor** [mekanism/Mekanism#6000] opened 2020-03-28 11:57 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I opened the Resistive Heater temperature adjustment
The client crashes and the server is intact

#### Version (make sure you are on the latest version before reporting):
**Forge:*31.1.27* 
**Mekanism:*9.9.17.409* 
**Other relevant version:** 

[crash-2020-03-28_19.39.14-client.txt](https://github.com/mekanism/Mekanism/files/4397065/crash-2020-03-28_19.39.14-client.txt)

**Comment by thiakil** [comment] 2020-03-28 12:02
duplicate of #5996

**Closed by thiakil** 2020-03-28 12:02 UTC
