### ISSUE TITLE
Pipez mod cannot transfer all of the energy from an Advanced Solar Generator

### ISSUE THREAD

**Issue by jarquafelmu** [mekanism/Mekanism#7567] opened 2022-08-05 16:39 UTC
### Issue description

Just opened an issue on their end, so this is the reference to it. [132](https://github.com/henkelmax/pipez/issues/132). 

Could this energy problem be related to https://github.com/mekanism/Mekanism/issues/7096#issuecomment-817314608

### Steps to reproduce

1. Place down an Advanced Solar Generator, Ultimate Energy Cube, and link them with an Energy Cable set to output on the generator.
2. Add an ultimate upgrade to the output side of the energy pipe.
3. Observe that even though power is being transferred to the Energy Cube, the transfer speed is not sufficient to consume all of what is being produced by the generator; which means that the generator is producing more than what the pipe can handle.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.68

### Mekanism version

Older

### Other relevant versions

I have tested this in world with just pipez and mekansim and the issue persists.

**Comment by pupnewfster** [comment] 2022-08-05 16:54
Out of curiosity/for confirmation, does putting the energy cube directly against the solar generator (or connecting it with universal cables) work properly? Granted that doesn't prove much beyond the fact that there isn't some issue in say the rate the energy cube can accept power as it won't convert to FE first and then back, but presuming it does work properly (which I suspect it does as this is our first report), I would try using [LaserIO](https://www.curseforge.com/minecraft/mc-mods/laserio) or [XNet](https://www.curseforge.com/minecraft/mc-mods/xnet) and see if it also happens there. Mostly just suggesting trying with one of those mods as they are the first ones that came to mind that use the ForgeEnergy Api to transfer power, so if it doesn't happen with them, it makes it more likely that the issue is on pipez's end than on our implementation of the forge energy api.

**Comment by jarquafelmu** [comment] 2022-08-05 17:15
Thanks, I will give those a shot

**Comment by jarquafelmu** [comment] 2022-08-05 18:52
An energy cube right next to the generator works as expected.

I was not able to get LaserIO to work, but I did get XNet to work. Even with XNet set to extract it's maximum of 10,000 RF/t it wasn't able to keep up with the 120 RF/t generation of the Advanced Solar Generator and the generator filled up.

![image](https://user-images.githubusercontent.com/5807272/183142528-27a3cb9a-749e-4a5e-a53a-db6079502872.png)
![image](https://user-images.githubusercontent.com/5807272/183142560-b7624e14-dc75-46b7-aac6-ed3075b06f86.png)
![image](https://user-images.githubusercontent.com/5807272/183142570-2da5a219-6d76-4cb9-b77d-8292de661234.png)
![image](https://user-images.githubusercontent.com/5807272/183142593-84cc7271-9184-44c5-a378-0f0598b409e1.png)

So, it might be in the conversion process of Joules -> FE

**Comment by pupnewfster** [comment] 2022-08-06 16:41
I need to look into it in a bit more depth to confirm, but I think the issue here might only be minorly related to the Joules to FE in that after looking at it a little I believe that the advanced solar generator either is generating more power than it should or the output limit it has is lower than it should be. Which then because the output limit is the same as the production when it converts from joules to FE it can't do so in whole numbers so it increases by a tiny bit each tick. And it can't make up for it in the next tick as the output buffer won't let it output the extra amount as it is already at capacity.

For 10.3.2 (MC 1.19.1/2 as 1.18 is EOL) I will try to improve the max output rate of the advanced solar generator and see if any other generators need it adjusted as well, so that the tiny amount of excess energy doesn't just build up.

**Comment by jarquafelmu** [comment] 2022-08-06 18:18
I was noticing that as well that the generators were supposed to do up to 240 rf/t output but were only doing what they were generating

**Comment by pupnewfster** [comment] 2022-08-06 18:25
Well should be fixed for 10.3.2, and you can definitely go and close the issue you opened on pipez's end as it was due to a bug in the generator's max output number and nothing to do with their mod.

**Closed** 2022-08-06 23:52 UTC
Labels: confirmed, Mekanism, interaction, Fixed in dev, Old MC, 1.18, 1.19

**Comment by jarquafelmu** [comment] 2022-08-07 00:59
Thanks for your quick fix! I know that 1.18.2 is no longer in development, but could this fix be backported, please?

**Comment by pupnewfster** [comment] 2022-08-07 01:27
Sorry but it is not planned a waste of < 2 FE per tick is inconsequential especially given if you really care you could put an energy cube or universal cable just outside the generator as a buffer that won't have the limit issue. Or you could change configs to rebalance all joules thing to shift them and make joules and FE be 1:1
