### ISSUE TITLE
Jetpack Glide Mode

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6318] opened 2020-07-13 15:39 UTC
This would basically add a fourth mode to the jet-pack called glide.

*regular
*hover
*glide
*disabled

Glide mode would basically work in a similar fashion to elytra in vanilla except in having the propulsion being powered by fireworks, it would be powered by the jetpack's rocket. This new mode would allow for extremely fast air travel at the cost of high hydrogen usage. It would be fun to just fly through the sky like a plane.

**Comment by term2112** [comment] 2020-07-13 15:39
I already wrote this but don't know what happened to the last one.

**Comment by pupnewfster** [comment] 2020-07-13 15:39
This seems to be a duplicate of your request that I moved to the feature requests tracker https://github.com/mekanism/Mekanism-Feature-Requests/issues/55 so I am going ahead and closing this

**Comment by term2112** [comment] 2020-07-13 15:40
Sorry about that, I didnt know what happened to this

**Closed by pupnewfster** 2020-07-13 15:39 UTC
Labels: enhancement
