### ISSUE TITLE
Advanced Energized Smelting Factory dupe glitch

### ISSUE THREAD

**Issue by TrevorFawcett** [mekanism/Mekanism#5981] opened 2020-03-21 07:55 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Advanced Smelting Factory output was outputting items pretty much infinitely, much faster than hopper, Basic Logistical Transporter was able to move into a chest and the amount inside the machine were not updating correctly.

#### Steps to reproduce:
1. Items were being inputted by an Advanced Enriching Factory
2. Have settings on Smelter set to Auto Sort 
3. Output into hopper, pipe or pull items out manually. 
4. I fixed the issue by breaking the Smelter and moving it and taking out all the items waiting to be smelted, then put a regular smelter in its place with no issues. 

#### Version (make sure you are on the latest version before reporting):
**Forge:31.1.18** 
**Mekanism:9,9.16.408** 
**Other relevant version:**

**Comment by stiggy1001** [comment] 2020-03-21 19:17
We also experienced this issue
To reproduce for us, attach pipe, hopper or whatever to the BOTTOM
Attaching to any other side is no issue
Then enable auto eject after setting up config

**Comment by pagameba** [comment] 2020-03-24 12:08
I also just experienced this in the TNP Limitless 2 Mod Pack version 1.06 with

- Mekanism-1.15.2-9.9.16.408.jar
- MekanismAdditions-1.15.2-9.9.16.408.jar
- MekanismGenerators-1.15.12-9.9.15.408.jar
- MekanismTools-1.15.2.9.9.16.408.jar

Smelting Factory output to barrel directly or via cable dupes any items in output slot without clearing output slot.  Subjectively, it seems to output whatever is in the output slot every tick so the more you have, the faster it dupes.

**Comment by pagameba** [comment] 2020-03-24 12:31
I just did a few tests, it seems only to affect the advanced smelting factory, the other tiers seemed okay and also other machines at the advanced level, if that helps at all.

**Comment by pupnewfster** [comment] 2020-03-24 16:36
I believe what is/was happening is was a side effect of a change I made that was broken, and caused our capabilities to too strongly cache if they can be inserted from or not. So I think this will be fixed next alpha due to this commit: https://github.com/mekanism/Mekanism/commit/e7e21e7c46578dafddd5ad018e4a9c25714418b9

**Comment by pupnewfster** [comment] 2020-03-26 19:42
Fixed released (9.9.17)

**Closed by pupnewfster** 2020-03-26 19:42 UTC
Labels: 1.15, Fixed in dev, Not reproducible, bug, moderateimportance
