### ISSUE TITLE
Balloon Crash - Prevents World Load

### ISSUE THREAD

**Issue by mk0003** [mekanism/Mekanism#6600] opened 2020-10-08 15:34 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When you spawn any balloon it crashes game.

#### Steps to reproduce:
1. Spawn balloon (Right Click)
2. Game crashed and you cannot load the save.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
34.1.12
**Mekanism:** 
1.16.3-10.0.10.434
**Other relevant version:** 
MekanismAdditions-1.16.3-10.0.10.434

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/mk0003/8d442cdc16a44f42bc3cc7d285de716b

**Comment by ToMe25** [comment] 2020-10-08 15:57
This is fixed in dev, meaning it will be fixed in the next build(10.0.11).
While i could reproduce this in 10.0.10, i can't reproduce it with the latest commit.

**Comment by pupnewfster** [comment] 2020-10-08 16:00
Seems that the cause is the same as that caused #6599 and I will try to release an update with that fix sometime later today

**Closed** 2020-10-08 21:33 UTC
Labels: 1.16, Fixed in dev, bug
