### ISSUE TITLE
Using Eventide Amulet from ProjectE in the Rotary Condensentrator can cause crash 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [mekanism/Mekanism#7781] opened 2023-04-29 16:32 UTC
### Issue description

When using the Eventide Amulet in Rotary Condenstrator and you toggle the mode while the Amulet is still inside the game crashes

### Steps to reproduce

1. Toogle Condenstrator to Decondensentrating
2. Put in Eventide Amulet from ProjectE
3. Toggle Operation back to Condesnsetaring
4. Game Crashes

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.1

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pste.ch/gogehofira.hs

**Comment by pupnewfster** [comment] 2023-04-29 16:57
Duplicate of #7664

**Closed by pupnewfster** 2023-04-29 16:57 UTC
