### ISSUE TITLE
XP Glitch

### ISSUE THREAD

**Issue by Sunekaer** [mekanism/Mekanism#7660] opened 2022-11-09 18:51 UTC
### Issue description

When you use a cardboard box to move a furnace that has XP stored inside it when you unpack and re-pack it spits out the XP again. You can do this infinitely to get unlimited XP.

### Steps to reproduce

    Put items in smelter to smelt.
    Take Cardboard Box and packge the smelter. (Drops XP)
    Place Cardboard Box and unpackage.
    Re-Package Smelter with cardboard box. (Drops XP)
    Rinse and Repeate Steps 3 and 4

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.84

### Mekanism version

Older

### Other relevant versions

Mekanism-1.18.2-10.2.5.465.jar

**Comment by pupnewfster** [comment] 2022-11-09 19:20
Duplicate of #7600

**Closed by pupnewfster** 2022-11-09 19:20 UTC
