### ISSUE TITLE
[1.15.2]The texture of the pipe is gone

### ISSUE THREAD

**Issue by EnterFor** [mekanism/Mekanism#5963] opened 2020-03-13 08:09 UTC
* both Please use the search functionality before reporting an issue. Also take a look at the closed issues! *

Issue description:
The texture of the pipe disappears

Steps to reproduce:
1. Start the game
2.Check the pipes

Make sure you are on the latest Version before reporting:
* * Forge: 31.1.18
**Mekanism:Mekanism-1.15.2-9.9.15.407.jar (the other two are also 407)
* * Other relevant version: 1.15.2

If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
The latest logs:
[latest.log](https://github.com/mekanism/Mekanism/files/4328482/latest.log)
![image](https://user-images.githubusercontent.com/10114685/76602088-3421ca80-6545-11ea-91aa-cdaf8c18c608.png)

**Comment by EnterFor** [comment] 2020-03-13 08:14
I thought it was a computer problem, but when I restarted it a few times, it still happened

**Comment by pupnewfster** [comment] 2020-03-13 13:47
Can you please provide your debug.log file. I have been unable to reproduce this issue myself, but added a debug message at some point to try and track down the race condition that is occurring. If you don't have a debug log then next version I may just bump the level the logging happens at so that it shows in the latest log

**Comment by EnterFor** [comment] 2020-03-13 13:53
I asked another person to test it, and he didn't have the problem, which was weird.
The client is completely consistent...
[debug.log](https://github.com/mekanism/Mekanism/files/4329915/debug.log)

**Comment by EnterFor** [comment] 2020-03-13 14:09
> 您能否提供您的debug.log文件。我一直无法自己重现此问题，但在某个时候添加了一条调试消息，以尝试跟踪正在发生的竞争状况。如果您没有调试日志，则下一版本我可能会提高日志记录的级别，以便在最新日志中显示

I got two more people to test it
The result: one is normal, one is wrong
A little bit of randomness

**Comment by pupnewfster** [comment] 2020-03-15 00:36
Should be fixed in 9.9.16 which is now up and on curseforge.

**Closed by pupnewfster** 2020-03-15 00:36 UTC
Labels: 1.15, Fixed in dev, aesthetic, bug, interaction
