### ISSUE TITLE
[1.12.2] Chunk unload dupe

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#5919] opened 2020-03-01 20:59 UTC
Sorry to ignore the issue template, but all the information is available at the link below.

https://github.com/SpongePowered/SpongeForge/issues/3094

**Comment by pupnewfster** [comment] 2020-03-01 21:09
Not quite sure why this got opened given in your issue you linked you said it is not a problem of mekanism as it can be repeated with pipes from buildcraft, but either way I am closing this as we are not working on 1.12 anymore and have fixed a few bugs as well as rewritten some of the logic around how items are actually handled in transporters in 1.15.

**Closed by pupnewfster** 2020-03-01 21:09 UTC
Labels: Not Mekanism, Old MC, Sponge

**Comment by bigenergy** [comment] 2020-03-16 13:34
@pupnewfster This is a mecanism problem, just load the server to 30-50 ms..
I noticed the reason:
When I return to the shipped chunk - the pipes do not have time to connect to each other so quickly and the items transported by the pipes do not have time to understand that the pipe connection was not successful, since the delay on the server was 45-50ms

thereby, items fall from the pipe to the ground and remain in the pipe (this is a duplicate of any items)

I understand that you do not want to support the old code, mecanism works fine, in addition to these errors.
Please correct this as you find the time, a lot of players are still using 1.12.2.

**Comment by pupnewfster** [comment] 2020-03-16 14:06
I do actually agree this *was* a mekanism issue given since closing it we stumbled across the cause and fixed this in 1.15 https://github.com/mekanism/Mekanism/commit/4755d0a2847a2d1bec45dca8d9c2096a91e01eb2

**Comment by bigenergy** [comment] 2020-03-16 14:14
If this is such an easy fix, I think it won't be difficult for you to implement it in 1.12.2?

**Comment by aidancbrady** [comment] 2020-03-16 18:41
Unfortunately it’s not as easy as quickly implementing the fix. We’d need to reconfigure our build/distribution system and back port the changes to our old frameworks which is relatively time consuming- we’d rather spend these hours perfecting the 1.15 branch. Moving forward we will be closing all issues relating to old MC distributions.
