### ISSUE TITLE
Industrial Turbine Crash 

### ISSUE THREAD

**Issue by fiieryx** [mekanism/Mekanism#5499] opened 2019-06-01 17:13 UTC
I was finishing my turbine, and when i put the last block to finish the multi-block structure... my game crashed, and now i simply can't load my world

Minecraft 1.12.2
Forge: 14.23.5.2838
Mekanism: 9.7.5.376 for 1.12.2

Crash report:
https://pastebin.com/pUp1zF1t

**Comment by sromi** [comment] 2019-06-01 19:07
The exact same thing just happened to me.

Minecraft 1.12.2
Forge: 14.23.5.2838
Mekanism: 9.7.5.376 for 1.12.2

Crash report:
https://pastebin.com/M1et0ike

**Comment by skuIIs** [comment] 2019-06-01 22:57
Minecraft 1.12.2
Forge: 14.23.5.2838
Mekanism: 9.7.5.376 for 1.12.2

[https://pastebin.com/LJUwWtdF](https://pastebin.com/LJUwWtdF)

**Comment by skuIIs** [comment] 2019-06-01 23:07
Duplicate of #5485. Please close.

**Closed** 2019-06-02 00:08 UTC
