### ISSUE TITLE
Make items from radioactive components give radiation dose when in inventory.

### ISSUE THREAD

**Issue by halvors** [mekanism/Mekanism#6490] opened 2020-08-20 07:31 UTC
**Describe the the feature you'd like**
Make items from radioactive components give radiation dose when in inventory. So that you need to have a Hazmat Suit in order to handle those components, this would make it little more effort and dangerous to make end game stuff like the Meka-Tool and Meka-Suit.

The item could simply add a given dose to the player using the existing radiation system, and maybe add an item description saying how radioactive the item is, just like with radioactive gases.

If accepted should this be implemented as a Item capability? I might start writing a PR for this, just want to check if this is something that could be accepted first.

**Comment by pupnewfster** [comment] 2020-08-20 12:32
Duplicate of https://github.com/mekanism/Mekanism-Feature-Requests/issues/95 and we currently have no plans to have items give off radiation

**Closed by pupnewfster** 2020-08-20 12:32 UTC
Labels: enhancement

**Comment by halvors** [comment] 2020-08-20 13:56
Oh, sorry. I couldn't find it when filtering for closed requests, thought maybe the other one hadn't be posted after all, so i apologize :)
