### ISSUE TITLE
Formulaic Assemblicator not handling water buckets in concrete recipe from ImmersiveEngineering

### ISSUE THREAD

**Issue by delucain** [mekanism/Mekanism#7004] opened 2021-02-17 16:26 UTC
#### Issue description:
While trying to create the `concrete` block from `Immersive Engineering` in a `Formulaic Assemblicator` , the `Water Bucket` in the recipe will not import from a `QIO Exporter` or a `Logistical Transporter`. 

#### Steps to reproduce:
1. Create a `Formulaic Assemblicator`.
2. Fill the Crafting Block area in it with the recipe for `Immersive Engineering` `Concrete`. (Picture to be included.)
3. Add a `Crafting Formula`.
4. Save the Formula.
5. Connect a `QIO Exporter` or `Chest` and `Logistical Transporter` with Item Stack Filtering set to the ingredients for `Concrete` (`Sand`, `Gravel`, `Clay Ball`, and `Water Bucket`.)
6. Configure the input sides of the `Formulaic Assemblicator`.
7. The `Sand`, `Gravel`, and `Clay Ball`s will be imported into the `Formulaic Assemblicator`, but the `Water Bucket` will not.

This behavior is in a creative local test instance. On our hosted server, this crashes the server any time the chunk is loaded. I apologize, but I do not have the crash log for that, as I'm not an admin on our server.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.36
**Mekanism:** 1.16.4-10.18.446
**ImmersiveEngineering:** : 1.16.4-4.1.2-129

![image](https://user-images.githubusercontent.com/1514696/108234543-e3cac980-7112-11eb-99a9-9af5fe1a32f0.png)

![image](https://user-images.githubusercontent.com/1514696/108234582-ee855e80-7112-11eb-81a1-764538cda85b.png)

**Comment by delucain** [comment] 2021-02-17 16:43
Switch the `Chest` out for a `Basic Bin` makes this work.

**Comment by delucain** [comment] 2021-02-17 16:56
It appears that a `QIO Exporter` directly _does_ work, and I am mistaken on that count. However, there seems to be a weird issue with the recipe not matching up, and with Stock Control on, it may not be accepting them from the `QIO Exporter` in that instance.

**Comment by pupnewfster** [comment] 2021-07-09 15:02
I did some changes/cleanup to the formulaic assemblicator in https://github.com/mekanism/Mekanism/commit/9fe5371acaf21f6eeb95bbe318e3e358fe4d4913 and I am not able to reproduce this so I am going to mark it as fixed in dev, but I didn't bother to try and use the 10.0.21 release version to see if I could reproduce it in that.

**Closed** 2021-12-22 19:42 UTC
Labels: needs review, Fixed in dev, Not reproducible, 1.16
