### ISSUE TITLE
[1.16.4] Fluid tank got void in liquid crafting

### ISSUE THREAD

**Issue by frank89722** [mekanism/Mekanism#6780] opened 2020-12-13 15:12 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Tank got void in liquid crafting like immersive engineering Treated wood planks
![image](https://user-images.githubusercontent.com/10683361/102015578-72c80800-3d97-11eb-8129-f1d8dd3974bd.png)
![image](https://user-images.githubusercontent.com/10683361/102015614-a30fa680-3d97-11eb-980c-e697f7c2329b.png)

I have tested with the tank from pneumatic craft and it works fine so I reported here.
If need more information please let me know, thank's for developing this awesome mod!

#### Steps to reproduce:
1. Fill the fluid tank with some fluid needed for crafting
2. Put it in a crafting table and craft the item
3. Fluid tank disappeared 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.11
**Mekanism:** 1.16.4-10.0.18.445
**Other relevant version:** immersive engineering 1.16.4-4.1.1-128

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment] 2020-12-13 15:21
Duplicate of #6710 this is on immersive engineering's end. And I believe they have fixed it given https://github.com/BluSunrize/ImmersiveEngineering/issues/4449 is now closed, though I am not positive if a new version of IE is out yet that includes the fix or not.

**Closed by pupnewfster** 2020-12-13 15:21 UTC

**Comment by NillerMedDild** [comment] 2020-12-18 22:39
The new version of IE is now out. Non-infinite Mekanism tanks can no longer be used for batch crafting IE items.

**Comment by pupnewfster** [comment] 2020-12-18 23:04
> The new version of IE is now out. Non-infinite Mekanism tanks can no longer be used for batch crafting IE items.

Not sure what the point of this comment is given the crafting IE item stuff is entirely on their end, our tanks implement `IFluidHandlerItem` so my best guess is that their recipe then doesn't think the items have fluid in them or enough. Did you test with an elite/ultimate tank? As I would not be surprised if their recipes now properly respect the fact that our basic and advanced tanks by default have a rate limit of less than a bucket and thus don't craft.

**Comment by NillerMedDild** [comment] 2020-12-18 23:09
It was just meant as info :)

You are correct! Basic and Advanced do not work, everything above does work.

**Comment by pupnewfster** [comment] 2020-12-18 23:12
Ok, wasn't sure if it was just meant as a "this is broken" type of thing, and basic/advanced probably will end up working once aidan has a chance to review tank capacities (#6473) given we are likely to up the default configs for the various limits.
