### ISSUE TITLE
Log spam regarding transmitter

### ISSUE THREAD

**Issue by Naxanria** [mekanism/Mekanism#6192] opened 2020-05-28 08:06 UTC
**Forge:** 31.1.87
**Mekanism:** 9.10.5

See https://github.com/FTBTeam/FTB-Omnia/issues/103

**Comment by AngelicBeatz** [comment] 2020-05-30 14:33
what am I missing? I wasn't aware this was also linked over here.

**Comment by Ki-Tan2934** [comment] 2020-06-15 16:21
I also have this problem force loading all chunks with mekanism fixes the spam

**Comment by pupnewfster** [comment] 2020-06-15 16:51
We have yet to have some way to reproduce this issue, and my best guess for how it may be occurring is if some other mod is doing something improper and "ghost loading" chunks causing them to go back and forth between being loaded and unloaded, and thus causing transmitters to be added multiple times in the same tick. Or potentially even across multiple ticks if a mod like performant is installed which adds a "feature" of breaking the fact that a tick event is fired every tick; luckily that feature is configurable and if you do have performant installed you could try disabling the "event load balancing" and see if it causes the warning to go away. One thing to note though if this does make it go away, that doesn't mean a mod isn't "ghost loading"/"flickering" chunks (and causing bad performance), that just would mean that the transmitters are printing messages to the log as a side effect of the chunk loading, unloading and loading again within "one tick" as far as they are aware.

**Comment by Ki-Tan2934** [comment] 2020-06-15 19:14
FTB chunk loading problems happen when the pipes run out of power

**Comment by pupnewfster** [comment] 2020-07-07 19:00
Going to go ahead for now and mark this as "Fixed in Dev" even though I don't believe it actually is an issue on Mekanism's end and is caused by some other mod making chunks thrash. I rewrote/refactored a good portion of our transmitter logic for V10 (1.16), which hopefully will also make it so if mods make chunks load/unload rapidly it causes less of an issue to the transmitter networks.

**Comment by Ki-Tan2934** [comment] 2020-07-07 20:26
Editing the performant setting did fix the problem

**Closed** 2020-07-10 20:31 UTC
Labels: 1.15, Fixed in dev, Format not followed, Not reproducible, interaction
