### ISSUE TITLE
[1.15.2] Logistical transporter does not insert items into Storage Drawer

### ISSUE THREAD

**Issue by LuciusV** [mekanism/Mekanism#6197] opened 2020-05-30 01:10 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am producing ethylene from water, hydrogene and biofuel and PRC does not eject substrate from below.

#### Steps to reproduce:
1. Direct energy, water, hydrogen and biofuel into PRC.
2. Connect logistical transporter pipe from below, set to pull and direct into storage drawer
3. In PRC config set bottom side items output blue 
4. Substrate does not ejects, eventually blocking PRC production when it full :(

It works with vanilla chest placed instead of storage drawer 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.0
**Mekanism:** 9.10.6.419
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment] 2020-05-30 01:24
Duplicate of #5957

**Closed by pupnewfster** 2020-05-30 01:24 UTC
Labels: 1.15, Not Mekanism, duplicate
