### ISSUE TITLE
cant retro gen osm ores in pregened worlds

### ISSUE THREAD

**Issue by resinate** [mekanism/Mekanism#5778] opened 2020-01-16 18:10 UTC
not possible to spawn ore in pre-gened world in 1.15.1 version of the mod. would be nice to have it appear, a buddy saw it was commented out in source.

**Comment by pupnewfster** [comment] 2020-01-16 18:45
I don't believe it is commented out, but you also have told us next to nothing about what version the issue is with. As there are *multiple* 1.15.1 versions of Mekanism as we have been releasing updates relatively frequently. One of the updates, don't remember which one, did fix some issues with world generation configs not being respected, so unless you actually tell us which version number you have an issue with/where you think the code is commented out there is not much we can do to help you.

**Comment by resinate** [comment] 2020-01-16 22:25
version: Mekanism-1.15.1-9.9.2.393.jar
in configs i did this:
	#Allows chunks to retrogen Mekanism ore blocks.
	enableRegeneration = true
	#Change this value to cause Mekanism to regen its ore in all loaded chunks.
	#Range: > 0
	userWorldGenVersion = 1

but still didnt find any ores spawning, also how does retro gen actually work? does it replace remaining stone to ores in ur mod?

**Comment by pupnewfster** [comment] 2020-01-16 22:38
Thank you for the extra information, also I did find out where the code is commented out, so you were right initially that retro gen is disabled.

**Comment by resinate** [comment] 2020-01-17 14:05
sweet cant wait for the fix so we can play the mod, i run a SMP modded earth server, so i rely on the retro gen aspect.

**Comment by pupnewfster** [comment] 2020-01-17 15:46
I mean if you read the commit message, I only partially fixed it. It still doesn't actually work yet, may or may not finish fixing it before 9.9.3.

**Comment by pupnewfster** [comment] 2020-01-24 16:17
I believe in 9.9.5 the code on our end will *theoretically* work for retrogen, except do note no retrogen *will* happen due to the event we are listening to not firing. (https://github.com/MinecraftForge/MinecraftForge/issues/6471)

Though I would be careful once the event does get fixed about having the retrogen enabled on a world you care about before testing it on another world to make sure there is not some major issue I did not discover due to not being able to test the re-implementation.

**Comment by pupnewfster** [comment] 2020-01-30 16:38
In newer versions of forge the event not firing is fixed, but I would be cautious of turning retro-gen on because I just tested and it does appear to cause a crash. (Which I will now work on fixing due to the fact that I can actually test it)

**Comment by pupnewfster** [comment] 2020-02-01 19:31
Closing this as 9.9.8 is now released and on curseforge.

**Closed by pupnewfster** 2020-02-01 19:31 UTC
Labels: 1.15, Fixed in dev, bug
