### ISSUE TITLE
Reset Electric Pump calculation

### ISSUE THREAD

**Issue by gogoetom** [mekanism/Mekanism#6957] opened 2021-02-03 22:07 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
don't know know how to solve this problem

#### Steps to reproduce:
1.use eltric pump
2.oil
3. won't pump

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 1.5?

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment] 2021-02-03 22:13
No idea what the issue is due to the lack of information you have provided but if you want to reset which blocks it has marked as already having picked up I believe breaking and placing the pump will reset said calculation. In terms of it pumping it should work on any fluid as long as you place it over a source block and provide it energy.

**Comment by tyler489** [comment] 2021-02-03 22:53
I would assume from the info provided this is a duplicate of https://github.com/mekanism/Mekanism/issues/6907

**Closed** 2021-02-09 04:54 UTC
Labels: Format not followed, Waiting Feedback
