### ISSUE TITLE
Energy Transfer Bug - Machines & Energy Cubes Randomly Disconnect From Universal Cables

### ISSUE THREAD

**Issue by TheGameAce** [mekanism/Mekanism#7304] opened 2021-09-04 20:51 UTC
### Issue description

A similar issue is pinned and was reported over a year ago. However, I felt this issue was different enough and far enough apart to warrant its own submission. I have a feeling these two issues are very likely connected in some capacity. (Additional searching has also yielded another result from an issue posted in 2017 that's the most similar to this that I've seen. Referencing that case and the fix the was apparently applied, may be of some help here.)

To put it simply, energy cubes and machines seem to 'disconnect' from cables at random (the physical connection doesn't appear to cut off, however). This seems to only occur when the chunk(s) is/are unloaded and then loaded in again. I've found this to occur both by way of saving and quitting the world and then rejoining, as well as simply unloading the chunk by venturing far enough away and then returning. This seems to have the ability to affect a number of machines or energy cubes at once, and the problem seems to only be fixed by breaking said machine/cube, and then placing it down again.

Also of note is that this does seem to affect energy-accepting blocks/machines/etc from other mods as well that use the cables. (For example, the Energy Acceptor from AE2, requiring it to be broken and placed again.)

If requested, I have additional observations that may or may not be of benefit. (Misc details in other words.)
My presumption based on current observations so far, however, is that this is an issue specifically with the Universal Cables.

Edit: After some additional tinkering, I've discovered that changing an energy cube's configuration to use Input/Output on a side connecting with a cable, that it starts to accept energy again. Not sure if this would be of help.

### Steps to reproduce

There's no guaranteed steps to reproduce this, as it seems to be somewhat random. However, the following is the best determinable way to (potentially) reproduce the issue.

1) Place down a system of cables, energy cubes, and machines. Provide a power source.
2) Once things are powered up, go far enough away to unload the chunk(s). (Alternatively save + quit.)
3) Once certain that the chunk(s) is/are unloaded, return.
4) Run the machines. If any start losing power from their reserves despite the network being powered, you've reproduced the issue!
5) If the machines did not start losing power as described above, repeat steps 2 - 4.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

**Comment by MizozPL** [comment] 2021-09-12 21:29
I believed it's the same issue as the pinned one. Did a lot of testing int the last 3 days.

**Comment by pupnewfster** [comment] 2021-10-19 19:48
After looking into the likely cause of #6356 thanks to Mizoz's help I do believe that this issue and the other one are caused by the same thing so I am going to go ahead and close this for now. (I will comment a bit later on #6356 with a somewhat general update to the issue)

**Closed by pupnewfster** 2021-10-19 19:48 UTC
Labels: needs review, 1.16
