### ISSUE TITLE
Oredictotionificator Crash

### ISSUE THREAD

**Issue by flareblitz21** [mekanism/Mekanism#5623] opened 2019-08-23 00:57 UTC
#### Issue description:
Minecraft crashes when opening the Oredictotionificator and choosing the option "New Filter"

#### Steps to reproduce:
1.Open Oredictotionificator
2. Click New Filter
3. Wait for game to crash
4. Profit?

#### Version:
Forge: Forge-14.23.5.28.38
Mekanism: Mekanism-1.12.2-9.8.0.381
**Other relevant information:**
Was on the modpack [All the Mods 3](https://www.curseforge.com/minecraft/modpacks/all-the-mods-3)
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[Crash Report](https://pastebin.com/fLTRyGB8)
[Game Output](https://pastebin.com/AbwexuNx)

**Comment by pupnewfster** [comment] 2019-08-23 01:05
Duplicate of #5597 Update mekanism.

**Closed by pupnewfster** 2019-08-23 01:05 UTC

**Comment by flareblitz21** [comment] 2019-08-23 10:53
Mekanism is up to date on the latest release...
9.8.0.381

**Comment by pupnewfster** [comment] 2019-08-23 14:41
Wrong. 9.8.1 was released on August 4th https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2755008
