### ISSUE TITLE
Crash when rendering QIO Drive Array

### ISSUE THREAD

**Issue by ToMe25** [mekanism/Mekanism#6599] opened 2020-10-08 10:00 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When rendering a QIO Drive Array with atleast one Drive in it the game will crash.

#### Steps to reproduce:
1. Create a new Creative Mod World
2. Place Down a QIO Drive Array
3. Put a QIO Drive in it
4. Wait a few seconds and see mc crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.12
**Mekanism:** 10.0.10
**Other relevant version:** N/A

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/ToMe25/aa055e3c4034e7a4adea4d40c1b83ce3
Note that this gist contains both the debug.log and the latest.log

**Comment by pupnewfster** [comment] 2020-10-08 12:34
While this technically is a duplicate of #6336 I am going to keep this open and close the other one as this one is a lot more detailed. It has something to do with google's cache but I don't know anything really about the cache data structure is using or why for some people it crashes.

**Comment by ToMe25** [comment] 2020-10-08 13:08
well, i didn't consider that a possible duplicate, because this isn't mod compat, it happens with mekanism alone, so i didn't read more then the title of that one.

**Comment by pupnewfster** [comment] 2020-10-08 13:10
Ya basically the crash report is more or less the same from a glance, and that person was not a native english speaker and mainly even opened that issue because I told them if they wanted a chance of me remember to look into it they should open one.

**Comment by Wodong77** [comment] 2020-10-08 16:08
Other than the fact that I was in a LAN with another player, the vitals were very similar to original, probably close enough to be considered a duplicate problem.  Survival world but players in creative mode at the time,  (I'm doing a bit of copy pasta because it's the same). Steps to reproduce:

    Place Down a QIO Drive Array
    Put a QIO Drive in it
    guest on LAN CTD  (Note that as the host of the LAN I did not crash out and QIO seemed fine for me)

Version (make sure you are on the latest version before reporting):

Forge: 34.1.12
Mekanism: 10.0.10
Other relevant version: N/A

**Comment by ToMe25** [comment] 2020-10-08 16:27
This should already be fixed, there just isn't a release with the fix yet.

**Closed** 2020-10-08 21:33 UTC
Labels: 1.16, Fixed in dev, Not reproducible, bug
