### ISSUE TITLE
1.21 not launching

### ISSUE THREAD

**Issue by marmot418** [mekanism/Mekanism#8140] opened 2024-06-26 23:10 UTC
### Issue description

I get an error message when trying to open mekanism in 1.21

### Steps to reproduce

1. try to launch mekanism in 1.21

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.38

### Mekanism version

10.6.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/zEK9BCeD

**Comment by UnknownSerhan** [comment] 2024-06-26 23:18
Duplicate of https://github.com/mekanism/Mekanism/issues/8136

**Closed as completed** 2024-06-27 02:49 UTC
Labels: Fixed in dev, 1.21
