### ISSUE TITLE
1.15.2 Machine info does not show in One Probe in SMP

### ISSUE THREAD

**Issue by vedrit** [mekanism/Mekanism#6238] opened 2020-06-24 23:07 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism machine details do not show up in TOP tooltip when playing multiplayer, and instead only shows "Waiting for server..."

#### Steps to reproduce:
1. Join server using Mekanism 9.10.8.421 and The One Probe (either 2.0.3 or 2.0.4)
2. Place Mekanism machine and power source
3. Look at machine

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.2.23** 
**Mekanism: 9.10.8.421** 
**Other relevant version: The One Probe 2.0.4** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/nvwCGmVc

**Comment by pupnewfster** [comment] 2020-06-28 21:49
I was not able to reproduce this, though I did notice one odd thing about the class that was showing up in your error log, which I have corrected. I am marking this as fixed in dev and hopefully when we release 9.10.9 this issue will go away.

**Closed** 2020-07-04 20:22 UTC
Labels: 1.15, Fixed in dev, Mekanism, Not reproducible, interaction, minorimportance
