### ISSUE TITLE
Crash when using a flamethrower in Inferno-Mode on obsidian

### ISSUE THREAD

**Issue by oheoh** [mekanism/Mekanism#6861] opened 2021-01-10 00:24 UTC
#### Issue description:
When using a flamethrower in inferno mode on a block of obsidian that has another block of obsidian floating two blocks above, minecraft crashes with attached crash log. While trying to load into the affected save, minecraft crashes again, making the level unplayable.

Obisdian arrangement:
O = Obsidian
X = Air
O
X
X
O
(View from front)

#### Steps to reproduce:
1. Install Mekanism, create a new save
2. Build a obsidian arrangement as shown above
3. Equip a flamethrower, set it to inferno-mode and fire away at the obsidian
4. Minecraft crashes

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.4 35.1.36** 
**Mekanism: 1.16.4-10.0.18.445** 
**Other relevant version:** 

#### Crash log

[gist](https://gist.github.com/oheoh/2980c94de9dbbf3fde3176a1e9f82fdf)

**Comment by pupnewfster** [comment] 2021-01-30 19:57
So it turns out this is actually caused by one of the two bugs in vanilla that caused them to release 1.16.5. As 10.0.20 will require 1.16.5 for some forge updates (as well as to have this bug fixed), I am marking it as fixed in dev even though just updating to a 1.16.5 version of forge without updating Mekanism also would fix this.

**Closed** 2021-02-13 17:02 UTC
Labels: 1.16, Fixed in dev, Not Mekanism, bug
