### ISSUE TITLE
[Bug] Client side crash upon server reading beyond specific value of items in QIO drive.

### ISSUE THREAD

**Issue by Pantheris2019** [mekanism/Mekanism#7421] opened 2022-02-27 06:53 UTC
### Issue description

When I go to the drive itself to try to remove a drive or something after filling the drive with epic amounts of items, it just crashes clients.  The server is FINE, and just treats it as a client disconnect.

### Steps to reproduce

1. Fill QIO drive with about 40K items ranging over about 2000 types.
2. right click drive. (not the inventory screen thing, but the drive itself.)
3. ENJOY BEING PUNTED! And your new exception. io.netty tries to read too much NBT data specifying it's over a certain max value.

### Minecraft version

1.16.5 (Latest)

### Forge version

32.2.29

### Mekanism version

10.1.2 (Latest)

### Other relevant versions

Actual Mekanism Version: 10.1.2.457

**Comment by pupnewfster** [comment] 2022-02-27 14:31
Duplicate of #6837

**Closed by pupnewfster** 2022-02-27 14:31 UTC
