### ISSUE TITLE
Error and Crash on loading the mod with the newest version

### ISSUE THREAD

**Issue by Fidulus** [mekanism/Mekanism#8139] opened 2024-06-26 10:16 UTC
### Issue description

![image](https://github.com/mekanism/Mekanism/assets/48780170/fa4ae3ed-dfc6-4f98-b4ba-d03653033183)

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.37 beta

### Mekanism version

10.6.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/CthqfWeT

**Comment by UnknownSerhan** [comment] 2024-06-26 10:25
Duplicate of https://github.com/mekanism/Mekanism/issues/8136

**Closed as completed** 2024-06-26 11:38 UTC
Labels: Didn't bother searching
