### ISSUE TITLE
The Elite and Ultimate Induction Cell list the wrong figures for the storage space

### ISSUE THREAD

**Issue by ThePanman** [mekanism/Mekanism#5642] opened 2019-09-15 00:36 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The Elite and Ultimate Induction Cell list the wrong figures for the storage space. They both only seem to report 2.14GRF, both on the tooltip and when inside the multiblock.

#### Steps to reproduce:
1. Acquire induction Cell
2. Look at tool tip or place inside multiblock

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 1.12.2-9.8.1.383
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
Gif
https://i.imgur.com/LZCcHRX.gifv

**Comment by pupnewfster** [comment] 2019-09-15 00:40
Duplicate of #5609

**Closed by pupnewfster** 2019-09-15 00:40 UTC
