### ISSUE TITLE
Pipes/Tubes/etc stop delivering to machine

### ISSUE THREAD

**Issue by sibernetik** [mekanism/Mekanism#7099] opened 2021-04-11 21:58 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Pipes/Tubes/etc stop delivering to machines. For example: I have a Fission Reactor that I am pulling the Radioactive Waste from and sending it to a Solar Neutron Activator. Randomly, (and I think it may be a chunk issue), the SNA stops receiving waste. The tubes are full of waste, but the SNA is empty. I tried replacing the SNA with no success. The only success I have had is to break all of the tubes and place them back down. This has also happened with Universal Cables.

#### Steps to reproduce:
1. See above

#### Version (make sure you are on the latest version before reporting):
**Forge:*1.16.5* 
**Mekanism:*1.10* 
**Other relevant version:*Valhelsia 3 v1.16.5*

**Comment by pupnewfster** [comment] 2021-04-11 22:08
I am not sure if Valhelsia tweaks the default configs for Performant but if it doesn't try disabling tick event load balancing and tile tick load balancing. (Or just try removing performant all together imo the mod causes more issues than it solves in a modded environment).

**Comment by UpperManglement** [comment] 2021-04-11 22:38
I'm the server owner for the above issue, been working with Sibernetik on reproducing it. I've attached the performant config file here, I haven't made any changes to it myself. I'm assuming you're referring to "TELoadBalancing" and "eventLoadBalancing" in the configs? By default with Valhelsia, it looks like TELoadBalancing is enabled, but eventLoadBalancing is not.
[performant-common.toml.txt](https://github.com/mekanism/Mekanism/files/6292894/performant-common.toml.txt)

also here's the full version numbers:

- forge-1.16.5-36.1.3.jar
- Mekanism-1.16.5-10.0.21.448.jar
- modpack: Valhelsia 3, version 3.2.3

**Comment by pupnewfster** [comment] 2021-04-12 14:42
Not really sure what is going on to be honest, I feel like this is likely the same issue as #6356 (so I am going to close this for now and merge into that issue) but I have yet to be able to reproduce it myself and so far everyone who has reported it has had a relatively large number of mods which makes finding a minimum reproduction setup rather difficult.

**Closed by pupnewfster** 2021-04-12 14:42 UTC
Labels: 1.16, Waiting Feedback
