### ISSUE TITLE
Metallurgic Infuser not working

### ISSUE THREAD

**Issue by Darkfiend009** [mekanism/Mekanism#5477] opened 2019-05-14 22:54 UTC
#### Issue description:
Metallurgic Infuser won't begin process for any materials. I tried to make Enriched Alloy, Reinforced Alloy and a Basic Control Circuit. It takes the redstone/diamond dust and adds it to the reservoir but when i add an Iron ingot, Osmium ingot, or Enriched Alloy nothing happens. The machine does have power. This is also occurring in single player and on a server.  

#### Steps to reproduce:
1. Place Metallurgic Infuser
2. Provide Power
3. Add infusing material
4. Add material to be infused
5. Nothing processes.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2825
**Mekanism:** 1.12.2-9.7.4.375
**Other relevant version:** Mekanism Generators and Tools are also installed at 9.7.4.375

Screenshot: https://ibb.co/q5mFTZK
Modlist: https://pastebin.com/B52KWb4J

**Comment by pupnewfster** [comment] 2019-05-20 22:47
Couple things, if you could double check this still occurs for you in 9.7.5 that would be great. I don't think anything changed regarding that but doesn't hurt to check. Secondly, the recipe does show up in JEI right? Because if now my guess is some mod is removing it for some reason.

**Comment by Darkfiend009** [comment] 2019-05-21 03:01
I will update the modpack i am using and the server overnight and test it tomorrow afternoon to see if 9.7.5 makes a difference. I will let you know!

Also, the recipes do show in JEI properly. I double checked that just to be sure.

**Comment by Darkfiend009** [comment] 2019-05-21 13:34
The issue still persists in 9.7.5. Tried both osmium and iron ingots with redstone in the reservoir. 

Here is a screenshot of JEI showing the recipes for both:
https://ibb.co/8bYHhcg

**Comment by pupnewfster** [comment] 2019-05-21 14:50
I will try to look at it later, is there a download link to the pack? As my suspicion is it has something to do with some weird mod interaction, if not I will just download the different mods you listed above (it just probably will take a bit longer)

**Comment by Darkfiend009** [comment] 2019-05-21 15:47
I appreciate it! Yes, the pack is hosted on curseforge. It's for my streaming community:

https://minecraft.curseforge.com/projects/twitch-kittens-reforged?

**Comment by pupnewfster** [comment] 2019-05-22 14:23
Ok, I need to look into it more and try to figure out what is going on, BUT I am able to reproduce it with your pack so at least that is a good sign. (From the point of view that it *should* be easier to track down)

**Comment by Darkfiend009** [comment] 2019-05-22 14:37
I understand. If there is anything i can do to help, just let me know.

**Comment by thiakil** [comment] 2019-05-23 04:43
One (very time consuming) way is to start with just Mek + Forge, and add mods from your pack until the issue occurs (starting with mods that seem relevant, e.g. Unidict et al)

**Comment by pupnewfster** [comment] 2019-05-27 16:27
It seems that every single item in your pack has an empty NBT tag. Yesterday I made a "fix" that basically makes empty NBT tags equate as equal to no tag, except I decided that this is not ideal because there are times when an empty NBT tag and no NBT tag actually mean different things for some mods.

It seems to be due to this https://github.com/Calemi/CalemiUtils/issues/4 (Or more accurately from what I can tell all items, given it also has ones in the creative menu have an empty NBT tag). After looking at their code briefly I *believe* I know what is causing it, and I will make a comment on that issue to help him be able to fix it.

**Comment by Darkfiend009** [comment] 2019-05-27 18:52
You beat me to the punch. I had been doing the 1 by 1 mod testing with Mekansim as thiakil mentioned and had it narrowed down to 3 possibilities. Calemi's was one.

Thank you for looking into this and finding the issue! I've been self teaching myself about mods, packs, and Java but wasn't sure where to really begin for this. My community and i really appreciate it!

**Comment by pupnewfster** [comment] 2019-05-31 22:18
Closing this as it seems that a release of the other mod was made that from what I can tell is supposed to fix this.

**Closed by pupnewfster** 2019-05-31 22:18 UTC
Labels: Not Mekanism, bug
