### ISSUE TITLE
Quantum Entangloporter never stops pulling energy

### ISSUE THREAD

**Issue by unclaspedsteele** [mekanism/Mekanism#6015] opened 2020-03-31 18:51 UTC
I believe this is a problem. I am still new to this mod, so I may just be misunderstanding the block, but I have it hooked up to my Extreme Reactor that generates 333kRF. I also have an OpenComputer setup hooked up to monitor the reactors buffer and turn it off when the internal buffer fills up. Here is where the problem is. Once I hook up the entangloporter, its 2b buffer fills up and keeps draining energy from my reactor instead of stopping. Is this a normal behavior, or is this a bug?

**Comment by pupnewfster** [comment] 2020-03-31 19:12
What version is this, and the quantum entangloporter does have an internal buffer.

**Comment by unclaspedsteele** [comment] 2020-03-31 19:29
1.12.2-9.8.3.390

**Comment by thiakil** [comment] 2020-03-31 22:16
It's a very large buffer, how are you sure it has been filled?

**Comment by unclaspedsteele** [comment] 2020-03-31 22:19
It may not be, but waila is showing the buffer is somewhere near 2.14 billion RF. and stays there and continues to keep drawing power from the entangloporter.

**Comment by pupnewfster** [comment] 2020-04-01 19:00
Not sure what is going on here, but as I am not able to reproduce it in the 1.15 branch so am going ahead and closing this. (Though I did find a second unrelated issue in the 1.15 branch with quantum entangloporters which I will fix)

**Closed by pupnewfster** 2020-04-01 19:00 UTC
Labels: Format not followed, Old MC

**Comment by alexchomiak** [comment] 2020-05-13 21:28
I'm having this same issue in 1.12. Has there been a fix?

**Comment by pupnewfster** [comment] 2020-05-13 21:41
If this is actually an issue in 1.12 (never bothered confirming) then no, the only "fix" would be updating to 1.15.
