### ISSUE TITLE
Turbine crashed server

### ISSUE THREAD

**Issue by SayonaraQ** [mekanism/Mekanism#5495] opened 2019-05-30 13:48 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

When the turbine is formed, the server crashes.

#### Steps to reproduce:
1. Build a turbine 5x5x6

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.2-14.23.5.2838 ** 
**Mekanism: 1.12.2-9.7.5.376**
**MekanismGenerators-1.12.2-9.7.5.376**

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
```
Time: 5/30/19 4:30 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at mekanism.generators.common.content.turbine.TurbineFluidTank.getFluidAmount(TurbineFluidTank.java:113)
        at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.getRedstoneLevel(TileEntityTurbineValve.java:417)
        at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.onUpdate(TileEntityTurbineValve.java:67)
        at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)
        at net.minecraft.world.World.func_72939_s(World.java:1835)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at mekanism.generators.common.content.turbine.TurbineFluidTank.getFluidAmount(TurbineFluidTank.java:113)
        at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.getRedstoneLevel(TileEntityTurbineValve.java:417)
        at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.onUpdate(TileEntityTurbineValve.java:67)
        at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)

-- Block entity being ticked --
Details:
        Name: mekanismgenerators:turbine_valve // mekanism.generators.common.tile.turbine.TileEntityTurbineValve
        Block type: ID #2580 (tile.Generator // mekanism.generators.common.block.BlockGenerator$1 // mekanismgenerators:generator)
        Block data value: 11 / 0xB / 0b1011
        Block location: World: (249,64,46), Chunk: (at 9,4,14 in 15,2; contains blocks 240,0,32 to 255,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Actual block type: ID #2580 (tile.Generator // mekanism.generators.common.block.BlockGenerator$1 // mekanismgenerators:generator)
        Actual block data value: 11 / 0xB / 0b1011
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1835)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_211, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 3808711080 bytes (3632 MB) / 4251975680 bytes (4055 MB) up to 5726797824 bytes (5461 MB)
        JVM Flags: 2 total; -Xms3G -Xmx6G
        IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
        FML: MCP 9.42 Powered by Forge 14.23.5.2838 99 mods loaded, 99 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State  | ID                                | Version                  | Source                                           | Signature                                |
        |:------ |:--------------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
        | LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                    | None                                     |
        | LCHIJA | mcp                               | 9.42                     | minecraft.jar                                    | None                                     |
        | LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LCHIJA | forge                             | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | LCHIJA | foamfixcore                       | 7.7.4                    | minecraft.jar                                    | None                                     |
        | LCHIJA | opencomputers|core                | 1.7.4.153                | minecraft.jar                                    | None                                     |
        | LCHIJA | actuallyadditions                 | 1.12.2-r148              | ActuallyAdditions-1.12.2-r148.jar                | None                                     |
        | LCHIJA | buildcraftlib                     | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | buildcraftcore                    | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | buildcraftfactory                 | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | buildcrafttransport               | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | buildcraftsilicon                 | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | additionalpipes                   | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                      | None                                     |
        | LCHIJA | appliedenergistics2               | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar             | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
        | LCHIJA | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                     | None                                     |
        | LCHIJA | ae2stuff                          | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                    | None                                     |
        | LCHIJA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
        | LCHIJA | endercore                         | 1.12.2-0.5.57            | EnderCore-1.12.2-0.5.57.jar                      | None                                     |
        | LCHIJA | jei                               | 4.15.0.279               | jei_1.12.2-4.15.0.279.jar                        | None                                     |
        | LCHIJA | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | LCHIJA | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | LCHIJA | cofhcore                          | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar           | None                                     |
        | LCHIJA | cofhworld                         | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | LCHIJA | thermalfoundation                 | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | LCHIJA | thermalexpansion                  | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.39-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | LCHIJA | enderio                           | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
        | LCHIJA | enderiointegrationtic             | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | tconstruct                        | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                 | None                                     |
        | LCHIJA | p455w0rdslib                      | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                   | None                                     |
        | LCHIJA | ae2wtlib                          | 1.0.6                    | AE2WTLib-1.12.2-1.0.6.jar                        | None                                     |
        | LCHIJA | aroma1997core                     | 2.0.0.2.b165             | Aroma1997Core-1.12.2-2.0.0.2.b165.jar            | dfbfe4c473253d8c5652417689848f650b2cbe32 |
        | LCHIJA | aromabackup                       | 3.0.0.0.b117             | AromaBackup-1.12.2-3.0.0.0.b117.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
        | LCHIJA | aromabackuprecovery               | 3.0.0.0.b117             | AromaBackup-1.12.2-3.0.0.0.b117.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
        | LCHIJA | bedrockbgone                      | 5.0.8                    | BedrockBGone-1.12.2-5.0-b8.jar                   | None                                     |
        | LCHIJA | biomesoplenty                     | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar    | None                                     |
        | LCHIJA | bookshelf                         | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
        | LCHIJA | buildcraftbuilders                | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | buildcraftenergy                  | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | ic2                               | 2.8.153-ex112            | industrialcraft-2-2.8.153-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
        | LCHIJA | forestry                          | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                    | None                                     |
        | LCHIJA | theoneprobe                       | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                      | None                                     |
        | LCHIJA | buildcraftcompat                  | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | buildcraftrobotics                | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                     | None                                     |
        | LCHIJA | rf-capability-adapter             | 1.0                      | capabilityadapter-1.0.1.jar                      | None                                     |
        | LCHIJA | chickenchunks                     | 2.4.0.70                 | ChickenChunks_1.12_2.4.0.70_universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | LCHIJA | elevatorid                        | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                     | None                                     |
        | LCHIJA | eplus                             | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
        | LCHIJA | enderiobase                       | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | enderioconduits                   | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | enderioconduitsappliedenergistics | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | opencomputers                     | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar             | None                                     |
        | LCHIJA | enderioconduitsopencomputers      | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | refinedstorage                    | 1.6.14                   | refinedstorage-1.6.14.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
        | LCHIJA | enderioconduitsrefinedstorage     | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | enderiointegrationforestry        | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | enderiointegrationticlate         | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | enderiomachines                   | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | enderiopowertools                 | 5.0.44                   | EnderIO-1.12.2-5.0.44.jar                        | None                                     |
        | LCHIJA | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | LCHIJA | extracells                        | 2.6.2                    | ExtraCells-1.12.2-2.6.2a.jar                     | None                                     |
        | LCHIJA | mcmultipart                       | 2.5.3                    | MCMultiPart-2.5.3.jar                            | None                                     |
        | LCHIJA | mekanism                          | 1.12.2-9.7.5.376         | Mekanism-1.12.2-9.7.5.376.jar                    | None                                     |
        | LCHIJA | sonarcore                         | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                   | None                                     |
        | LCHIJA | fluxnetworks                      | 3.0.19                   | fluxnetworks-1.12.2-3.0.19-21.jar                | None                                     |
        | LCHIJA | foamfix                           | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                        | None                                     |
        | LCHIJA | gravestone                        | 1.10.2                   | gravestone-1.10.2.jar                            | None                                     |
        | LCHIJA | gravisuite                        | 3.1.1                    | Gravitation+Suite-3.1.1.jar                      | None                                     |
        | LCHIJA | immersiveengineering              | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                 | 4cb49fcde3b43048c9889e0a3d083225da926334 |
        | LCHIJA | immersivecables                   | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                 | None                                     |
        | LCHIJA | instantunify                      | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                    | None                                     |
        | LCHIJA | inventorytweaks                   | 1.64+dev.146.2180b27     | InventoryTweaks-1.64+dev.146.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
        | LCHIJA | ironchest                         | 1.12.2-7.0.64.843        | ironchest-1.12.2-7.0.64.843.jar                  | None                                     |
        | LCHIJA | journeymap                        | 1.12.2-5.5.5b7           | journeymap-1.12.2-5.5.5b7.jar                    | None                                     |
        | LCHIJA | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                     | None                                     |
        | LCHIJA | malisisblocks                     | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                   | None                                     |
        | LCHIJA | malisisdoors                      | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
        | LCHIJA | mekanismgenerators                | 1.12.2-9.7.5.376         | MekanismGenerators-1.12.2-9.7.5.376.jar          | None                                     |
        | LCHIJA | numina                            | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                         | None                                     |
        | LCHIJA | powersuits                        | 1.12.2-1.0.41            | ModularPowersuits-1.12.2-1.0.41.jar              | None                                     |
        | LCHIJA | naturescompass                    | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                  | None                                     |
        | LCHIJA | nei                               | 2.4.2                    | notenoughitems-1.12.2-2.4.2.240-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | LCHIJA | omlib                             | 3.1.0-232                | omlib-1.12.2-3.1.0-232.jar                       | None                                     |
        | LCHIJA | practicallogistics2               | 3.0.8                    | practicallogistics2-1.12.2-3.0.8-11.jar          | None                                     |
        | LCHIJA | xreliquary                        | 1.12.2-1.3.4.786         | Reliquary-1.12.2-1.3.4.786.jar                   | None                                     |
        | LCHIJA | solarflux                         | 4.32r                    | SolarFluxReborn_1.12.2-4.32r.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
        | LCHIJA | subcommonlib                      | 1.2.0.1                  | subcommonlib-sublib-1.12-1.2.0.1.jar             | None                                     |
        | LCHIJA | thermalcultivation                | 0.3.2                    | ThermalCultivation-1.12.2-0.3.2.11-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | LCHIJA | thermaldynamics                   | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | LCHIJA | thermalinnovation                 | 0.3.2                    | ThermalInnovation-1.12.2-0.3.2.11-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
        | LCHIJA | tinker_io                         | rw2.7.1                  | tinker_io-1.12.2-rw2.7.1.jar                     | None                                     |
        | LCHIJA | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar              | None                                     |
        | LCHIJA | topaddons                         | 1.12.2-1.11.0            | topaddons-1.12.2-1.11.0.jar                      | None                                     |
        | LCHIJA | torchmaster                       | 1.7.1.74                 | torchmaster_1.12.2-1.7.1.74.jar                  | 5e9a436b366831c8f54a7e80b015784da69278c6 |
        | LCHIJA | bspkrscore                        | at_0.9                   | treecapitator-mod-1.12.jar                       | None                                     |
        | LCHIJA | treecapitator                     | at_0.9                   | treecapitator-mod-1.12.jar                       | None                                     |
        | LCHIJA | wanionlib                         | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                         | None                                     |
        | LCHIJA | wct                               | 3.11.88                  | WirelessCraftingTerminal-1.12.2-3.11.88.jar      | None                                     |
        | LCHIJA | unidict                           | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                         | None                                     |

        Loaded coremods (and transformers):
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.7.5.376.jar)
  mekanism.coremod.KeybindingMigrationHelper
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)

TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)

        AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
        Pulsar/tconstruct loaded Pulses:
                - TinkerCommons (Enabled/Forced)
                - TinkerWorld (Enabled/Not Forced)
                - TinkerTools (Enabled/Not Forced)
                - TinkerHarvestTools (Enabled/Forced)
                - TinkerMeleeWeapons (Enabled/Forced)
                - TinkerRangedWeapons (Enabled/Forced)
                - TinkerModifiers (Enabled/Forced)
                - TinkerSmeltery (Enabled/Not Forced)
                - TinkerGadgets (Enabled/Not Forced)
                - TinkerOredict (Enabled/Forced)
                - TinkerIntegration (Enabled/Forced)
                - TinkerFluids (Enabled/Forced)
                - TinkerMaterials (Enabled/Forced)
                - TinkerModelRegister (Enabled/Forced)
                - theoneprobeIntegration (Enabled/Not Forced)

        List of loaded APIs:
                * actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r148.jar
                * ae2wtlib|api (1.1) from AE2WTLib-1.12.2-1.0.6.jar
                * apAPI (3) from additionalpipes-6.0.0.8.jar
                * appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-6.jar
                * Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
                * buildcraftapi_blocks (1.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_boards (2.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_core (2.2) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_crops (1.1) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_enums (1.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_events (2.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_facades (1.1) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_filler (5.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_fuels (2.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_gates (4.1) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_items (1.1) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_library (2.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_lists (1.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_power (1.3) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_recipes (3.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_robotics (3.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_statements (1.1) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_tiles (1.2) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_tools (1.0) from buildcraft-all-7.99.24.1.jar
                * buildcraftapi_transport (5.0) from buildcraft-all-7.99.24.1.jar
                * cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.2.25-universal.jar
                * enderioapi (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.44.jar
                * fluxapi (1.0) from fluxnetworks-1.12.2-3.0.19-21.jar
                * ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.387.jar
                * ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.387.jar
                * ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-89.jar
                * ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-89.jar
                * journeymap|client-api (1.4) from journeymap-1.12.2-5.5.5b7.jar
                * journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.5b7.jar
                * journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.5b7.jar
                * journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.5b7.jar
                * journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.5b7.jar
                * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.279.jar
                * MekanismAPI|core (9.7.5) from Mekanism-1.12.2-9.7.5.376.jar
                * MekanismAPI|energy (9.7.5) from Mekanism-1.12.2-9.7.5.376.jar
                * MekanismAPI|gas (9.7.5) from Mekanism-1.12.2-9.7.5.376.jar
                * MekanismAPI|infuse (9.7.5) from Mekanism-1.12.2-9.7.5.376.jar
                * MekanismAPI|laser (9.7.5) from Mekanism-1.12.2-9.7.5.376.jar
                * MekanismAPI|transmitter (9.7.5) from Mekanism-1.12.2-9.7.5.376.jar
                * MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.7.5.376.jar
                * MouseTweaks|API (1.0) from MouseTweaks-2.10-mc1.12.2.jar
                * opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
                * practicallogistics2-api (3.1) from practicallogistics2-1.12.2-3.0.8-11.jar
                * ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12.2-2.0.36.jar
                * redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
                * sonarapi (1.0.1) from sonarcore-1.12.2-5.0.19-20.jar
                * theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.28.jar
                * wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.11.88.jar
```
[gist/pastebin/etc link here]

**Comment by Sitheau** [comment] 2019-05-31 03:16
Just ran into a similar issue found out that if you don't have any vents attached it won't crash

**Comment by pupnewfster** [comment] 2019-05-31 05:01
This issue has been posted a few times and is fixed in dev by https://github.com/mekanism/Mekanism/commit/65ed1cf062fa59b3792fa241ad2547e629cc90fc

**Closed by pupnewfster** 2019-05-31 05:01 UTC
Labels: Fixed in dev, bug, duplicate

**Comment by Gunner76th** [comment] 2019-06-19 22:27
@SayonaraQ Does this crash cause world corruption (IE server is never able to start back up), or does it crash, but then when you restart everything is working?

**Comment by StephenLujan** [comment] 2019-09-02 17:17
> @SayonaraQ Does this crash cause world corruption (IE server is never able to start back up), or does it crash, but then when you restart everything is working?

It doesn't cause corruption in the normal computer science sense of the word (unintended, usually random, data alteration leading to unexpected behavior and crashes), but for me it did cause the world to crash on startup as the conditions right before the error occurs are saved so they repeat on loading.
