### ISSUE TITLE
formulaic assemblicator crashing server when starting auto crafting

### ISSUE THREAD

**Issue by STATEDLIGHT** [mekanism/Mekanism#5781] opened 2020-01-16 23:52 UTC
Description: Ticking block entity

java.lang.RuntimeException: Invalid stack for slot.
	at mekanism.common.inventory.slot.BasicInventorySlot.setStack(BasicInventorySlot.java:126) ~[?:?] {re:classloading}
	at mekanism.common.inventory.slot.BasicInventorySlot.setStack(BasicInventorySlot.java:107) ~[?:?] {re:classloading}
	at mekanism.common.tile.TileEntityFormulaicAssemblicator.moveItemsToGrid(TileEntityFormulaicAssemblicator.java:385) ~[?:?] {re:classloading}
	at mekanism.common.tile.TileEntityFormulaicAssemblicator.onUpdate(TileEntityFormulaicAssemblicator.java:207) ~[?:?] {re:classloading}
	at mekanism.common.tile.base.TileEntityMekanism.func_73660_a(TileEntityMekanism.java:389) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:473) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mekanism.common.inventory.slot.BasicInventorySlot.setStack(BasicInventorySlot.java:126)
	at mekanism.common.inventory.slot.BasicInventorySlot.setStack(BasicInventorySlot.java:107)
	at mekanism.common.tile.TileEntityFormulaicAssemblicator.moveItemsToGrid(TileEntityFormulaicAssemblicator.java:385)
	at mekanism.common.tile.TileEntityFormulaicAssemblicator.onUpdate(TileEntityFormulaicAssemblicator.java:207)
	at mekanism.common.tile.base.TileEntityMekanism.func_73660_a(TileEntityMekanism.java:389)

-- Block entity being ticked --
Details:
	Name: mekanism:formulaic_assemblicator // mekanism.common.tile.TileEntityFormulaicAssemblicator
	Block: Block{mekanism:formulaic_assemblicator}[active=false,facing=south]
	Block location: World: (528,64,-1763), Chunk: (at 0,4,13 in 33,-111; contains blocks 528,0,-1776 to 543,255,-1761), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
	Block: Block{mekanism:formulaic_assemblicator}[active=false,facing=south]
	Block location: World: (528,64,-1763), Chunk: (at 0,4,13 in 33,-111; contains blocks 528,0,-1776 to 543,255,-1761), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:473)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2808
	Level dimension: DimensionType{minecraft:overworld}
	Level name: world
	Level seed: -3794323954148762815
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (144,70,-90), Chunk: (at 0,4,6 in 9,-6; contains blocks 144,0,-96 to 159,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 7886545 game time, 180159 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 2770 (now: true), thunder time: 119908 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Linux (amd64) version 4.15.0-74-generic
	Java Version: 1.8.0_232, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 199194792 bytes (189 MB) / 1604845568 bytes (1530 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 1 total; -Xmx4096M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.1-30.0.39.jar fml TRANSFORMATIONSERVICE 
	FML: 30.0
	Forge: net.minecraftforge:30.0.39
	FML Language Providers: 
		javafml@30.0
		minecraft@1
	Mod List: 
		forge-1.15.1-30.0.39-server.jar Minecraft {minecraft@1.15.1 DONE}
		SereneSeasons-1.15.1-3.0.0.43-universal.jar Serene Seasons {sereneseasons@1.15.1-3.0.0.41 DONE}
		mcw-bridges-1.0.3-mc1.15.1.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		elevatorid-1.15.1-1.5.4.jar Elevator Mod {elevatorid@1.15.1-1.5.4 DONE}
		MekanismTools-1.15.1-9.9.2.393.jar Mekanism: Tools {mekanismtools@9.9.2 DONE}
		ChunkNoGoByeBye-1.15.1-1.1.0.jar ChunkNoGoByeBye {chunknogobyebye@1.15.1-1.1.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		Morpheus-1.15.1-4.2.45.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.1-9.9.2.393.jar Mekanism: Generators {mekanismgenerators@9.9.2 DONE}
		Hwyla-forge-1.10.7-B71_1.15.1.jar Waila {waila@version DONE}
		jei-1.15.1-6.0.0.1.jar Just Enough Items {jei@6.0.0.1 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		magicmirror-1.0.4.1.jar Magic Mirrors {magicmirror@1.0.4.1 DONE}
		Mekanism-1.15.1-9.9.2.393 (1).jar Mekanism {mekanism@9.9.2 DONE}
		forge-1.15.1-30.0.39-universal.jar Forge {forge@30.0.39 DONE}
		Xaeros_Minimap_1.19.6_Forge_1.15.1.jar Xaero's Minimap {xaerominimap@1.19.6 DONE}
		SuperTools-1.0b_1.15.1.jar Super Tools {supertools@1.0b DONE}
		XaerosWorldMap_1.5.4_Forge_1.15.1.jar Xaero's World Map {xaeroworldmap@1.5.4 DONE}
		corpse-1.15.1-1.0.0.jar Corpse {corpse@1.15.1-1.0.0 DONE}
		SimpleDivingGear-4.0.0 mc 1.15.1.jar Simple Diving Gear {simpledivegear@4.0.0 mc 1.15.1 DONE}
		[1.15.1] SecurityCraft v1.8.15-beta2 (1).jar SecurityCraft {securitycraft@v1.8.15-beta2 DONE}
	Player Count: 0 / 10; []
	Data Packs: vanilla, file/bukkit, mod:forge (incompatible), mod:cfm (incompatible), mod:chunknogobyebye, mod:corpse, mod:elevatorid, mod:jei (incompatible), mod:mcwbridges, mod:mekanism, mod:mekanismgenerators, mod:mekanismtools, mod:metalbarrels (incompatible), mod:morpheus (incompatible), mod:securitycraft (incompatible), mod:sereneseasons, mod:simpledivegear (incompatible), mod:supertools (incompatible), mod:waila (incompatible), mod:xaerominimap, mod:xaeroworldmap, mod:magicmirror (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by pupnewfster** [comment] 2020-01-17 00:01
First off please don't just delete the issue format it is there for a reason, and the format specifies also to check open issues and to paste logs in a site like gist or pastebin. But either way this is a duplicate of #5769

**Closed by pupnewfster** 2020-01-17 00:01 UTC

**Comment by STATEDLIGHT** [comment] 2020-01-17 00:15
Sorry I just jumped on here and posted, didn't mean to ruffle anyone's feathers.
