### ISSUE TITLE
No measured output on induction multiblocks

### ISSUE THREAD

**Issue by D3nnis3n** [mekanism/Mekanism#5032] opened 2018-04-29 11:17 UTC
#### Issue description:
Input is shown, output is never shown.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2655
**Mekanism:** 341

<img width="428" alt="output" src="https://user-images.githubusercontent.com/25908592/39405973-a60bc83c-4baf-11e8-8d68-a493646d4797.png">
<img width="447" alt="input" src="https://user-images.githubusercontent.com/25908592/39405975-a97e55a2-4baf-11e8-9b4a-704339252a48.png">

And yes, the first outputs to the second atm.

**Comment by thommy101** [comment] 2018-04-29 18:55
The induction matrix is probably on a chunk border. There are some issues with that.
Please replace the structure so it is in a singel chunk.
Closing as duplicate of #3837

**Comment by D3nnis3n** [comment] 2018-04-29 19:00
@thommy101 
No it is not. I was being made aware of problems with multiblocks between chunks before and my multiblocks from mekanism are all in a single chunk.

**Comment by felixletsplayYT** [comment] 2018-09-16 11:55
Same problem here with Mekanism 1.12.2-9.4.13.349.
Also only one chunk

**Comment by aidancbrady** [comment] 2020-02-12 04:55
Was never able to figure out this issue. @pupnewfster and I will take a look in the near-term.

**Comment by D3nnis3n** [comment] 2020-02-12 05:12
Uh, that was a long time ago, lol.

**Comment by aidancbrady** [comment] 2020-03-05 01:08
Happy to say that I can no longer reproduce this with recent changes in the 1.15 branch.

**Closed by aidancbrady** 2020-03-05 01:08 UTC
Labels: important

**Comment by D3nnis3n** [comment] 2020-03-05 02:22
Happy to hear, even though i'm no longer playing Minecraft currently, as i'm now working for "competitor" game development studio myself, haha.

**Comment by D3nnis3n** [comment] 2020-04-01 01:40
@aidancbrady We started playing Minecraft again due to Corona Lockdown, with our old modpack on 1.12, there it's still broken. I assume you're not going to backport the fix?

Unfortunately 1.15 misses more than 80% of our mods, including 90% of our "not without" mods like EnderIO.
