### ISSUE TITLE
[Mekanism] - Console Stacksize Spam Error

### ISSUE THREAD

**Issue by AnCasper** [mekanism/Mekanism#7776] opened 2023-04-18 15:11 UTC
### Issue description

Console spam with messages about "Stacksize changed by different amount" error. Flags a bunch of times at any given time. See below attachments for more details. No crash log to submit.

Direct Error: [Console Spam Messages](https://mclo.gs/mKONtoM) 

### Steps to reproduce

1: ATM8 Modpack
2: Hop on server
3: Use any mekanism machine
4: Console spam
5: Let your OCD kick in :)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

10.3.8 (Latest)

### Other relevant versions

Specific to: Mekanism-1.19.2-10.3.8.477

**Comment by JakeCarneAsada** [comment] 2023-05-24 03:25
Same thing here, but it times everyone on the server out with the error.

**Comment by AnCasper** [comment] 2023-05-24 04:19
@JakeCarneAsada Yea the more machines that people make the worse the spam gets. Does your hardware max out by any chance? We’re running a really beefy machine and have had no timeouts due to this message.

**Comment by JakeCarneAsada** [comment] 2023-05-24 05:06
@AnCasper The server is on a BisectHosting 5GB setup and runs with about 100 other smaller mods. There are probably about 3 ore processing machines that are fed by lots of quarries, but they are spread across the map about 2000 blocks from each other. I suppose eliminating one would reduce the error.

**Comment by pupnewfster** [comment] 2023-06-06 19:26
Duplicate of #7741

**Closed by pupnewfster** 2023-06-06 19:26 UTC
