### ISSUE TITLE
#3077 still present in Mekanism version 9.4.3.330 (energy loss with ultimate cable and cryo-stab. fluxduct)

### ISSUE THREAD

**Issue by aerde** [mekanism/Mekanism#4898] opened 2018-01-03 18:31 UTC
#### Issue description:
Same issue as #3077

#### Steps to reproduce:
1.connect cryostab. fluxduct to TE energy cell (full)
2.connect ultimate universal cable to cryostab fluxduct
3.watch energy goes down

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2582
**Mekanism:** 9.4.3.330
**Other relevant version:** Modern Skyblock 2 modpack, minecraft 1.12.2, LAN singleplayer

**Comment by thiakil** [comment] 2018-01-04 02:44
are you sure it's not the cable's buffer you're seeing?

**Comment by aerde** [comment] 2018-01-04 03:43
Either one piece of ultimate cable's buffer is enourmous and eat 200 MRF and 30 KRF/t, or it's not the buffer. Problem is totally replicable with just energy cell (resonant one, 50MRF) one piece of cryo-stabilized fluxduct on it, and one piece of ultimate universal cable on top, connected to nothing more. And cryo-stabilized fluxduct don't have internal buffer.

**Comment by pupnewfster** [comment] 2019-04-23 19:50
Not quite sure what is causing this (probably something to do with the casting to/from doubles) but I tested against 9.7.2 (and could reproduce it), and against #5422 and was unable to reproduce it. Which means that once #5422 is merged this should be fixed.

**Closed** 2019-04-30 14:27 UTC
Labels: Fixed in dev
