### ISSUE TITLE
All the Mods 5 - Mekanism Item Duplication BUG REPORT

### ISSUE THREAD

**Issue by Salonikiozzz** [mekanism/Mekanism#6225] opened 2020-06-18 15:13 UTC
Charging items inside the Induction Matrix Duplicates items. Modpack version 2.1

Video showcase below:

https://www.youtube.com/watch?v=UELTUGFN6CY

**Comment by pupnewfster** [comment] 2020-06-18 15:22
Unable to reproduce this, my best guess is either something weird is going on with the item you are charging, or maybe all the mods is using an older version of Mekanism. I know quite a few versions ago we did have a desync bug that would cause it to *look* like there was a duplicated item which would disappear after closing and reopening your inventory. I am not however going to bother installing a modpack just to see what version of Mekanism it uses.

**Closed by pupnewfster** 2020-06-18 15:22 UTC
Labels: 1.15, Format not followed, Not reproducible, interaction

**Comment by Salonikiozzz** [comment] 2020-06-18 15:24
This is not a desync issue as i can drop them on the ground and tried relogging on the server.

**Comment by pupnewfster** [comment] 2020-06-18 15:33
What version of Mekanism does ATM 5 use, and are you able to reproduce this with other energy based items or is it just the drill that it happens with.
