### ISSUE TITLE
DigitalMiner-Filter doesn't work 

### ISSUE THREAD

**Issue by DaWegi** [mekanism/Mekanism#7485] opened 2022-05-22 08:12 UTC
### Issue description

My friends and I have a MC-Server with the Modpack "Valhelsia 3 1.16.8" and in this Modpack is Mekanism included. My friend built a DM but the filters doesn't work. You can create a filter, tag or modID, but it mines everything (Stone, Diorite, ...). I don't know what to do, we have tried *ore* / ore* / forge:ore / ..., but nothing works.

### Steps to reproduce

Placed DM
created Filter
doesn't work

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.31

### Mekanism version

Older

**Comment by leadwolf32** [comment] 2022-05-22 09:48
Hey just wanna make sure, it's not set to inverse mode is it? That'll make it so it mines everything but what's in the filter. There a little 'i' icon in the filter screen

**Comment by DaWegi** [comment] 2022-05-22 11:39
> Hey just wanna make sure, it's not set to inverse mode is it? That'll make it so it mines everything but what's in the filter. There a little 'i' icon in the filter screen

thx for the reply, but no, its not on reverse mode

**Comment by DaWegi** [comment] 2022-05-22 13:23
problem solved, my friend made a copy of the world, and reset the server

**Comment by pupnewfster** [comment] 2022-05-22 17:44
in general I recommend people using `forge:ores` I don't know if `forge:ore` matches anything but I do know some mods might add things that have `ore` somewhere in the name. Closing this though as you say the issue is solved.

**Closed by pupnewfster** 2022-05-22 17:44 UTC
