### ISSUE TITLE
Upgrading QIO Drives

### ISSUE THREAD

**Issue by realestatebroki** [mekanism/Mekanism#7576] opened 2022-08-12 10:07 UTC
### Issue description

Hey Guys,

So I tried to upgrade my 4 QIO Drives to the ultimate QIO Drive and when I draged all of my already used QIO Drives into the Crafting Grid, the Server crashed.

Now my whole QIO Drives are stuck in the Portable QIO Monitor and I'm not able to open the Monitor.

### Steps to reproduce

1. Take out your used QIO Drives
2. Drag them into the Crafting Grid of your Portable QIO Monitor
3. Server crashes
4. Can't use your Portable Monitor anymore
5. QIO Drives are in the Monitor
[Logs.txt](https://github.com/mekanism/Mekanism/files/9315514/Logs.txt)
 

### Minecraft version

1.19.0 (No longer being developed)

### Forge version

40.1.68

### Mekanism version

10.3.2 (Latest)

**Comment by pupnewfster** [comment] 2022-08-12 12:52
1. You are not on 1.19 you are on 1.18.2 based on your forge version
2. That Mekanism version you claim to be on only supports 1.19.1 and 1.19.2 it doesn't even support 1.19.0 like you claim you are on
3. Which makes this a duplicate of #6837 and your best bet likely is to transfer the world to single player where there isn't limits finish the crash/remove the items from the portable dashboard and then transfer the world back to the server.

**Closed** 2022-08-12 12:54 UTC
Labels: duplicate, Old MC, Format not followed, 1.18
