### ISSUE TITLE
Some of our texture sizes don't work well with mipmapping

### ISSUE THREAD

**Issue by josephcsible** [mekanism/Mekanism#4920] opened 2018-01-24 03:57 UTC
A lot of our textures are odd sizes that look ugly when you're using mipmapping. Forge gives this warning about each of them at startup:

Texture mekanism:textures/X with size X will have visual artifacts at mip level 4, it can only support level X. Please report to the mod author that the texture should be some multiple of 16x16.

**Comment by pupnewfster** [comment] 2020-02-05 02:03
While #5834 is a duplicate of this I am closing this in favor of that one as it is a more detailed report.

**Closed by pupnewfster** 2020-02-05 02:03 UTC
