### ISSUE TITLE
Mekansim has a mixin conflict with refined storage

### ISSUE THREAD

**Issue by Rubyz67** [mekanism/Mekanism#7405] opened 2022-01-30 20:06 UTC
### Issue description

When loading up the game it crashes while intizling 

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.23

### Mekanism version

10.1.1 (Latest)

### Other relevant versions

Refind Storage Latest
Refined Storage Addons Latest
Mekansim Addons Lastest

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Rubyz67/0b5d1c2c30e3390d56531eda71e920d3

**Comment by pupnewfster** [comment] 2022-01-30 20:07
Mekanism doesn't have any mixins or coremods (aside from using forge's AccessTransformer system). Mekanism addons is not our mod it is a third party addon that for SOME reason decided to name it addons when we already have Mekanism Additions as one of our official modules

**Comment by Seniorendi** [comment] 2022-01-30 20:07
KInda a duplicate of https://github.com/mekanism/Mekanism/issues/7404

**Closed** 2022-01-30 20:07 UTC

**Comment by Rubyz67** [comment] 2022-01-30 20:13
its not a duplicate'

**Comment by Rubyz67** [comment] 2022-01-30 20:13
i dont have backpacker mod

**Comment by Seniorendi** [comment] 2022-01-30 20:15
Read the reason from pup
And read some comments in #7404

**Comment by Rubyz67** [comment] 2022-01-30 20:20
it worked
