### ISSUE TITLE
[1.12] something (I'm assuming a mod) is causing Mek to cap it's power at 2^31.

### ISSUE THREAD

**Issue by SubjectHawk66** [mekanism/Mekanism#5678] opened 2019-11-14 22:55 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I run a server for ATM Remix with some friends and I added some mods. I need help isolating the issue that cropped up. When someone went to use an induction matrix it capped at 2.14G. I've read up a little and someone had a similar issue but they knew what caused it. All I know is somehow the API is capping out at the maximum for rf instead of tesla.

#### Steps to reproduce:
1. Well I'm trying to figure out but I installed pam's, dragonmounts2 and ceramics. It also could've been that I had railcraft on the server at one point but it didn't work properly so I deleted it.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2844
**Mekanism:** 9.8.1.383
**Other relevant version:** Latest versions of railcraft, ceramics, pam's, and dragonmounts

**Comment by pupnewfster** [comment] 2019-11-14 22:57
Update mekanism this is a duplicate of #5609 and only is a bug in the display number not in the amount of power it can actually store.

**Closed by pupnewfster** 2019-11-14 22:57 UTC
