### ISSUE TITLE
When in bucket mode tanks does not consume scooped liquid blocks.

### ISSUE THREAD

**Issue by Vany** [mekanism/Mekanism#5854] opened 2020-02-06 20:18 UTC
this version of minecraft https://www.curseforge.com/minecraft/modpacks/all-the-mods-5

and here is a demo  https://www.youtube.com/watch?v=ChT9pSdDsPY (in the begining of video)

*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When in bucket mode tanks does not consume scooped liquid blocks.

#### Steps to reproduce:
1. switch tank to bucket mode
2. scoop some lava
3. profit

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.42
**Mekanism:** 1.15.1-9.9.3.394

**Comment by pupnewfster** [comment] 2020-02-06 20:21
Please don't just delete the format as it does have useful information we need in it. What version of Mekanism is this on, as I am not going to download a modpack just to see what version of Mekanism it includes, and a few alphas ago I did fix some issues about how the fluid tanks act in bucket mode.

**Comment by Vany** [comment] 2020-02-06 20:26
Ok! thanx!! 
I can check it only on weekend ... but it will be great.

**Comment by pupnewfster** [comment] 2020-02-06 20:30
Ya this issue is a duplicate of #5802 and got fixed in Mekanism 9.9.5.

**Closed by pupnewfster** 2020-02-06 20:30 UTC
Labels: Format not followed, Waiting Feedback
