### ISSUE TITLE
[1.15.2] Rotary Condensentrator not accepting water

### ISSUE THREAD

**Issue by Zoratan** [mekanism/Mekanism#5823] opened 2020-01-28 18:03 UTC
Issue description:

Rotary Condensentrator does not accept water, singleplayer and dedicated Server.
Looks like there is no Water Vapor (replaced by Steam) gas tank in creative.

Even tried to set the water pipe to push. 
It connects but the condensentrator does not take anything in.
Condensentrating steam produces Liquid steam...

Version (make sure you are on the latest version before reporting):

Forge: forge-1.15.2-31.0.1
Mekanism: 9.9.5

**Comment by pupnewfster** [comment] 2020-01-28 18:14
Opened up a 1.12 instance and seems that I hadn't actually noticed mekanism had something called "water vapor" (maybe that is just the localized name it was using), I will try to look into this at some point and figure out what functionality I accidentally killed off.

**Comment by term2112** [comment] 2020-01-28 18:17
I can confirm in is in 9.9.6

![image](https://user-images.githubusercontent.com/41069911/73292655-6f07b300-41d0-11ea-9005-ef053178fcea.png)

![image](https://user-images.githubusercontent.com/41069911/73292707-85157380-41d0-11ea-8c8e-43cfe7cd54a8.png)

**Comment by winsrp** [comment] 2020-01-29 16:45
I'm just getting to know this mod, and I can confirm this on 1.5.2, What broke is ore processing for tier 4 (5X)

[https://wiki.aidancbrady.com/w/images/aidancbrady/a/a2/Mekanism-flowchart-v7-simplified.png](url)

**Comment by winsrp** [comment] 2020-01-29 21:57
Steam seems to be the most common form of this gas (I mean... water vapor is steam XD), so might as well just make it steam which would also make it compatible with other mods,, but also I think you have other machines that make steam right? So would that break this loop, or would it actually add an alternative for it?

**Comment by Zoratan** [comment] 2020-01-29 22:35
> 
> 
> Steam seems to be the most common form of this gas (I mean... water vapor is steam XD), so might as well just make it steam which would also make it compatible with other mods, [...]

**Comment by pupnewfster** [comment] 2020-01-29 23:31
The reason I for now just added water vapor additionally instead of removing one of the types of steam. Is I don't want to have to go through/figure out currently the implications of being able to get steam via just the condensentrator instead of having to get it via other means. Eventually we will figure out how we want to handle the production/usage of steam and water vapor.

**Comment by winsrp** [comment] 2020-01-30 01:47
looking around in the wiki it seems that the other thing that produces steam is the Thermoelectric Boiler, which is far more expensive in terms of materials, and the output is much greater, that said, I don't think nothing would break, the Rotary condensentrator works as a small supplier of steam for the ore setup, which is just what you need, and the Thermoelectric Boiler is something bigger for the turbine, which could eventually replace the condensentrator as the steam provider for the setup, but it still has lots more uses so I think from a user perspective that its fine to change it to making just steam instead of steam with another name.

Also checking the wiki:

Water Vapor
Made by:

Rotary Condensentrator using Water
Used by:

Chemical Infuser to make Sulfuric Acid -> [the one on this setup for ore production]
Chemical Injection Chamber with Dirt to make Clay -> [the only other use ¯\_(ツ)_/¯ ]

And that's about it... so I think that for the actual uses it has... steam would work just fine.

**Comment by pupnewfster** [comment] 2020-01-30 01:52
Closing this for now as it is "fixed" in 9.9.7 which is released and on curseforge. I will end up looking back at this when I eventually look more into how things will actually be handled.

**Closed by pupnewfster** 2020-01-30 01:52 UTC
Labels: 1.15, Fixed in dev, bug

**Comment by closeshot** [comment] 2020-03-07 13:07
I found that it accepts water now version 1.15.2 9.9.14.406 however it is not producing water vapor

**Comment by pupnewfster** [comment] 2020-03-07 14:08
#5940
