### ISSUE TITLE
I have a Minecraft world with Mekanism stuck on world loading screen

### ISSUE THREAD

**Issue by TnTCreeperLpr** [mekanism/Mekanism#6842] opened 2021-01-04 19:07 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I have a Minecraft world with Mekanism stuck on world loading screen and I have isolated it to the Mekanism mod.

#### Steps to reproduce:
1.Download Mekanism-1.16.4-10.0.18.445
2.Run Minecraft forge 1.16.4
3.Make new world
4.Then it says Reading world data with a dirt screen
5.Then it goes to a dirt screen with no words then I have to close it

#### Version (make sure you are on the latest version before reporting):
Forge:1.16.4-forge-35.1.28
Mekanism:Mekanism-1.16.4-10.0.18.445 
[latest.log](https://github.com/mekanism/Mekanism/files/5766491/latest.log)

**Comment by Seniorendi** [comment] 2021-01-04 19:17
I play with 1.16.4 forge and Mekanism 10.0.18. 
How long did you wait?

**Comment by TnTCreeperLpr** [comment] 2021-01-04 19:20
Wait for what?

**Comment by Seniorendi** [comment] 2021-01-04 19:26
That the world loads

**Comment by Seniorendi** [comment] 2021-01-04 19:26
I usually wait 1-3 minutes

**Comment by TnTCreeperLpr** [comment] 2021-01-04 19:26
I have been waiting for about 5 min

**Comment by TnTCreeperLpr** [comment] 2021-01-04 19:27
Game says Not Responding

**Comment by Seniorendi** [comment] 2021-01-04 19:27
You didn't send a log. Could you do that?

**Comment by TnTCreeperLpr** [comment] 2021-01-04 19:28
yes... But I have not done it in a while how would I  go about it

**Comment by TnTCreeperLpr** [comment] 2021-01-04 19:34
https://pastebin.com/baFu77zc

**Comment by TnTCreeperLpr** [comment] 2021-01-04 19:40
[latest.log](https://github.com/mekanism/Mekanism/files/5766480/latest.log)

**Comment by Seniorendi** [comment] 2021-01-04 20:11
```
Encountered an unexpected exception
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file Mekanism/general.toml of type SERVER for modid mekanism

```
This is weird. Which OS(linux, windows, ...) do you use?

**Comment by TnTCreeperLpr** [comment] 2021-01-04 20:11
Windows 10

**Comment by Seniorendi** [comment] 2021-01-04 20:14
I don't know what the problem is.
We should ask @pupnewfster (Sorry for the ping, if i shouldn't ping you)

**Comment by TnTCreeperLpr** [comment] 2021-01-04 20:15
OK thanks

**Comment by pupnewfster** [comment] 2021-01-04 20:39
Not sure offhand, though I vaguely recall mention at one point of a forge bug (or bug that is upstream of forge) that causes configs to not load properly. What I would recommend is making a backup of your configs (at first just Mekanism's, though if it doesn't help all of them) and then deleting the configs and letting them regenerate and see if it progresses further. If you end up needing to try it with all configs and just deleting the Mekanism ones is not good enough, keep in mind some of the configs are in the `configs` folder and some are inside a folder in the world folder (I forget the exact path name, given I have Mekanism redirect all our configs to the `configs` folder for convenience).

**Comment by TnTCreeperLpr** [comment] 2021-01-04 20:57
It worked thanks so much

**Comment by pupnewfster** [comment] 2021-01-04 21:58
Going to go ahead and close this then, and just chalk it up to the forge/night config bug where configs rarely become "corrupted" and can't properly be read.

**Closed by pupnewfster** 2021-01-04 21:58 UTC
