### ISSUE TITLE
Can't craft items in QIO panel

### ISSUE THREAD

**Issue by Proxwian** [mekanism/Mekanism#7694] opened 2023-01-04 09:45 UTC
### Issue description

Looks like player can't craft items from other mobs (also mod Mekanism Generators) in QIO panel
![image](https://user-images.githubusercontent.com/31781674/210527285-29419eea-b2a5-4f02-8675-d58bcaa56d6e.png)
![image](https://user-images.githubusercontent.com/31781674/210527340-2cf66c58-9368-423c-90d0-6a247ea928d5.png)
![image](https://user-images.githubusercontent.com/31781674/210527393-f00796cd-b1bd-40e4-8126-83c5aa169a86.png)

### Minecraft version

1.18.2

### Forge version

40.1.92

### Mekanism version

Older

### Other relevant versions

10.2.5

**Comment by pupnewfster** [comment] 2023-01-04 17:56
I am unable to reproduce this in 1.19. What mod is the steel you are trying to use from? And if you are using a prebuilt modpack what is the name of it.
![image](https://user-images.githubusercontent.com/1203288/210619044-9d8ebe65-7a17-4f7e-8f56-20ffeaaac6dd.png)

**Comment by Proxwian** [comment] 2023-01-04 17:59
I guess this was because of RecipeStages mod, also it's 1.18.2 and OxFORTPACK x256 6.2 modpack

**Comment by pupnewfster** [comment] 2023-01-11 03:22
Ah yeah, it is due to recipe stages. Talked with jared some and got him to add a few methods to recipe stage's API and in 1.19 this will be fixed by us making use of those changes.

**Closed** 2023-01-30 19:54 UTC
Labels: Fixed in dev, Not reproducible, Old MC, 1.18, 1.19
