### ISSUE TITLE
Portable Teleporter owner:null

### ISSUE THREAD

**Issue by youngchan01** [mekanism/Mekanism#7110] opened 2021-04-15 06:59 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
If you join a server using localhost, after owning a portable teleporter, it will only bind its owner to you for that session, once  disconnected and reconnected again, the Portable teleporter will have its owner set to: null

#### Steps to reproduce:
1. Host a server on the same device that runs your client
2. Connect to the server using the IP: localhost
3. have a Portable Teleporter, set its owner to yourself
4. Disconnect and Reconnect to your server
5. Portable Teleporter now has its owner set to null

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.16.5-36.1.0
**Mekanism:** Mekanism-1.16.5-10.0.21.448
**Other relevant version:** N/A

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment] 2021-04-15 09:36
Are you using offline server mode? That is inherently incompatible with ownership (even if your client is logged in)

**Comment by youngchan01** [comment] 2021-04-15 18:17
Yes, however this does not seem to.be a problen for other players

**Comment by pupnewfster** [comment] 2021-04-17 21:53
I need to look into this further but from my very initial investigation I think in theory placing a security desk might work as a workaround and make any future claimed teleporters not have this issue.

**Comment by DanteAyagawe** [comment] 2021-08-11 06:17
I reproduced this issue when I copied a whole curseforge folder to another pc because the other doesn't have sounds, the sound got fixed, but the portable teleporter now gets nulled when saving the game and then loading it again, this issue doesn't affect other players other than the pc that has the copied files.

Was playing Enigmatica 6

**Comment by Seniorendi** [comment] 2021-08-11 12:17
DanteAyagawe. 

Take a look at the labels. There is a `Fixed in dev` label. So this is already fixed, but you need to wait until Mekanism is released.

**Closed** 2021-12-22 19:42 UTC
Labels: bug, confirmed, needs review, Fixed in dev, 1.16
