### ISSUE TITLE
Turbine doesn't form when update from 425 to 431 (1.16.1)

### ISSUE THREAD

**Issue by idonhavename** [mekanism/Mekanism#6442] opened 2020-08-09 16:37 UTC
When I update from 10.0.8.425 to 10.0.8.431, everything is normal except the turbine, It just stops spinning, can't click, even I rebuild it, still doesn't work.
Forge: 32.0.107
Mekanism: 10.0.8.431
I'm so dumb that I accidentally press closed on the last one
![2020-08-09_23 00 58](https://user-images.githubusercontent.com/52009098/89737154-08c1ee00-da99-11ea-9159-fff423f95f91.png)
Even I close that hole, Multiblock doesn't form, no particles.

**Comment by pupnewfster** [comment] 2020-08-09 17:14
Duplicate of #6441 (your own issue) the turbine is too tall

**Closed by pupnewfster** 2020-08-09 17:14 UTC
