### ISSUE TITLE
Mekasuit Does Not Render

### ISSUE THREAD

**Issue by PessimisticBastard** [mekanism/Mekanism#6789] opened 2020-12-17 01:57 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Mekasuit is not rendering, just shows empty space

#### Steps to reproduce:
1. Put on Mekasuit
2. Player model becomes invisible

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.13
**Mekanism:** 10.0.18.445
**Other relevant version:** Minecraft 1.16.4

**Comment by Seniorendi** [comment] 2020-12-17 01:59
I used the Mekasuit with Mekanism 10.0.17, and it works. Maybe it's a issue with 10.0.18.

**Comment by pupnewfster** [comment] 2020-12-17 02:00
Do you have optifine or other very hacky rendering mods and if so does removing it fix it?

**Comment by PessimisticBastard** [comment] 2020-12-17 02:00
I do not have any performance enhancement mods. The suite was rendering correctly before the update.

**Comment by PessimisticBastard** [comment] 2020-12-17 02:10
I just tested rolling back Mekanism to version 10.0.17.444. The suit is rendering correctly.

**Comment by Diamantino-Op** [comment] 2021-01-03 19:32
Maybe i know the problem, there are multiple errors in the rendering code and i found it.
It's this function in the ClientRegistration class:
private static <T extends LivingEntity, M extends BipedModel<T>, A extends BipedModel<T>> void addCustomArmorLayer(LivingRenderer<T, M> renderer) {
        for (LayerRenderer<T, M> layerRenderer : new ArrayList<>(renderer.layerRenderers)) {
            //Only allow an exact match, so we don't add to modded entities that only have a modded extended armor layer
            if (layerRenderer.getClass() == BipedArmorLayer.class) {
                BipedArmorLayer<T, M, A> bipedArmorLayer = (BipedArmorLayer<T, M, A>) layerRenderer;
                renderer.addLayer(new MekanismArmorLayer<>(renderer, bipedArmorLayer.modelLeggings, bipedArmorLayer.modelArmor));
                break;
            }
        }
    }
These are the errors:
renderer.layerRenderers
bipedArmorLayer.modelLeggings
bipedArmorLayer.modelArmor

The variables are private in the main class with the new forge update and this gives errors.

The same problem is in the rendering functions of the other armor pieces too in the rendering function:
@Override
    public void render(@Nonnull MatrixStack matrix, @Nonnull IRenderTypeBuffer renderer, int light, int overlayLight, float partialTicks, boolean hasEffect,
          LivingEntity entity, ItemStack stack) {
        if (isChild) {
            matrix.push();
            float f1 = 1.0F / childBodyScale;
            matrix.scale(f1, f1, f1);
            matrix.translate(0.0D, childBodyOffsetY / 16.0F, 0.0D);
            renderMekaSuit(matrix, renderer, light, overlayLight, partialTicks, hasEffect, entity);
            matrix.pop();
        } else {
            renderMekaSuit(matrix, renderer, light, overlayLight, partialTicks, hasEffect, entity);
        }
    }

Problems:
childBodyScale
childBodyOffsetY

And i think there is another error, but i need to search it.

P.S. : i tried to fix but i need to create a custom render system for that.

**Comment by pupnewfster** [comment] 2021-01-03 20:38
Those variables are not private with Mekanism, we AT them, they are only a problem if another mod like optifine goes ahead and overwrites entire classes, if that is what the issue is and there are access errors in the log I am going to go ahead and close this.

**Comment by Diamantino-Op** [comment] 2021-01-03 20:40
Well, how i can solve the problem of the private variables, then?

**Comment by pupnewfster** [comment] 2021-01-03 20:52
By setting up the forge project the same as any other forge project so that it can apply the ATs. This isn't the place for support with figuring out how to setup a forge mod.

**Comment by pupnewfster** [comment] 2021-01-28 20:39
Not able to reproduce this best guess is there is some other mod you have installed that is breaking things. Providing a modlist may help or even better testing a few of your mods at a time with Mekanism also installed and seeing when the mekasuit stops rendering.

**Closed** 2021-02-09 04:53 UTC
Labels: 1.16, Not reproducible, Waiting Feedback, interaction

**Comment by DeleteMetaInf** [comment] 2022-08-27 21:39
I’m having the same issue. The Meka-Suit does not render on my player, and worse, it makes my hand invisible, even in first-person mode (when empty-handed), when using the MekaSuit bodyarmour, which is annoying.

I’m using the latest version of Mekanism for 1.18.2, 10.2.5.

**Comment by NeonWizard** [comment] 2022-09-07 07:27
Same issue of the HUD not rendering, and I'm not using Optifine.

Minecraft version: 1.16.5
Mekanism version: 10.1.2.457

**Comment by TwixWolf** [comment] 2022-09-07 21:27
> I’m having the same issue. The Meka-Suit does not render on my player, and worse, it makes my hand invisible, even in first-person mode (when empty-handed), when using the MekaSuit bodyarmour, which is annoying.
> 
> I’m using the latest version of Mekanism for 1.18.2, 10.2.5.

Same issue here, I assume we will have to open a new ticket for this issue.

**Comment by DeleteMetaInf** [comment] 2022-09-08 01:53
This is an issue caused by Oculus. Disabling shaders solves it. Reported it [here](https://github.com/Asek3/Oculus/issues/170); I hope they fix it.

**Comment by SparkyTD** [comment] 2023-07-14 22:05
If the issue is as simple as the MekaSuit not being rendered by Oculus, then as a temporary workaround it would be better to render both the original player model and the suit, or at least add a config option for it. That way even if the suit is invisible, the original plyer model is still rendered, which is better than nothing being rendered at all.
