### ISSUE TITLE
Machines disappear 

### ISSUE THREAD

**Issue by MattKenney11** [mekanism/Mekanism#6298] opened 2020-07-11 18:07 UTC
Whenever me or my friend log out and log in the most recent machines we place disappear and we are left with this error in console
[m[1;31m[10:59:59] [Server thread/ERROR] [Mekanism/]: Different orphan transmitter was already registered at location! [Coord4D: 1188, 77, 1130, dim=ResourceKey[minecraft:dimension / minecraft:overworld]]
[m[1;31m[10:59:59] [Server thread/ERROR] [Mekanism/]: Different orphan transmitter was already registered at location! [Coord4D: 1187, 77, 1130, dim=ResourceKey[minecraft:dimension / minecraft:overworld]]

the same goes for if we go into the nether and back. Please help i'm enjoying the mod but i'm too scared to progress due to losing resources, thankyou!

**Comment by pupnewfster** [comment] 2020-07-11 18:08
First I don't think this has to do with Mekanism and some other mod is causing "ghost chunk loading" making chunks load/unload relatively quickly. Secondly what version of Mekanism is this even on.

**Comment by MattKenney11** [comment] 2020-07-11 18:15
Citadel-1.2.0 
Forge version: 1.16.1 32.0.63
Mod version: 1.16.1-10.0.0.423
SSP/SMP: SMP
Other Mods: AppleSkin-mc1.16.1-forge-1.0.14
citadel-1.2.0
cloth-config-forge-4.0.1
CTM-MC1.16.1-1.1.0.1
Ding-1.16.1-1.1.0
FastLeafDecay-v23
ironchest-1.16.1-11.0.1
ironshulkerboxes-1.16.1-5.0.1
jei-1.16.1-7.0.0.6
light-overlay-5.4.0
Mekanism-1.16.1-10.0.0.423
MekanismAdditions-1.16.1-10.0.0.423
MekanismGenerators-1.16.1-10.0.0.423
MouseTweaks-2.13-mc1.16.1
rats-6.0.3-1.16.1
StorageDrawers-1.16.1-8.0.0
theoneprobe-1.16-3.0.0-beta
valhelsia_structures-16.0.1
Waystones_1.16.1-7.0.1
Description: When placing machines in chunks after unloading chunk and coming back the block deletes and it is reproduce able, I tested it 8 times and it happened every time. 

Sorry new to github

**Comment by ZeWolfTah** [comment] 2020-07-11 20:28
MattKenney11's friend here. I've been tinkering around to test what might be causing the bug, and after some tests I have results. The bug is not Mekanism related but seems to be world related. Console filtering was hiding some crucial details about the issues occurring and previously only showed the Mekanism orphan transmitter error. After unfiltering the console the bug now seems to be related to a null pointer causing chunk saving to fail for hundreds of chunks as shown in this example snippet here: https://pastebin.com/Bc1TKBNc

Would you happen to know of a fix or where this should be reported since it's likely not Mekanism related?

**Comment by pupnewfster** [comment] 2020-07-11 20:36
I would backup your world, and then try loading the world (with a couple mods removed) and seeing if you can reproduce the issue, and keep on removing a couple more mods until you track down which one is actually causing the world to not save.

**Comment by ZeWolfTah** [comment] 2020-07-11 20:43
Thank you for the swift response! My edit must have been too late to be noticed, but I have made some backups and tried exactly that. The issue still occurs even with no mods on the forge server which confirms it's world related. 
I'm also unable to replicate the issue on a new world even after attempting to place the exact machines MattKenney11 placed right before the issue occurred, so I'm at a loss for what caused it.
Do you think this bug would be best taken to the forge bug reports?

**Comment by pupnewfster** [comment] 2020-07-11 20:47
Maybe that or the forge forums. Though given it is continuing to have that error with no mods (including mekanism) installed, I am going to go ahead and close this as it seems unlikely it is Mekanism related then.

**Closed by pupnewfster** 2020-07-11 20:47 UTC
Labels: 1.16, needs review
