### ISSUE TITLE
1.15.2 Mekanism version 9.10.1.414 pipe/cable textures become disconnected.

### ISSUE THREAD

**Issue by feteryeeter420** [mekanism/Mekanism#6094] opened 2020-04-23 21:22 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Can either walk away from where area is and pipe textures break but the energy/fluids flowing will stay connected, or can happen randomly and do the same thing.

#### Steps to reproduce:
1. Afk for 5 min, or go at least 1 chunk away
2. come back and have to mine and put back pipe/cable to fix
3. chance of other pipes in base messing up when you mine and replace pipe/cable

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.47
**Mekanism:** 9.10.1.414
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
![2020-04-23_16 12 21](https://user-images.githubusercontent.com/64229907/80150788-9a572f80-857e-11ea-9c22-2850854011b6.png)

**Comment by feteryeeter420** [comment] 2020-04-23 21:30
![2020-04-23_16 30 10](https://user-images.githubusercontent.com/64229907/80151479-c1623100-857f-11ea-8d8f-484789e3f816.png)
another picture of pipes getting messed up in a bigger part of my base

**Comment by Tahakk** [comment] 2020-04-23 22:07
looks like dupe of #5922

**Comment by thiakil** [comment] 2020-04-23 22:14
Do you have immersive portals installed?

**Comment by feteryeeter420** [comment] 2020-04-23 23:23
> Do you have immersive portals installed?

yes I do. i'll try and disable it for half an hour and see what happens. love the mod but if it keeps on breaking the pipes/cables like this its got to go lol

**Comment by ocram9** [comment] 2020-04-23 23:27
The immersive portal devs have attempted to fix this incompatibility but apperently its not fully fixable: https://github.com/qouteall/ImmersivePortalsModForForge/issues/49

**Closed** 2020-04-23 23:50 UTC
Labels: 1.15, Not Mekanism, duplicate

**Comment by thiakil** [comment] 2020-04-24 00:27
> but apparently its not fully fixable

Doubtful
