### ISSUE TITLE
Robit Ticking Entity

### ISSUE THREAD

**Issue by kornfan6589** [mekanism/Mekanism#5970] opened 2020-03-15 22:28 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server reports Robit as a ticking entity

#### Steps to reproduce:
1. Join server
2. Load a chunk with a Robit
3. Server crashes

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.23
**Mekanism:** 9.9.16.408
**Other relevant version:** 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/LwAqN3QY

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment] 2020-03-15 22:32
This seems to be due to the changes I made in 9.9.16 with saved data. If you downgrade to 9.9.15, pickup your robit you should be able to upgrade back to 9.9.16 without it causing any crashes.

I am leaving this open for now, as I am unsure if it is intended for robit's to ever be able to not have an owner (in which case this is a bug), however if they are always supposed to have an owner (which I believe is the case), then this is just an alpha upgrade artifact. I will leave it up to @aidancbrady to say which of these two it is.

**Comment by kornfan6589** [comment] 2020-03-15 22:54
So as i figured, that did indeed fix it. however it appears all players have lost ownership of all things with that trait. so many items must be broken down and rebuilt. No longer a bug then i suppose, just the cost of running an alpha mod. Wanted to make the issue so others upgrading are aware.

**Comment by pupnewfster** [comment] 2020-03-19 20:15
Closing this as aidan confirmed to me that robit's should always have an owner, so the crash is only due to the invalid state from breaking changes occurring during an alpha.

**Closed by pupnewfster** 2020-03-19 20:15 UTC
Labels: 1.15, Mekanism
