### ISSUE TITLE
TPS lag stops fusion

### ISSUE THREAD

**Issue by alaestor** [mekanism/Mekanism#6184] opened 2020-05-25 23:59 UTC
#### Issue description:
TPS lag causes reactor shutdown due to insufficient fuel transfer. Occurs even when properly chunk-aligned, chunk-loaded, and supplied from high grade pipes with an ample fuel source.

#### Steps to reproduce:
1. Setup server environment; more consistently reproduced on servers with limited CPU resources.

2. Build a sufficiently supplied 98 injection rate fusion reactor and ignite it. In my testing I used dual-gas injection with elite pipes and ultimate tanks. I suspect lower injection rates are more tolerant due to the internal buffer, but they aren't immune.
3. Keep the reactor loaded. To rule out possible issues with chunkloading I had someone with it and watching the fuel info screen.

4. Rapidly generate chunks to overload the server, causing "can't keep up" warnings, ideally with high tick counts. I accomplished this by going to an unused dimension and moving very quickly with an emerald jetpack from another mod.

5. While the server lags behind, the reactor will have run out of fuel (confirmed by signal out) and shut down. I suspect the drop in fuel can sometimes only be only for an instant.

#### Version:
**Forge:** 31.1.87
**Mekanism:** Mekanism-1.15.2-9.10.5.418.jar
**Other relevant version:** modpack FTB Omnia 1.4.0

#### ...
A screenshot of the [server output](https://imgur.com/3Ti6r61) during my test, showing that the server was running at least 42 ticks behind (I don't own the server and likely wont be able to provide any additional information about its specs)

**Comment by pupnewfster** [comment] 2020-05-26 00:04
Duplicate of #6178. Free feel to attempt my suggestion here: https://github.com/mekanism/Mekanism/issues/6178#issuecomment-633575178 and report back if performant is indeed the cause of the issue.

**Closed by pupnewfster** 2020-05-26 00:04 UTC
Labels: duplicate
