### ISSUE TITLE
crash server caused by mekanism using the modpack valhesia 2 [1.15.2]

### ISSUE THREAD

**Issue by Azkalaak** [mekanism/Mekanism#6550] opened 2020-09-12 15:54 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
we are playing on a server in 1.15.2 using the valhesia 2 modpack (containing mekanism). it crashes randomly (sometimes not, sometimes after 10 minutes, sometimes after 6 hours) with the following error message:

```
[Server thread/ERROR] [Mekanism/]: Stack size changed by a different amount (-63857) than requested (957).

java.lang.Exception: null

	at mekanism.common.util.MekanismUtils.logMismatchedStackSize(MekanismUtils.java:108) [?:?]

	at mekanism.common.transmitters.grid.FluidNetwork.absorbBuffer(FluidNetwork.java:130) [?:?]

	at mekanism.api.transmitters.DynamicNetwork.commit(DynamicNetwork.java:81) [?:?]

	at mekanism.api.transmitters.TransmitterNetworkRegistry.commitChanges(TransmitterNetworkRegistry.java:190) [?:?]

	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:113) [?:?]

	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:106) [?:?]

	at net.minecraftforge.eventbus.ASMEventHandler_1013_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) [?:?]

	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.2.0-service.jar:?]

	at com.performant.coremod.event.EventHandlerB.post(EventHandlerB.java:154) [?:1.15-3.10m]

	at com.performant.coremod.event.EventHandlerB.onPostServerTick(EventHandlerB.java:98) [?:1.15-3.10m]

	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:536) [?:?]

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:825) [?:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

[12Sep2020 01:52:34.560] [Netty Epoll Server IO #4/INFO] [codechicken.lib.config.ConfigSyncManager/]: Skipping config sync, No mods have registered a syncable config.

[12sept.2020 01:52:35.560] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception

java.lang.NullPointerException: null

	at it.unimi.dsi.fastutil.objects.ObjectOpenHashSet$SetIterator.next(ObjectOpenHashSet.java:501) ~[?:?]

	at mekanism.api.transmitters.DynamicNetwork.commit(DynamicNetwork.java:65) ~[?:?]

	at mekanism.api.transmitters.TransmitterNetworkRegistry.commitChanges(TransmitterNetworkRegistry.java:190) ~[?:?]

	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:113) ~[?:?]

	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:106) ~[?:?]

	at net.minecraftforge.eventbus.ASMEventHandler_1013_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]

	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]

	at com.performant.coremod.event.EventHandlerB.post(EventHandlerB.java:154) ~[?:1.15-3.10m]

	at com.performant.coremod.event.EventHandlerB.onPostServerTick(EventHandlerB.java:98) ~[?:1.15-3.10m]

	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:536) ~[?:?]

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:825) ~[?:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

[12sept.2020 01:52:35.577] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /var/directory_serv/minecraft_198911/./crash-reports/crash-2020-09-12_01.52.35-server.txt

[12sept.2020 01:52:35.578] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
```

I don't have access to the crash log right now, so if needed I can provide it in the coming week.

#### Steps to reproduce:
1. I have no idea this happens randomly

#### Version:
**Forge:** 31.2.36
**Mekanism:** 9.10.9
**Other relevant version:** minecraft 1.15.2

**Comment by pupnewfster** [comment] 2020-09-12 18:42
Not really sure part of it may be caused by performant given that mod is known to do all sorts of weird things, but part of it may also just be due to fastutil having some concurrency related issues. I am going ahead and closing this though given we are currently only developing for 1.16 and I rewrote the majority of the transmitter system again to try and make this not be able to happen anymore, given I could never track down or reproduce it in 1.15 myself.

**Closed by pupnewfster** 2020-09-12 18:42 UTC
