### ISSUE TITLE
Mekasuit doesn't render with shaders

### ISSUE THREAD

**Issue by 9Octopus** [mekanism/Mekanism#7743] opened 2023-02-23 13:51 UTC
### Issue description

When I deactivate shaders the Mekasuit renders in vanilla, but is invisible with shaders on both the player and armor stands. The Pneumaticcraft suit seems to operate similarly yet it renders fine.

I play in third person with shaders so this makes the Mekasuit unusable for the time being.

### Steps to reproduce

1. Using Oculus / Rubidium with any shaders
2. Wear Mekasuit or place it on an armor stand
3. Invisible

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.3

### Mekanism version

10.3.8 (Latest)

**Comment by SirEndii** [comment] 2023-02-23 13:54
Duplicate of #7729

**Comment by 9Octopus** [comment] 2023-02-23 13:58
I downloaded multiple extra settings for Oculus/Rubidium and none of the base settings or extra settings seemed to fix the issue

**Comment by SirEndii** [comment] 2023-02-23 13:59
iirc mekanism does not work on supporting shaders
The armor itself also uses shaders to render, this could be a reason why it does not work

**Comment by 9Octopus** [comment] 2023-02-23 14:02
So this issue will never be fixed?

**Comment by pupnewfster** [comment] 2023-02-23 14:31
There is nothing on our end we can reasonably do to fix your shader mods not supporting native vanilla and forge features that we use.

**Closed by pupnewfster** 2023-02-23 14:31 UTC

**Comment by KostromDan** [comment] 2023-11-14 02:32
> There is nothing on our end we can reasonably do to fix your shader mods not supporting native vanilla and forge features that we use.

Maybe you can just check if oculus shaders enabled, and if yes, automatically disable mekanism shaders. The way how it's works now is absolutely unacceptable. This problem was discussed with iris devs. They say it should be fixed on your side. Iris/Oculus won't support custom core shaders.
![Screenshot_20231114_052254_Discord](https://github.com/mekanism/Mekanism/assets/90044015/aa25bd8b-5e70-48a5-8f95-8d9d53795676)
At least 30% players playing mekanism, using shaders. So they having this problem. This is major issue.
The way how it looks now: Oculus dev says what it's mekanism problem, mekanism dev says its oculus problem...
This way this will never be fixed.
So if you can't/don't want to fix this, maybe you should just create workaround with disabling mekanism shaders if iris shaders applied.
I repeat, the way it is now absolutely unacceptable.
Too many players using shaders for not paying attention to this issue.

**Comment by colin094** [comment] 2024-05-26 22:31
I will say that this is more of a mekanism issue as this issue is known for every version of shaders that use any version oculus and optifine. Also your game will crash as late if you use optifine with mekanism. honestly it's a shame they're so reluctant to fix it as it only 4 items and such complex textures have easily been done by other mods in the past without issue. And its not like you can really enjoy Minecraft when every texture is stepped to hell after 20 blocks
