### ISSUE TITLE
critical exception packet issue.

### ISSUE THREAD

**Issue by border999** [mekanism/Mekanism#6160] opened 2020-05-13 18:20 UTC
#### Issue description: 
[latest.log](https://github.com/mekanism/Mekanism/files/4623820/latest.log)

#### Steps to reproduce:
1. unknown, possible just building a large energy multiblock from mekanism with Cubic Chunks installed. Did not happen instantly though, worked for some time before this issue occurred. 

**Forge:** 1.12.2-forge1.12.2-14.23.5.2847
**Mekanism:** Mekanism-1.12.2-9.8.3.390
**Other relevant version:** CubicChunks-1.12.2-0.0.1058.0-SNAPSHOT-all

**Comment by pupnewfster** [comment] 2020-05-13 22:36
Probably has to do with the networking having some assumption that is broken by Cubic Chunks. As networking has been rewritten in 1.15 and cubic chunks isn't out yet for it anyways I am closing this as I believe this is no longer an issue in 1.15.

**Closed by pupnewfster** 2020-05-13 22:36 UTC
Labels: Old MC, interaction

**Comment by Barteks2x** [comment] 2020-05-13 22:45
Cubic chunks is not involved here at all.

If this is not an mekanism issue, my only suspicions are hammercore and betterportals.

**Comment by pupnewfster** [comment] 2020-05-13 23:04
No idea then, only threw up saying cubic chunks might have been it due to the crash being in the `SimpleNetworkWrapper#sendToAllTracking` and vaguely recalling that cubic chunks changes things to make sure blocks above/below normal height limits are properly marked as being tracked. So ya if it isn't cubic chunks your best bet here border is to experiment with if it is the issue of one of the mods barteks listed.

**Comment by Zeitheron** [comment] 2020-05-13 23:12
Hammer Core is only found when passing the tile tick to the modded TE:
`com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)`
Don't think it's HammerCore's fault either.

**Comment by Barteks2x** [comment] 2020-05-13 23:55
I don't in fact currently change how `sendToAllTracking` works, which is actually an oversight. I don't think cubic chunks being the cause is possible. From networking point of view, it's not doing much more than a standard mod.
