### ISSUE TITLE
energy consumption is not well displayed

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5813] opened 2020-01-25 12:25 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When a factory is running, the consumption isn't always displayed
Not working for :
- Electrolytic separator
- (Maybe others but i didn't test all)

#### Steps to reproduce:
1.Place an electrolytic separator
2.Provide energy and materials
3.Look the info

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.0.1
**Mekanism:** 9.9.5
**Other relevant version:** mc 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Redstylt** [comment] 2020-01-26 11:42
Why is an enhancement ? not a bug ?

**Comment by pupnewfster** [comment] 2020-01-26 14:27
There are two things going on here, one the reason I marked it as an enhancement is that factories are not meant to always show their power usage because if they are not running or only some slots are running the power usage is different. The second thing is the bug that the electrolytic separator doesn't actually require power to run given I somehow broke it again.

**Comment by aidancbrady** [comment] 2020-02-27 20:21
The Electrolytic Separator now properly uses energy. The energy usage bar, as intended, shows how much energy is being consumed per tick.

**Closed by aidancbrady** 2020-02-27 20:21 UTC
Labels: 1.15, enhancement
