### ISSUE TITLE
Pipes, Cables, etc. have issues connecting to Thermal Series blocks

### ISSUE THREAD

**Issue by spukiitv** [mekanism/Mekanism#6817] opened 2020-12-26 10:41 UTC
#### Issue description:
When connecting storage block from Thermal Series [Flux Cell, Storage Cell, etc.], the pipes / cables wont connect when the cell face is configured; If a cell in configured while cables are connected to it, the cables will disconnect.

#### Process:
1 - Connect Universal Cable to Flux Cell
2 - Configure a not connected face

[Note: if you are having issues connecting the cable and cell, configure the cell face, then place cable]

#### Version:
**Forge:** 35.1.13
**Mekanism:** 10.0.18.445
**Thermal Series:** [Expansion]1.1.1, [Foundation] 1.1.2

**Comment by pupnewfster** [comment] 2020-12-26 14:24
My instinct is telling me this is a bug in thermal given our cables work with every other mod fine. My guess is they are properly invalidating the capability when a side config of theirs changes, but not exposing a new one. In terms of not connecting to a side that was not previously configured, my guess is they are not firing a neighbor update event to allow mods to know that something may have changed when it previously didn't expose a capability.

**Comment by KingLemming** [comment] 2020-12-28 00:59
We actually are - the question is if your cables automatically reconnect. That's what I'm not sure of.

**Comment by pupnewfster** [comment] 2020-12-28 01:37
Reopening this for now then so I remember to look into this in more detail when I get the chance.

**Comment by KingLemming** [comment] 2020-12-28 09:29
I've handled this on my end. I'm a bit worried that I may be "overcalling" state changes but it's definitely reliably working.

You do seem to have a small problem with double chests though, but it may be *entirely* on vanilla.

**Comment by pupnewfster** [comment] 2021-02-04 18:26
I am closing this then, as I have finally had a chance to look into this and the issue is with how forge is handling reviving caps that it invalidates it but still returns the old invalid cap from getCapability if called from an invalidation listener which then shows as not being present as it is invalid. I will keep #6822 open for now until I submit a PR to forge a bit later to fix this issue.

**Closed by pupnewfster** 2021-02-04 18:26 UTC
Labels: 1.16, Not Mekanism, interaction, needs review

**Comment by AraHaan** [comment] 2025-05-09 09:44
I am sorry to post here but it seems that the QE's are making the Sequential Fabricators unable to pull any items from say a chest when using it to power the block. The block *does* get power, but becomes useless. Luckily the modpack I am using has AE2 as well so I *could* use that instead for autocrafting.
