### ISSUE TITLE
Server Crash by using Mekanism

### ISSUE THREAD

**Issue by Midnight-Vortex** [mekanism/Mekanism#7728] opened 2023-02-06 13:09 UTC
### Issue description

Crashlog:  https://gist.github.com/Midnight-Vortex/fada7985e36e17e745473b0bf79a3ed9
Log: https://gist.github.com/Midnight-Vortex/7162f0b1d92024ae25dfcfb8ebfbeeab

### Steps to reproduce

ItemTags without silk touch
Gold
Diamond
Iron
Lapis
Redstone
Ancient Debris
Glowstone

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.4

### Mekanism version

10.3.7 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Midnight-Vortex/fada7985e36e17e745473b0bf79a3ed9

**Comment by SirEndii** [comment] 2023-02-06 13:12
You're not saying how it happened/what the steps to reproduce are
And what does "ItemTags without silk touch" have to do with this?

**Comment by pupnewfster** [comment] 2023-02-06 15:11
Duplicate of #7726

**Closed** 2023-02-06 15:12 UTC
