### ISSUE TITLE
Client Crash after Placeing Gas-burning Generator

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#6058] opened 2020-04-13 09:48 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Client crashes right after I placed a gas-burning generator from NEI on ground without any machines or transmitters near it.

#### Steps to reproduce:
1.Grab a Gas-burning Generator;
2.Place it down;
3.Crash!

#### Version (make sure you are on the latest version before reporting):
**Forge:1.15.2-forge-31.1.30** 
**Mekanism:Mekanism-1.15.2-9.9.19.411** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/Apot98/5d3859d90a7526775264f94a94d8361e

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment] 2020-04-13 09:55
> [gist / pastebin / etc link here. Please make sure that it isn't set to expire.]

**Comment by Apot98** [comment] 2020-04-13 10:00
> > [gist / pastebin / etc link here. Please make sure that it isn't set to expire.]

updated

**Comment by thiakil** [comment] 2020-04-13 10:18
duplicate of #6057

**Closed by thiakil** 2020-04-13 10:18 UTC
