### ISSUE TITLE
Repost: 1.12.2 Server Cables disconnect after rejoining.

### ISSUE THREAD

**Issue by Swiftcreepa** [mekanism/Mekanism#6132] opened 2020-05-04 17:25 UTC
I will clarify this time, both the hub and the main server are MC - 1.12.2.

Here is my issue again.

Issue description:
Hey, So I've noticed that whenever our server restarts and takes us to the hub ( Sponge Forge ) it always disconnects the cables when others and I reconnect. This doesn't happen when we go through the multiplayer menu and connect directly to the server. We do not have Mekanism on the hub server but we do have it on the modded server. We also have Mek. Generators and Tools as well on the server.

Steps to reproduce:
   Server Restarts > Forced into Hub Server
   Rejoin main server > Cables disconnected
   Have to replace all the cables.

Forge: 8.0.99.99 **
Mekanism-1.12.2-9.7.9.380**
MekanismGenerators-1.12.2-9.7.9.380
MekanismTools-1.12.2-9.7.9.380

**Comment by pupnewfster** [comment] 2020-05-04 17:26
Duplicate of #6131 

See: https://github.com/mekanism/Mekanism/issues/6131#issuecomment-623597182 for more details as to why it was closed

**Closed by pupnewfster** 2020-05-04 17:26 UTC
