### ISSUE TITLE
Obsidian Duplication

### ISSUE THREAD

**Issue by Dunkmania101** [mekanism/Mekanism#6955] opened 2021-02-03 13:16 UTC
#### Issue description:
I looked through the existing issues (open and closed) and couldn't find anyone reporting this, so I figured I'd go.

#### Steps to reproduce:
1. Grind obsidian into dust with an Enrichment Chamber.
2. Smelt each dust back into one obsidian each.
3. Profit?

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.5-36.0.14** 
**Mekanism: 1.16.4-10.0.19.446**

**Comment by TepperPepper666** [comment] 2021-02-03 16:23
Using just Mekanism I was unable to reproduce this, are you playing with any other mods? There does not appear to be a recipe to smelt a single obsidian dust into obsidian.
![2021-02-03_11 20 59](https://user-images.githubusercontent.com/46273243/106776500-1dc7a600-6612-11eb-8ec5-6ee7654594e6.png)

**Comment by pupnewfster** [comment] 2021-02-03 16:30
Thank you for confirming this Tepper, I didn't think we added a recipe but wanted to double check before commenting. Most mods at least in 1.12 had obsidian "crushing" type recipes produce four obsidian dust (in fact we had a PR that buffed ours to four dust from two to match the general consensus of what other mods were doing). So I am going to close this as it isn't really Mekanism's problem if another mod is handling this differently than what the normalized rates are, it is either on the other mod or the modpack dev to balance as they wish.

**Closed by pupnewfster** 2021-02-03 16:30 UTC
Labels: 1.16, To be confirmed
