### ISSUE TITLE
I crash Everytime i look at a Heat Generator

### ISSUE THREAD

**Issue by Mini-kun** [mekanism/Mekanism#6703] opened 2020-11-11 01:52 UTC
#### Issue description:
i Look Thouth to a heat Generator from lava or Fire and it Crash me (I have The One Probe install)

#### Steps to reproduce:
1.Have a Heat generator Cover in lava but the back site
2.Look touth the Lava/Fire to the Heat generator
3.*Crash*

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.41
**Mekanism:** 10.0.17.444
**Other relevant version:** 

I don't Relly have a Crash log

**Comment by pupnewfster** [comment] 2020-11-11 02:25
Duplicate of #6603 from what I can tell it is not on Mekanism's end it is either on TOPs end or more likely some other addon breaking TOP, as I have not been able to reproduce this the multiple times I have tried, both on and off of servers.

**Closed by pupnewfster** 2020-11-11 02:25 UTC
