### ISSUE TITLE
meka suit duplcation

### ISSUE THREAD

**Issue by D3s0l4ti0n** [mekanism/Mekanism#6807] opened 2020-12-22 23:07 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
use modification station to add mods shift right click the piece in the mod slot back to your armor slot it will make a copy and both pieces are still there 

#### Steps to reproduce:
1.place helmet or any other piece of meka suit in modification stations upgrade slot 
2.shift right click it and it will equip it and it will still be in the mod slot 
3.bioth pieces still are able to be take out and used [](url)

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.16.4-35.1.13
**Mekanism:** Mekanism-1.16.4-10.0.18.445
**Other relevant version:** atm6 1.16.4 1.3.4c

https://user-images.githubusercontent.com/28746626/102941358-22783680-4478-11eb-9665-612134149827.mp4

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment] 2021-01-31 18:38
I am not able to reproduce this. Like I believe you that it is happening especially with the video showing it but I can't reproduce this in either single player or on a dedicated server. My best guess is that one of the other mods in the pack (potentially one of the inventory transferring mods) is just creating a copy for no good reason of the item when it is shift right clicked instead of letting the container handle it. Your best bet is probably to report this to the ATM issue tracker and see if they can figure out which other mod they have installed is causing it.

**Closed by pupnewfster** 2021-01-31 18:38 UTC
Labels: 1.16, Not reproducible, interaction, moderateimportance
