### ISSUE TITLE
[1.15.2-9.9.10] Some Textures are broken

### ISSUE THREAD

**Issue by bloodyraoul** [mekanism/Mekanism#5881] opened 2020-02-17 14:46 UTC
With version 402, some machine textures doesnt appears anymore

![image](https://user-images.githubusercontent.com/16031618/74663729-9d0f6000-519c-11ea-983c-bc282db9a287.png)

**Comment by pupnewfster** [comment] 2020-02-17 15:03
1. Version 402 means next to nothing as it is just a number added by the build system. Granted we could look up what version number that corresponds to but if you insist on leaving a number out of the version number leave the fourth number out... not only provide it.
2. Could you please provide your latest.log file via pastebin or gist or something.

**Comment by bloodyraoul** [comment] 2020-02-17 15:10
sorry, it is version 1.15.2-9.9.10.402
I have found in logs :
Unable to load model: 'mekanism:block/transmitter/small/small' referenced from: mekanism:basic_universal_cable#waterlogged=true: java.lang.IllegalStateException: Model loader 'mekanism:transmitter' not found. Registered loaders: forge:obj, forge:composite, forge:multi-layer, forge:bucket, minecraft:elements

Unable to load model: 'mekanism:block/transmitter/large/logistical_transporter/transporter' referenced from: mekanism:basic_logistical_transporter#waterlogged=true: java.lang.IllegalStateException: Model loader 'mekanism:transmitter' not found. Registered loaders: forge:obj, forge:composite, forge:multi-layer, forge:bucket, minecraft:elements

Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/diversion_transporter
Unable to resolve texture reference: #missing in minecolonies:block/blockhutwarehouse
Unable to resolve texture reference: #missingno in mekanism:item/basic_pressurized_tube
Unable to resolve texture reference: #missing in minecolonies:item/blockwaypoint
Unable to resolve texture reference: #missing in 
Unable to resolve texture reference: #missing in minecolonies:block/blockhutfisherman
Unable to resolve texture reference: #missing in minecolonies:block/blockhutsmeltery
Unable to resolve texture reference: #missingno in mekanism:item/elite_mechanical_pipe
Unable to resolve texture reference: #missing in minecolonies:block/blockhutchickenherder
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/thermodynamic_conductor/ultimate
Unable to resolve texture reference: #missing in minecolonies:block/blockhuttownhall
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/mechanical_pipe/advanced
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/logistical_transporter/elite
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/universal_cable/advanced
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/thermodynamic_conductor/advanced
Unable to resolve texture reference: #missing in minecolonies:block/blockhutsifter
Unable to resolve texture reference: #missingno in mekanism:item/ultimate_pressurized_tube
Unable to resolve texture reference: #missing in minecolonies:item/blockhutcowboy
Unable to resolve texture reference: #missing in minecolonies:item/blockhutchickenherder
Unable to resolve texture reference: #missingno in mekanism:item/restrictive_transporter
Unable to resolve texture reference: #missingno in mekanism:item/elite_thermodynamic_conductor
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/thermodynamic_conductor/basic
Unable to resolve texture reference: #missing in minecolonies:block/blockhutbuilder
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/pressurized_tube/advanced
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/restrictive_transporter
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/universal_cable/basic
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/universal_cable/ultimate
Unable to resolve texture reference: #missing in minecolonies:block/blockhutbarracks
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/pressurized_tube/ultimate
Unable to resolve texture reference: #missingno in mekanism:item/advanced_mechanical_pipe
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/pressurized_tube/basic
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/pressurized_tube/elite
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/logistical_transporter/advanced
Unable to resolve texture reference: #missingno in mekanism:item/ultimate_thermodynamic_conductor
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/mechanical_pipe/elite
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/universal_cable/elite
Unable to resolve texture reference: #missingno in mekanism:item/ultimate_mechanical_pipe
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/logistical_transporter/basic
Unable to resolve texture reference: #missing in minecolonies:item/blockhutcrusher
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/mechanical_pipe/basic
Unable to resolve texture reference: #missingno in mekanism:item/advanced_logistical_transporter
Unable to resolve texture reference: #missingno in mekanism:item/ultimate_logistical_transporter
Unable to resolve texture reference: #missing in minecolonies:item/blockpostbox
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/logistical_transporter/ultimate
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/mechanical_pipe/ultimate
Unable to resolve texture reference: #missingno in mekanism:item/elite_logistical_transporter
Unable to resolve texture reference: #missingno in mekanism:item/basic_mechanical_pipe
Unable to resolve texture reference: #missing in minecolonies:item/blockhutbuilder
Unable to resolve texture reference: #missing in minecolonies:block/blockhutcrusher
Unable to resolve texture reference: #missing in minecolonies:block/blockpostbox
Unable to resolve texture reference: #missing in minecolonies:block/blockhutcowboy
Unable to resolve texture reference: #missingno in mekanism:item/elite_universal_cable
Unable to resolve texture reference: #missingno in mekanism:block/transmitter/small/thermodynamic_conductor/elite
Unable to resolve texture reference: #missingno in mekanism:item/advanced_thermodynamic_conductor
Unable to resolve texture reference: #missing in minecolonies:item/blockhutfisherman
Unable to resolve texture reference: #missingno in mekanism:item/basic_universal_cable
Unable to resolve texture reference: #missingno in mekanism:item/diversion_transporter
Unable to resolve texture reference: #missingno in mekanism:item/advanced_universal_cable
Unable to resolve texture reference: #missing in minecolonies:item/blockhutbarracks
Unable to resolve texture reference: #missingno in mekanism:item/ultimate_universal_cable
Unable to resolve texture reference: #missing in minecolonies:item/blockhuttownhall
Unable to resolve texture reference: #missingno in mekanism:item/advanced_pressurized_tube
Unable to resolve texture reference: #missingno in mekanism:item/basic_thermodynamic_conductor
Unable to resolve texture reference: #missing in minecolonies:block/blockwaypoint
Unable to resolve texture reference: #missing in minecolonies:item/blockhutwarehouse
Unable to resolve texture reference: #missing in minecolonies:item/blockhutsmeltery
Unable to resolve texture reference: #missing in minecolonies:item/blockhutsifter
Unable to resolve texture reference: #missingno in mekanism:item/basic_logistical_transporter
Unable to resolve texture reference: #missingno in mekanism:item/elite_pressurized_tube


do you need the full log ?

**Comment by pupnewfster** [comment] 2020-02-17 15:20
Yes please provide the full log

**Comment by bloodyraoul** [comment] 2020-02-17 15:23
full log : https://pastebin.com/G8wbLz5v

**Comment by pupnewfster** [comment] 2020-02-25 17:25
Closing as 9.9.11 is now released and on curseforge. I wasn't ever able to reproduce this issue, but I believe it is now fixed after a conversation I had with giga about when the model loaders should actually be registered.

**Closed by pupnewfster** 2020-02-25 17:25 UTC
Labels: 1.15, Fixed in dev, Not reproducible, aesthetic, bug

**Comment by bloodyraoul** [comment] 2020-02-27 12:11
The version Mekanism-1.15.2-9.9.11.403.jar fixed it on my computer but I still have one of my player having it

**Comment by pupnewfster** [comment] 2020-02-27 13:23
Unsure, can you provide their latest log file

**Comment by bloodyraoul** [comment] 2020-02-27 13:36
Here is his last log : https://pastebin.com/XSkB7L07

there are a lot of errors like : 
[27Feb2020 12:58:01.396] [Server-Worker-6/INFO] [STDERR/]: [net.minecraftforge.client.model.ModelLoaderRegistry:getModel:112]: java.lang.IllegalStateException: Model loader 'mekanism:transmitter' not found. Registered loaders: forge:obj, forge:composite, forge:multi-layer, forge:bucket, minecraft:elements

or

[27Feb2020 12:58:14.341] [Server-Worker-6/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to resolve texture reference: #missingno in mekanism:block/transmitter/large/diversion_transporter

**Comment by pupnewfster** [comment] 2020-03-03 22:11
9.9.12 is out now, if it still ends up happening on it I would like the debug.log file from their logs folder, as I added a debug log so we can try to track down if it is due to a race condition. Though due to other changes I highly recommend backing up your world/emptying mekanism machines/tanks before updating to 9.9.12.

**Comment by bloodyraoul** [comment] 2020-03-09 08:52
Here is the lastest.log of this morning just after loading without mekanism textures :
[latest (1).log](https://github.com/mekanism/Mekanism/files/4305566/latest.1.log)

**Comment by pupnewfster** [comment] 2020-03-09 13:59
Can you provide the `debug.log` it should be in the same folder as the `latest.log` as I only added the message at the debug level.

**Comment by bloodyraoul** [comment] 2020-03-09 15:11
hum, i dont have this file
do i need to activate the debug level somewhere to generate it ?

**Comment by pupnewfster** [comment] 2020-03-13 21:33
I believe I just made a commit that should fix this from being able to happen. I will close the newer issue report of this #5963 when the next alpha is released.

**Comment by bloodyraoul** [comment] 2020-03-20 10:36
Since the version Mekanism-1.15.2-9.9.16.408, the problem doesnt appear anymore
seems to be fixed
good job
