### ISSUE TITLE
Cardboard box duplicates charged certus quartz

### ISSUE THREAD

**Issue by archiecarrot123** [mekanism/Mekanism#7053] opened 2021-03-13 23:20 UTC
#### Issue description:
When you place a cardboard box on a chest that contains charged certus quartz (from Applied Energistics 2), it is dropped out of the chest, like the chest was broken. No other items are dropped. The charged certus quartz remains in the chest after the cardboard box is opened, despite having fallen out.
#### Steps to reproduce:
1. Install AE2 and Mekanism
2. Place chest
3. Place charged certus quartz in the chest
4. Place a cardboard box on the chest, charged certus quartz will drop
5. Remove the cardboard box
6. Open the chest, there will still be charged certus quartz in the chest

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.55
**Mekanism:** 1.16.5-10.0.21.488
**Other relevant version:** Applied Energistics 2 8.2.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
attached

https://user-images.githubusercontent.com/16769714/111052429-cf2de700-84ae-11eb-9e07-6462da6ea0af.mp4

 video

**Comment by pupnewfster** [comment] 2021-03-13 23:32
It was a bit unclear in your post but can you reproduce this with any other items except for charged certus quartz? If you can't produce this with any other item except for charged certus quartz I am inclined to say the bug is on their end.

**Comment by archiecarrot123** [comment] 2021-03-13 23:42
It hasn't happened with any other items, however I haven't tried many others.

**Comment by BlueAgent** [comment] 2021-03-14 03:10
Could this be due to https://github.com/MinecraftForge/MinecraftForge/issues/7609 combined with the use of custom item entities? Charged certus being used for in world crafting and having those lightning particles.

**Comment by pupnewfster** [comment] 2021-03-14 03:28
No idea as I am not sure we even fire those events really beyond updating the block's state. But if it is only happening with their charged certus quartz and not things like dirt I definitely think it is on AE2's end that they are doing some weird thing to entities containing their items there isn't anything we can do about that. Going to go ahead and close this as based on what archie says it sounds like it isn't happening with mundane items which means it is extremely likely to be something that we can do anything about.

My best guess is their custom item entities aren't actually item entities at all https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/common/CommonPlayerTracker.java#L108-L114 or it has to do with them removing them themselves then adding them back which there isn't much we can do about

**Comment by BlueAgent** [comment] 2021-03-14 03:31
Forge has custom item entities get replaced in the [EntityJoinWorldEvent with HIGHEST priority](https://github.com/MinecraftForge/MinecraftForge/blob/813f3d630de31b3f0ce20955ff6e6c335bc0c0cd/src/main/java/net/minecraftforge/common/ForgeInternalHandler.java#L52-L72) scheduling them to be spawned into the world the following tick.

Because that is occuring first, mekanism doesn't get to prevent the drops with their handler as it was already "prevented" by Forge's custom item entity handler first.

**Comment by pupnewfster** [comment] 2021-03-14 03:50
Hmm, I will re-open this for now but I am not really sure there is much we can do about this.

**Comment by gjerm** [comment] 2021-03-23 16:36
Getting similar behaviour with Astral Sorcery's Constellation Papers. Please let me know if you would like me to create a separate issue for this. Issue over on their repo: https://github.com/HellFirePvP/AstralSorcery/issues/1770

**Comment by BlueAgent** [comment] 2021-04-02 06:45
I noticed that the `SetBlockCommand` doesn't drop items (when using replace mode) for vanilla tiles.

This is because it calls `IClearable#clearObj`, which tiles implementing `IInventory` implement, clearing all contains items (so they aren't dropped when removed).

Although, I think it is recommended for Forge mods to **not** use `IInventory`, but use the `IItemHandler` capability instead, which modded tiles would have to implement `IClearable#clear` and clear that handler themselves.

I think a fix for this issue would potentially require changes in Forge and/or maybe having more mods more implement IClearable on their tiles?

For now thouh it might be okay to do the same as `SetBlockCommand` and use `IClearable#clearObj`?

This will fix dupes with vanilla and modded blocks that extend from `IInventory` (e.g. [Iron Chests](https://github.com/progwml6/ironchest/blob/d3605166b00d0a4dbbc37cf0ab11c7c23c81ee92/src/main/java/com/progwml6/ironchest/common/block/tileentity/GenericIronChestTileEntity.java#L39) extends from `LockableLootTileEntity`) and also any tiles that implement `IClearable` manually (I don't know of any off the top of my head).

This won't fix tiles that don't do do the above, which is most modded tiles. (e.g. [Crates](https://github.com/MysticMods/Druidcraft/blob/40788a8f164827cfa990f89b336c84d65ca3cdbb/src/main/java/com/vulp/druidcraft/blocks/tileentities/CrateTileEntity.java#L47) from Druidcraft.)

**Comment by BlueAgent** [comment] 2021-04-14 15:39
I think a better method would be to:
- Save the state of the `doTileDrops` gamerule.
- Setting it to `false`.
- Do the [replace with a cardboard box](https://github.com/mekanism/Mekanism/blob/b0a96e1eb7b5f5741cb1ca2f4ce656084ae923d5/src/main/java/mekanism/common/item/block/ItemBlockCardboardBox.java#L98).
- Restore the previous state of the gamerule.

This feels somewhat hacky though... But it'll work for the majority of cases I think.

Alternatively do the above with `World#restoringBlockSnapshots` and setting it to `true` instead. This is probably a very bad idea though... XD

**Comment by pupnewfster** [comment] 2021-04-14 17:52
The solution I probably will look into when I get a chance to look into is discussing with forge about moving their listener from highest to high so that mods can cancel spawns of items with custom item entities by using highest.

**Closed** 2021-12-22 19:43 UTC
Labels: bug, interaction, moderateimportance, needs review, Fixed in dev, 1.16

**Comment by Technici4n** [comment] 2022-01-09 13:46
Hmmm, did this end up being fixed somehow?

**Comment by pupnewfster** [comment] 2022-01-09 13:49
It should be fixed? I has been quite a while since I tested though (and I think I tested with AS not AE2) https://github.com/mekanism/Mekanism/commit/ce40a58b8fb7ae1f026a7bc5caedef512fc31d53#diff-8099868176762c57c5cde3346ee425c56c44d4e77777e137d831cbb10304db7aL92-L99

**Comment by Technici4n** [comment] 2022-01-09 13:52
I don't think we have AE2 custom item entities behave differently from AS' in that regard. That fix looks appropriate, perfect. :+1:
