### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Notraly** [mekanism/Mekanism#6078] opened 2020-04-18 20:22 UTC
#### Issue description:
Multi-player server crash when I place **Basic Pressurized Tube** after restart, the baci pressurized tube is present.

#### Steps to reproduce:
Unknown

#### Version :
**Forge:** 31.1.46
**Mekanism:** 1.15.2-9.9.17.409
**Other relevant version:** modpack Valhelsia 2 v2.1.6

log : https://pastebin.com/q440yddP
crash report : https://pastebin.com/MUSNPHh7

**Comment by pupnewfster** [comment] 2020-04-18 20:24
No idea what is going on but given a good amount of changes have taken place about transmitters since 9.9.17 I am closing this. If you are able to reproduce this issue with Mekanism 9.10.0 or higher feel free to comment and I will reopen it.

**Closed by pupnewfster** 2020-04-18 20:24 UTC
