### ISSUE TITLE
Placing a Thermal Evaporation Block Freeze the world / server

### ISSUE THREAD

**Issue by TheForceteam** [mekanism/Mekanism#5417] opened 2019-04-19 16:12 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When you place a Thermal Evaporation Block it freezes the world / Server

#### Steps to reproduce:
1. Place a thermal evaporation block

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2831
**Mekanism:** 1.12.2-9.6.8.366
**Other relevant version:** Modpack Sky Factory 4-4.0.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Client side I don't have a crash log but it freezes the game in singleplayer
Server Side/ When placing the block on a server https://hastebin.com/itujixirac.md
[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment] 2019-04-19 16:18
Duplicate of #5354 
Fixed in 9.6.9.367 and 9.7.x versions of mekanism

**Closed by pupnewfster** 2019-04-19 16:18 UTC

**Comment by thommy101** [comment] 2019-04-19 16:20
Hi!
Could you please see if this still happens in the latest version? There have been a bunch of fixes and optimalisations with multi block structures.
