### ISSUE TITLE
CraftingManager error

### ISSUE THREAD

**Issue by 123Kappa** [mekanism/Mekanism#5553] opened 2019-07-05 22:27 UTC
#### Issue description:
> [00:23:24] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <mekanism:basicblock2_4_alt_alt_alt> for output <1xtile.BasicBlock2@4> rejected inputs [1xitem.ControlCircuit@3, 1xtile.BasicBlock2@4, 1xitem.ControlCircuit@3, 1xtile.BasicBlock2@4, 1xtile.EnergyCube@0, 1xtile.BasicBlock2@4, 1xitem.ControlCircuit@3, 1xtile.BasicBlock2@4, 1xitem.ControlCircuit@3]. NOT FOUND, please report.

Happened randomly i am getting this ^ error message spammed in my console, restart did not fix it

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.52838
**Mekanism:**  1.12.2-9.7.8.379
**Other relevant version:**  Po3 version 3.41

**Comment by thiakil** [comment] 2019-07-06 02:47
duplicate of #5287

Autocrafters aren't great at recipes involving nbt

**Closed by thiakil** 2019-07-06 02:47 UTC
