### ISSUE TITLE
Metallurgic Infuser Crashing

### ISSUE THREAD

**Issue by Mello-OW** [mekanism/Mekanism#7371] opened 2021-12-26 15:38 UTC
### Issue description

When moving anything into a metallurgic infuser, I immediately crash.
Crash Log: [crash-2021-12-26_15.23.11-client.txt](https://github.com/mekanism/Mekanism/files/7777184/crash-2021-12-26_15.23.11-client.txt)
 

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.0 (Latest)

### Other relevant versions

Playing this in FTB University 1.16.

**Comment by pupnewfster** [comment] 2021-12-26 16:19
Was this on a server? Also if it was do you happen to know if they recently ran `/reload`? (I am currently more just trying to think of cases of how this could even happen)

**Comment by Mello-OW** [comment] 2021-12-26 16:52
Yeah it was on a server, I've been messing around trying to fix it and a clean install of University seemed to have fixed the issue, if I have anymore problems I'll make a new post but for now it should be fine. I have no idea what could've caused this.

**Comment by pupnewfster** [comment] 2021-12-26 17:10
Hmm okay, I will leave this open for now just to try and remember to look into it a little to see if I can reproduce it but if I can't then I will end up closing it due to it likely just being some weird cross mod interaction/things not necessarily updating fully properly.

**Comment by Mello-OW** [comment] 2021-12-26 17:58
Yeah, I'm pretty sure it's exactly that. I've had no problems so far with crashing so it was probably just a problem of not updating properly with the FTB app. Thank you for your help.

**Closed** 2022-01-01 15:24 UTC
Labels: needs review, Not reproducible, 1.16
