### ISSUE TITLE
Render crash when interacting with Basic Fluid Tank

### ISSUE THREAD

**Issue by sadovsf** [mekanism/Mekanism#6930] opened 2021-01-28 20:14 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Renderer crashes when user right mouse button interacts with Basic Fluid Tank. First time it crashed when tank was empty and i did click it. Second time it was full and i tried to add more lava into it.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.16.5-geckolib-3.0.4a
**Mekanism:** Mekanism-1.16.4-10.0.18.445
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2021-01-28_21.06.17-client.txt](https://github.com/mekanism/Mekanism/files/5889755/crash-2021-01-28_21.06.17-client.txt)

**Comment by pupnewfster** [comment] 2021-01-28 20:20
Best guess so far from #6913 and #6926 is that optifine is breaking something to do with resource packs or the `TextureStitchEvent.Pre` event as I cannot reproduce it. I did add some fallback code to at least not crash in my local branch earlier today, which I plan on committing later, but not sure when 10.0.20 will be released yet with the included "patch" as there are still a bunch of other things I want to address/fix and bumping the version just because optifine is being stupid and is breaking stuff isn't really high on my priority list.

**Closed by pupnewfster** 2021-01-28 20:20 UTC
