### ISSUE TITLE
Induction Cell max energy show incorrect

### ISSUE THREAD

**Issue by evileyecc1** [mekanism/Mekanism#5634] opened 2019-08-31 07:49 UTC
### Issue description:
Advanced Induction Cell show it can store 2.14GJ.But Elite and Ultimate show 2.14GJ too.Even in the Induction Matrix,
 
#### Steps to reproduce:
1.Build a Induction Matrix with Elite and Ultimate induction cell.It will only show maxium 2.14GJ
#### Version (make sure you are on the latest version before reporting):
**Forge:1.12.2-forge1.12.2-14.23.5.2838
**Mekanism:Mekanism-1.12.2-9.8.1.383

**Comment by evileyecc1** [comment] 2019-08-31 07:49
![image](https://user-images.githubusercontent.com/22828359/64061002-f55e9f80-cc06-11e9-8684-a36edfc4485a.png)

**Comment by pupnewfster** [comment] 2019-08-31 12:56
Duplicate of #5609

**Closed by pupnewfster** 2019-08-31 12:56 UTC
