### ISSUE TITLE
CB Multipart updated, but Mekanism does not supported it.

### ISSUE THREAD

**Issue by tuturox91** [mekanism/Mekanism#7429] opened 2022-03-19 10:55 UTC
### Issue description

Will there ever be support for Mekanism, CB Multipart for wires and pipes on 1.16.5?
Please this is so need. 1.16.5 is strong version, need litle update for cables and tubes.  This is so necessary, I beg you.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.31

### Mekanism version

10.1.2 (Latest)

**Comment by Robball14** [comment] 2022-03-19 11:26
![unknown-27](https://user-images.githubusercontent.com/54327191/159119208-3658c2e3-a6e7-4ec9-b897-31899a3a5e89.png)

Response from the discord, which i reccomend to join: https://discord.gg/nmSjMGc

**Comment by pupnewfster** [comment] 2022-03-19 14:19
Duplicate of https://github.com/mekanism/Mekanism-Feature-Requests/issues/114

**Closed by pupnewfster** 2022-03-19 14:19 UTC
