### ISSUE TITLE
Sound Cutting out 

### ISSUE THREAD

**Issue by Tatters1526** [mekanism/Mekanism#6571] opened 2020-09-23 04:52 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
having 288 wind Generators near each other out cuts the sound out for the whole server.

#### Steps to reproduce:
1.288 Wind Generators 
2.12 wide x 12 L
3.all in one chunk with a quantum entangloporter with anchor upgrade 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1- 32.0.108
**Mekanism:** MekanismGenerators-1.16.1-10.0.9.432.jar
--**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment] 2020-10-22 18:28
I am not able to reproduce this at all so no idea what is going on. Also 12x12 would be 144 wind generators not 288. I tried both 12x12 and 24x12. Is this something that only happens on a server or can you reproduce it in single player as well. Also are there any errors being printed to either the client's log or the server's log?

**Comment by Tatters1526** [comment] 2020-10-22 19:35
It would only happen on a server and there wasn't any error log and yes I
could reproduce it

**Comment by pupnewfster** [comment] 2020-10-23 19:50
Ok, tried to reproduce it again this time on a server and I am still not able to reproduce it so my best guess is that maybe another mod you have installed is causing sound to break.

**Comment by Tatters1526** [comment] 2020-10-23 21:16
maybe it was just odd that when i took the wind gens out the sound came
back but once i added them back it broke

**Comment by pupnewfster** [comment] 2020-10-23 21:54
Ya no idea, for now I am going to close this issue, but if you manage to find some reliable way to reproduce it with a limited set of mods feel free to comment and I will reopen it and try to look into it further.

**Closed by pupnewfster** 2020-10-23 21:54 UTC
Labels: 1.16, Not reproducible, minorimportance
