### ISSUE TITLE
fission going crazy in certain situation

### ISSUE THREAD

**Issue by Mrkripl** [mekanism/Mekanism#7549] opened 2022-07-12 17:35 UTC
### Issue description

my fission goes crazy when i put industrial alarm and redstone on logic adapters
I have it so it scrams when it overheats but instead it breaks I tried rebuilding it but it didnt help
it can be replicated with a button
![2022-07-12_19 34 14](https://user-images.githubusercontent.com/92227052/178556385-a79ba714-9d21-4d35-ba1d-bd261ac42767.png)

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.54

### Mekanism version

10.2.1

**Comment by Mrkripl** [comment] 2022-07-12 18:18
on the left is high temperatur and on the right is activation
![2022-07-12_20 17 03](https://user-images.githubusercontent.com/92227052/178565882-5a353bfd-0919-4495-a388-f0c969e5180a.png)
![2022-07-12_20 17 01](https://user-images.githubusercontent.com/92227052/178565875-8ee4ab39-df9e-497d-934c-b0b9724c62d5.png)

**Comment by Omikron-Delta** [comment] 2022-07-12 18:33
This is intended behavior, Activation enables the reactor with a signal on, and deactivates with a signal off.

**Comment by Mrkripl** [comment] 2022-07-12 18:35
yes thats what i meant for it to do but when it sends redstone signal it deactivates it like it was missing a block

**Comment by pupnewfster** [comment] 2022-07-12 18:55
Duplicate of #7494 
You need to update Mekanism, this was fixed in 10.2.2 and the latest/final for 1.18 is 10.2.4

**Closed by pupnewfster** 2022-07-12 18:55 UTC

**Comment by Mrkripl** [comment] 2022-07-12 18:56
thank you for help
