### ISSUE TITLE
Quantum Entangloporter is not fast

### ISSUE THREAD

**Issue by IBlackjk** [mekanism/Mekanism#7279] opened 2021-07-29 18:41 UTC
### Issue description

I play against my friends in minecraft so i decidet to let the steam from my 5x5x5 reactor per Quantum Entangloporter to my turbine. i tried it first with with normal pipes ect it worked fine but after placing them apart and use the Quantum Entangloporter the Steam was taken out way to slow. i just tried it in creative with just a few blocks apart so im sure the chunks are loaded but still the same result with normal cable it works with the Quantum Entangloporter the steam is taken out to slow.

### Steps to reproduce

1. Build a reactor
2. Build a turbine
3. connect them normally
4. look if steam flow is right
5. destroy the cable for steam 
6. let the steam from the reactor get into the Quantum Entangloporter and out at the turbine
7. see the Steam flow

### Minecraft version

1.16.5 (Latest)

### Forge version

1.16.5-forge-36.1.32

### Mekanism version

10.0.21 (Latest)

### Other relevant versions

MekanismGenerators-1.16.5-10.0.21.448
MekanismTools-1.16.5-10.0.21.448

**Comment by jaz0894** [comment] 2021-08-09 20:48
This is not a bug, the transfer rate is specified on the config of the mod. Entanglopoter won´t support the level of steam produced by a reactor unless you play with config.

**Comment by pupnewfster** [comment] 2021-08-10 21:51
As said this isn't a bug so I am going to go ahead and close this. When addressing  #6473 there is a good chance we will make some tweaks to how the entangloporter works as well

**Closed by pupnewfster** 2021-08-10 21:51 UTC
