### ISSUE TITLE
Crash when placing machines with stored energy

### ISSUE THREAD

**Issue by Anthony-LXXV** [mekanism/Mekanism#5875] opened 2020-02-14 15:55 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash when placing machines with stored energy

#### Steps to reproduce:
1. Place machine.
2. Charge it.
3. Remove it.
4. Crashes when machine is placed back.

####Version (make sure you are on the latest version before reporting):
Forge:31.1.1 
Mekanism-1.15.2-9.9.9.401
**Other relevant version:** 

Crashlog
https://pastebin.com/JKSuwdJV

**Comment by Yoosk** [comment] 2020-02-14 15:58
I don't think that mekanism is the issue but i would need lastest.log to confirm that.

**Comment by Anthony-LXXV** [comment] 2020-02-14 16:08
latest log
https://pastebin.com/msm96pS4

**Comment by pupnewfster** [comment] 2020-02-14 16:08
From the crash log this looks like an issue with inventory generators, my guess is that they are caching or doing something odd that makes it so that they think you still have the item in your inventory after you have placed it. Given there should be no way that our capability is on the empty stack, but given inventory generators has not updated their source on github past 1.12, there is not much more I can do on my end to see if it is a bug on our end, or just an issue with something they are doing.

**Comment by Anthony-LXXV** [comment] 2020-02-14 16:14
I disabled Inventory Generators, no more crash. Thanks

**Comment by Anthony-LXXV** [comment] 2020-02-14 16:17
I was using the beta from from curseforge,
inventorygenerators-1.15.1-1.0.1.jar

**Comment by owmii** [comment] 2020-02-23 17:07
Same crash happened with the player transmitter in my (Powah!) mod.

**Forge:** 31.1.14
**Mekanism:** 1.15.2-9.9.10.402

#### Crash log: https://pastebin.com/ksHhyjN4

**Comment by pupnewfster** [comment] 2020-02-23 18:06
Asking some questions in the forge discord to see where this needs to be fixed, but from what I can tell it has to do with the fact that item stacks don't invalidate their attached capabilities when they become empty.

**Comment by pupnewfster** [comment] 2020-02-23 18:35
Still not fully sure it is not partially a forge problem but added a patch/fix that will at least stop the crash from our side for the next alpha.

**Comment by owmii** [comment] 2020-02-23 20:42
That's so weird because the crash happen even when i'm in creative mode, i mean when the item stack doesn't shrink or set to air, sorry for late answer.

**Comment by pupnewfster** [comment] 2020-02-25 17:42
Closing as 9.9.11 is now released and on curseforge, and from my testing this issue no longer occurs.

**Closed by pupnewfster** 2020-02-25 17:42 UTC
Labels: 1.15, Fixed in dev, bug, confirmed, interaction, moderateimportance

**Comment by owmii** [comment] 2020-02-25 18:53
Confirmed!!
