### ISSUE TITLE
[Suggestion] Allowing to use the same face for imput and extra

### ISSUE THREAD

**Issue by cerovest** [mekanism/Mekanism#5567] opened 2019-07-16 16:04 UTC
**Describe the the feature you'd like:**
It would be great to be able to use the same face for input and extra on machines for a better implementation into autocrafting with AE2.

**Describe alternatives you've considered:**
I know you can just import what you need directly but when you do it this way you loose count on your resources, you can also use a chest before but for some unknown reasons it crashes (i don't know if it is because of mekanism or enderio for that)

**Comment by thiakil** [comment] 2019-07-20 14:15
Similar to #4225 - its designed this way

**Comment by pupnewfster** [comment] 2020-02-05 02:39
Closing this as it is designed in that way. You can use something like the quantum entangloporter so that you can insert or output multiple different types of things (say input both items and fluids or input items and output fluids), but it is intended and by design that you cannot input and output one type of thing from one side.

**Closed by pupnewfster** 2020-02-05 02:39 UTC
Labels: enhancement
