### ISSUE TITLE
Teleporting from the End to the overworld puts you at your spawnpoint

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5857] opened 2020-02-07 15:40 UTC
When Teleporting across dimensions you will be teleported to your spawn point instead of the teleporter. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.0
**Mekanism:** Mekanism-1.15.2-9.9.9.401.jar

**Comment by pupnewfster** [comment] 2020-02-07 17:52
Going to do some testing later but is this via the portable teleporter or two linked teleporters? As I had thought I tested to confirm two linked teleporters worked properly after there was a change in forge that I was unsure if would break things/require a change to be made on our end.

**Comment by pupnewfster** [comment] 2020-02-07 17:57
I don't seem to be able to reproduce this, using a teleporter to teleporter or portable teleporter to teleporter. Not even after setting my spawnpoint using a bed in case it was due to not having an actual spawnpoint set.

**Comment by Darkere** [comment] 2020-02-07 18:18
Hmm then It might be the modpack. Gonna try with just mekanism.

**Comment by Darkere** [comment] 2020-02-07 18:22
Yeah my bad. It only happens when teleporting from the End dimension. Teleporting from the nether works just fine.

**Comment by pupnewfster** [comment] 2020-02-08 19:20
Looked into this some, and there are a couple things going on:
1. Now that forge has an `ITeleporter` again I need to reimplement support for it (it just so happens that our teleportation code still works correctly from nether to overworld without it (though maybe something weird is still going on anyways))
2. In regards to fixing teleporting back from the end, that will have to wait for https://github.com/MinecraftForge/MinecraftForge/pull/6505 to be merged as the special handling vanilla has for end -> overworld for player's currently is ran regardless of the implementation for custom teleporters.

**Comment by pupnewfster** [comment] 2020-02-16 15:38
This is "fixed" in 9.9.10 but requires the forge PR to be merged for it to actually be fixed/work properly, so once it is merged it will work even without us releasing another version, but I am leaving this open until it gets merged and we then require the version of forge with the fix included.

**Comment by pupnewfster** [comment] 2020-02-17 16:24
Updating to forge 31.1.13 should fix this issue while using 9.9.10. Leaving this issue open until we release 9.9.11 which will require at least forge 31.1.13 to ensure everyone is using the fixed version.

**Comment by pupnewfster** [comment] 2020-02-25 17:24
Closing as 9.9.11 is now released and on curseforge, and requires a version of forge with this fix included.

**Closed by pupnewfster** 2020-02-25 17:24 UTC
Labels: 1.15, Fixed in dev, Mekanism, bug, interaction
