### ISSUE TITLE
[Small Bug] The color issue related to infusing factory

### ISSUE THREAD

**Issue by ScottCTD** [mekanism/Mekanism#6666] opened 2020-10-28 11:21 UTC
#### Issue description:

Like the pic following, the frame of the "extra" slot is purple
![image](https://user-images.githubusercontent.com/35100768/97429473-6d7f3d00-1952-11eb-8b66-fc8ef9922af4.png)

However, in the configuration of sides, the "extra" tool tip has yellow color.
![image](https://user-images.githubusercontent.com/35100768/97429577-93a4dd00-1952-11eb-9928-1e8f598ea4eb.png)

Very small bug, or may be I misunderstand something?

#### Steps to reproduce:
1. Open the GUI of infusing factory
2. You will see that

#### Version (make sure you are on the latest version before reporting):
**Forge: 34.1.25** 
**Mekanism: Mekanism-1.16.3-10.0.12.437.jar** 
**Other relevant version: Minecraft 1.16.3 Java 8u261** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
none

**Comment by Robball14** [comment] 2020-10-28 11:23
switch to the newer versions, the mod got update to 10.0.15 2 days ago, if it happens there too edit the report with the newer version

**Comment by Robball14** [comment] 2020-10-28 12:59
just tried by myself, it shows up in 10.0.15 and also in forge 34.1.33. i don't think it's a bug, it's more like they forgot to change that or they left it like that.

**Comment by pupnewfster** [comment] 2020-10-28 13:45
Fixed by https://github.com/mekanism/Mekanism/commit/b05e24d59c07893cdbcf6bc5aa148cd2ea5246d4

**Comment by ScottCTD** [comment] 2020-10-28 14:05
Ok copy that thanks!

**Comment by pupnewfster** [comment] 2020-10-28 14:06
We leave fixed issues open until a release with the fix is made so that it is easier to see when the issue is no longer a thing.

**Comment by ScottCTD** [comment] 2020-10-28 14:07
OK!

**Closed** 2020-11-03 00:10 UTC
Labels: 1.16, Fixed in dev
