### ISSUE TITLE
Server log spam issue due to invalid recipes

### ISSUE THREAD

**Issue by xJon** [mekanism/Mekanism#5845] opened 2020-02-03 14:16 UTC
#### Issue description:
Some players of my modpack reported the server log to have multiple warnings regarding invalid recipes from Mekanism. See [here](https://github.com/xJon/The-1.12.2-Pack/issues/191).
It is possible to remove the problematic recipes with CraftTweaker to stop the error spam in the log but then the items are not craftable, of course.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2847** 
**Mekanism: 9.8.3.390** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/0EV1zMLK

**Comment by pupnewfster** [comment] 2020-02-04 23:11
Duplicate of #5287

**Closed by pupnewfster** 2020-02-04 23:11 UTC
Labels: Old MC, duplicate

**Comment by xJon** [comment] 2020-02-05 08:05
@pupnewfster I have not noticed that issue, but as @syndran mentioned there, AE2 says they are only warning about invalid recipes. Is there no solution?

**Comment by pupnewfster** [comment] 2020-02-05 12:20
Not really for a couple reasons:
1. We are not really working on 1.12 anymore (and this shouldn't be an issue in 1.15 as we flattened things so don't have a bunch of recipes that require NBT)
2. This is a warning that AE2 throws when recipes require the use of NBT to determine various information about them.
