### ISSUE TITLE
Fusion Reactor Shuts down when i login in

### ISSUE THREAD

**Issue by Jarrod9991** [mekanism/Mekanism#7785] opened 2023-05-07 08:15 UTC
### Issue description

Every time i login to my world, my fusion reactor is always shut down, i thought it was a chunk issue because it wasnt all in 1 chunk, i moved it over and it still does the same thing, i have plenty of fuel so i know thats not the issue, i have to reform the reactor, and when i do, i have to set the fuel to 2 and then back up to 10 where i normally have it before it'll build heat up again

### Steps to reproduce

Every time i exit and open my world

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

34.1.42

### Mekanism version

Older

**Comment by pupnewfster** [comment] 2023-05-07 16:00
I believe this is a duplicate of #7587

**Closed by pupnewfster** 2023-05-07 16:00 UTC
