### ISSUE TITLE
Advanced Purifying Factories Bug

### ISSUE THREAD

**Issue by harinezumisan** [mekanism/Mekanism#7918] opened 2023-11-09 14:46 UTC
### Issue description

This happened on a friend's ModPack server
I am unable to put ore ore ore into Advanced Purifying Factories!
I was able to do this before, but it is a mystery.
This occurred after about 3,000 ore pellets had been processed
Electricity and oxygen are replenished to full and ready to operate.
I have tried removing the upgrade and other things, but no improvement.
This occurred while operating in a 3X line condition
(sorry for the translation)

### Steps to reproduce

Many gemstones are made to be processed
Then we may be able to reproduce the bug that will eventually prevent them from feeding in to the pre-processing place.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge47.1.3

### Mekanism version

10.4.2 (Latest)

### Other relevant versions

All the Mods 9 1.20.1 0.2.10

**Comment by thiakil** [comment] 2023-11-09 14:53
Duplicate of #7845

**Closed as not planned by thiakil** 2023-11-09 14:53 UTC

**Comment by harinezumisan** [comment] 2023-11-09 16:17
It seems to me that you are attaching a duplicate, but the contents are completely different.
Please take care of this.
If you need a video, I can provide one.

**Comment by harinezumisan** [comment] 2023-11-09 16:19
I now understand that he is a terrible author who leaves bugs in the dust.

**Comment by thiakil** [comment] 2023-11-09 23:17
The cause is the same - from what I understand it was working and then it stopped, possibly after a restart of a server?
