### ISSUE TITLE
Digital Miner disabled filters do not work

### ISSUE THREAD

**Issue by uhloin** [mekanism/Mekanism#7766] opened 2023-04-07 12:27 UTC
### Issue description

I used a Digital Miner with filters: 
1. fluorite ore, 
2. deepslate fluorite ore, 
3. uranium ore, 
4. deepslate uranium ore. 

Ore is transported to main base with entangloporter.

Next, I found that I have too much of fluorite and click "Disable" in 1,2 filters of Digital Miner. After restart, miner continued mining of fluorite. Then I deleted 1-2 fluorite filters. But digital miner still continued mining of fluorite. Only after I broke miner and set it back it stopped mining of fluorite and mine only uranium as expected.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

10.3.8 (Latest)

**Comment by pupnewfster** [comment] 2023-04-10 15:17
To confirm, by restart you mean like a game/world restart and not just from hitting stop/reset and start on the miner right? If so I think I probably know the cause and it is the same thing as #7769 as when looking into it I just noticed a missing check in relation to if a filter is enabled or disabled when loading filters from nbt.

**Comment by uhloin** [comment] 2023-04-11 09:23
By restart I mean just hit buttons in the Miner, not restart of the game.

**Comment by pupnewfster** [comment] 2023-07-15 03:06
I believe this is fixed as of Mekanism 10.3.9, but if you could confirm that would be great!

**Closed** 2023-08-01 01:13 UTC
Labels: needs review, Waiting Feedback, To be confirmed, 1.19
