### ISSUE TITLE
Mekanism bug

### ISSUE THREAD

**Issue by Fabibuster** [mekanism/Mekanism#7231] opened 2021-06-11 23:00 UTC
Hello,
Everytime i switch mode on any tool it does not apply it. On the screenschot it says it is disabled but i am flying, same when i am charging my tools up. To really change the mode i need to switch mode drop it pick it up and then it is changed  it is since i installed MekanismGenerators
VERSION: Mekanism: 10.0.21.448, MekanismGenerators: 10.0.21.448
![1](https://user-images.githubusercontent.com/64782098/121756032-1f9dfa80-cb19-11eb-87ca-56e589c31012.PNG)

**Comment by Seniorendi** [comment] 2021-06-11 23:01
You have not followed the form. What version do you use?

**Comment by Fabibuster** [comment] 2021-06-11 23:03
Mekanism: 10.0.21.44, MekanismGenerators: 10.0.21.448 it is since i installed MekanismGenerators

**Comment by pupnewfster** [comment] 2021-06-16 16:36
Does this happen in single player? And if not is it a normal forge server or are they using some weird hybrid server software.

**Comment by Fabibuster** [comment] 2021-06-16 16:43
It is a normal forge server. I haven't tried it in single player so far

**Comment by Fabibuster** [comment] 2021-06-16 16:45
but today i found out sometimes when i join the server it works like it should be but after re-equiping it doesn't work anymore. + same with meka tools and meka armor

**Comment by pupnewfster** [comment] 2021-06-16 16:50
Hmm not quite sure what is going on given it seems like a sync bug where the server isn't syncing items in your inventory when they change for some reason.

**Comment by Fabibuster** [comment] 2021-06-17 11:32
I tried it out now and it seems like it is no sync bug, because it doesn't work in singleplayer worlds either

**Comment by pupnewfster** [comment] 2021-06-17 13:21
Could you try on a fresh instance with just mekanism installed (and just spawn various stuff in via creative for testing). Given single player still has two sides an integrated server and the client so there is still a slight chance that if it is a mod screwing it up and isn't something on Mek's end that it would be breaking syncing in single player as well.

**Comment by Fabibuster** [comment] 2021-06-17 13:28
Ok, but with Mekanism Generators because it is since i installed that

**Comment by pupnewfster** [comment] 2021-06-17 13:40
Sure, when I said with just Mekanism I meant Mekanism and any of our official addons you wish to include in the test be it none or all.

**Comment by Fabibuster** [comment] 2021-06-17 13:49
In the new Instance it works fine how it should

**Comment by Fabibuster** [comment] 2021-06-17 14:11
It works fine even with all the mods added just on the other Profile it doesn't work

**Comment by pupnewfster** [comment] 2021-06-17 18:58
I am going to go ahead and close this then as I can't reproduce it either and assume that it probably was some other mod that maybe had its configuration get screwed up or something and was causing the things to not sync properly from server to client side.

**Closed by pupnewfster** 2021-06-17 18:58 UTC
Labels: 1.16, To be confirmed, Waiting Feedback
