### ISSUE TITLE
Induction Matrix bugged power storage.

### ISSUE THREAD

**Issue by Tobuscouse** [mekanism/Mekanism#5664] opened 2019-10-08 14:53 UTC
I am getting a good ways into Enigmatica 2 Expert and started building the induction Matrix to store my power in. I looked at the induction cells and every one of them but the basic shows the same capacity, I went into creative and tested it. When the multiblock structure is complete they all show they store the same power (other than basic again). I even put multiple cells in to test it and the number stays the same. Tested it in a creative world with an ultimate cell and it doesn't show that it is full on the left, but it's current power/capacity is 2.14GRF/2.14GRF and just voiding any extra power. Basic- https://prnt.sc/pgccmt Advanced- https://prnt.sc/pgcd1x Elite- https://prnt.sc/pgcd8u Ultimate- https://prnt.sc/pgcdlz Mekanism Version: 1.12.2-9.8.1.383

**Comment by pupnewfster** [comment] 2019-10-08 14:55
Duplicate of #5609 this was fixed in 9.8.2

**Closed by pupnewfster** 2019-10-08 14:55 UTC
