### ISSUE TITLE
NPE when adding/removing upgrades

### ISSUE THREAD

**Issue by LemADEC** [mekanism/Mekanism#5625] opened 2019-08-24 09:02 UTC
#### Issue description:
Client NPE crash when removing upgrades on a multiplayer server.

#### Steps to reproduce:
1. Open a electrolythic seperator
2. Remove energy upgrade
=> NPE

A hardcrash was also observed by adding upgrades to a Metallurgic infuser, no crashreport generated through, so can't confirm.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 1.12.2-9.8.1.383
**Other relevant version:** https://www.curseforge.com/minecraft/modpacks/worldwarminecraft/files/2758854

**Comment by pupnewfster** [comment] 2019-08-24 20:09
This should be fixed once we release 9.8.2. I was unable to reproduce it, but it seems pretty clear *what* was causing the null pointer.

**Closed** 2019-08-24 20:08 UTC
Labels: bug
