### ISSUE TITLE
PRC not accepting Plutonium gas.

### ISSUE THREAD

**Issue by Mattimus123** [mekanism/Mekanism#7880] opened 2023-10-04 03:35 UTC
### Issue description

My Pressurized reaction chamber is not accepting any plutonium gas. Yes I checked the sides for input being correct.

### Steps to reproduce

Plutonium gas in pipe
Try to put in PRC
See that it doesn't accept it.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge

### Mekanism version

10.4.0 (Latest)

**Comment by thiakil** [comment] 2023-10-04 03:50
Did you check the modpack didn't change the recipe?

**Comment by Mattimus123** [comment] 2023-10-04 03:55
I'm playing ATM 9 and it's the same, but I've since tested it on creative
world and it works fine also other people playing the pack have no issue. I
also couldn't get the gas to go from the pressurized tube to a tank.

**Comment by thiakil** [comment] 2023-10-04 04:02
Is the PRC completey empty? It won't accept a new recipe's ingredients while it still contains some of the previous ones inputs or outputs.

If not, there's already a couple of issues about pipes not working which we can't work out why

**Comment by Mattimus123** [comment] 2023-10-04 04:04
It has water and fluorite dust in it but that's it.
My other setup for polonium was the same way and it works just fine.

**Comment by AlexHgC** [comment] 2023-10-04 09:53
Can you send some screen please ? Like : 
- The setup itself
- The main UI of the PRC hovering the empty tank
- The side config UI of the PRC
- Try to connect the PRC in an other pipe, maybe the one you are trying is set to pull or none

**Comment by Mattimus123** [comment] 2023-10-04 17:11
https://i.imgur.com/hs82WI5.png
https://i.imgur.com/rnpofhI.png

**Comment by Mattimus123** [comment] 2023-10-04 17:28
I just did a server restart and it works fine now.

**Comment by iQSJoker** [comment] 2023-10-05 10:05
Just to add here, I have the full ore processing setup going. It's been working perfectly, then after server restart the ore washer specifically is no longer accepting dirty slurry. The CD Chamber is auto ejecting directly into the washer. Tried pulling the dirty slurry out via tube and attempted to push this into the washer and it still won't accept the dirty slurry. Even removing the washer and replacing with another brand newly crafted washer also doesn't work. There is absolutely nothing in any of the internal tanks with the exception of clean water. 

I am also using ATM9 but unsure if this is related.

As per the above I'm going to attempt a restart of the server to see if this resolves the issue

https://imgur.com/a/XnoYSa5

**Comment by iQSJoker** [comment] 2023-10-05 10:11
Just to confirm this works after server restart.

**Comment by thiakil** [comment] 2023-10-23 06:45
Looks like a duplicate of #7831 / #7845 which hasn't been worked out

**Closed as not planned by thiakil** 2023-10-23 06:45 UTC

**Comment by hexxone** [comment] 2023-12-25 18:12
Same issue happening for me rn. 
On Modpack ATM9, have already built the SPS and Fusion Reactor, but all of a sudden PRC stopped accepting Plutonium.
I already tried everything, even crafting a new PRC and placing it somewhere else.
Weirdest part is, it still accepts Water but not the Plutonium Gas OR Items from Refined Storage.
But Water - no problem.

Now I guess I'll have to wait for the server admin to get online and hope it goes away...

**Comment by Nidaelie** [comment] 2024-06-27 13:56
Happening to me also....

Modpack has the default recipe, waited for a server reset and prc isnt accepting the plutonium from the centrifuge...
tried 2 diff prc a dn a new crafted one and nothing....
