### ISSUE TITLE
Logistical Transporters not predicting future insertion

### ISSUE THREAD

**Issue by aidancbrady** [mekanism/Mekanism#5865] opened 2020-02-12 04:42 UTC
#### Issue description:
Logistical Transporters are not predicting future item insertion. Happening with all inventories and tiers.

#### Steps to reproduce:
1. Place Logistical Transporters pulling from an inventory to another
2. Have Transporter pull items from origin inventory
3. When items are traveling to the destination, the transporter will keep pulling items even if future items would fill the inventory

**Comment by pupnewfster** [comment] 2020-02-16 15:03
Closing this as 9.9.10 is now up and on curseforge.

**Closed by pupnewfster** 2020-02-16 15:03 UTC
Labels: 1.15, Fixed in dev, bug, important

**Comment by MarkL4YG** [comment] 2020-05-03 14:39
Hi there,
I am stumbling on this issue while I was investigating TPS loss issues on our server that seem to be caused by this bug.  
Is this fix going to be backported to 1.12.2 or is that MC version considered EOL for Mekanism as the mod is already build against 1.15 and backporting would be too much of a hassle?

**Comment by pupnewfster** [comment] 2020-05-03 14:41
1.12.2 is EOL as we would rather spend our time working on developing Mekanism V10 than spending hundreds of hours trying to backport things to 1.12.

**Comment by MarkL4YG** [comment] 2020-05-03 14:45
Understandable.
I would offer to submit a PR for this as we're (sadly) not ready to upgrade MC versions at the moment and depend on this fix. Would you be willing to review and accept such proposals? And, if so, can you pin-point me to the fix in V10 so I can replicate the fix as similar as possible?
