### ISSUE TITLE
enrichment chamber does not work...

### ISSUE THREAD

**Issue by sarah-charlotte-white** [mekanism/Mekanism#5819] opened 2020-01-27 15:25 UTC
Hello. You published a nice mod.

The issue is that "enrichment chamber" does not work properly.
I want to create obsidian dust.
I can't set obsidian. It does not enter.

Usage
Forge-1.15.2-31.0.0
Mekanism-1.15.2-9.9.4.395
MekanismGenerators-1.15.2-9.9.4.395
MekanismTools-1.15.2-9.9.4.395
MekanismAdditions-1.15.2-9.9.4.395
(jei-1.15.2-6.0.0.2)
(walljump-1.15.2-1.3.3)
(Xaeros_Minimap_20.1.0_Forge_1.15.2)
No other MOD

Thanks for your hard work.

**Comment by pupnewfster** [comment] 2020-01-27 15:42
Duplicate of #5805 updating mekanism will fix it

**Closed by pupnewfster** 2020-01-27 15:42 UTC

**Comment by sarah-charlotte-white** [comment] 2020-01-28 13:14
Thank you for your reply.

sorry.
I couldn't find a duplicate note.

Thanks for your hard work.
