### ISSUE TITLE
No texture when the player is in fluids

### ISSUE THREAD

**Issue by Lolothepro** [mekanism/Mekanism#8113] opened 2024-06-15 16:41 UTC
### Issue description

```
Failed to load texture: minecraft:misc/underwater
java.io.FileNotFoundException: minecraft:misc/underwater
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.ResourceProvider.lambda$getResourceOrThrow$1(ResourceProvider.java:23) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading}
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.ResourceProvider.getResourceOrThrow(ResourceProvider.java:23) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.texture.SimpleTexture$TextureImage.load(SimpleTexture.java:83) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.texture.SimpleTexture.getTextureImage(SimpleTexture.java:58) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.texture.SimpleTexture.load(SimpleTexture.java:29) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:96) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.texture.TextureManager.register(TextureManager.java:68) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.texture.TextureManager.getTexture(TextureManager.java:118) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:725) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:718) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.ScreenEffectRenderer.renderFluid(ScreenEffectRenderer.java:105) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/neoforge@21.0.6-beta/net.neoforged.neoforge.client.extensions.common.IClientFluidTypeExtensions.renderOverlay(IClientFluidTypeExtensions.java:156) ~[neoforge-21.0.6-beta-universal.jar%23176!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.ScreenEffectRenderer.renderScreenEffect(ScreenEffectRenderer.java:45) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.GameRenderer.renderItemInHand(GameRenderer.java:965) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1278) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1024) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.runTick(Minecraft.java:1198) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.run(Minecraft.java:810) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21-20240613.152323-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.1.jar%23142!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.1.jar%23142!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.1.jar%23142!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.1/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.1.jar%23142!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.2.jar%23144!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.2.jar%23144!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.2.jar%23144!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.2.jar%23144!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.2.jar%23144!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.2.jar%23144!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.2.jar%23144!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}
```

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

21.0.6-beta

### Mekanism version

10.6.0 (Latest)

**Comment by pupnewfster** [comment] 2024-06-15 16:43
Duplicate of #8099

**Closed as not planned by pupnewfster** 2024-06-15 16:43 UTC
