### ISSUE TITLE
Quantum Entangloporter lose frequencies

### ISSUE THREAD

**Issue by tkerkering** [mekanism/Mekanism#6032] opened 2020-04-05 19:51 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

When we're using quantum entangloporters and restart our server some of them lose their frequency.

#### Steps to reproduce:
1. We're playing the modpack MC.Eternal 1.3.5 which uses the current mekanism version with it's addons on a server.
2. We're using the quantum entangloporter with anchor upgrades and the chunks are also loaded seperately with ftbchunks.
3. After a server restart some of them lose their frequency, thus disconnecting cables attached to it.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2 - 14.23.5.2847
**Mekanism:** 1.12.2 - 9.8.3.390
**Other relevant version:** MC Eternal 1.3.5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment] 2020-04-05 19:52
No idea as I haven't seen this issue except in some early versions of the 1.15 version of Mekanism, but as I cannot reproduce this in the latest 1.15 version I am going ahead and closing this as we are no longer working on developing the 1.12 version of Mekanism.

**Closed by pupnewfster** 2020-04-05 19:52 UTC
Labels: Old MC
